### ISSUE TITLE
update function to add member to separate email and public_name from request body

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1021]
At present

If you type some letter you can see result of search and if he have no result you seen "no result".
If you type an email and you have no result you seen also "no result"

Expected 

- [x] If search with email give no result, don't show "no result" but show a button "invite this user"
- [x] if you click on this message, the result disappear and you can add role and validate this creation.

**Comment by Skylsmoi** [comment]
question is: How do you know it's a email ?  
I would answer: "Because it contains an @"  
But I'm not sure this is 100%, if a user has an @ in it's name, it will create bugs and unexpected behavior.  

Having the autocomplete saying "invite the user" looks like a call-to-action event though it'll only close the autocomplete popup ; I think it's misleading

**Comment by Skylsmoi** [comment]
exhaustive cases list:  
- public_name exists:
  - and known: autocomplete and API 200 ok
  - and unknown: no autocomplete and API 200 ok
- public_name not exists: no autocomplete and API 400 err
- email exists:
  - and known: autocomplete and API 200 ok
  - and unknown: no autocomplete and API 200 ok
- email not exists: no autocomplete and API 200 ok => invite sent
  
  
public_name IS email if it contains one '@' AND at least one '.'

**Comment by lebouquetin** [comment]
note: API means is `POST workspace/:id/member` API.

Behavior in invitation text field : 

- if text is considered an email (ie contains @ and .):
    - if email exist: 
        - show autocomplete
        - fill user_id in API
    - if email not exist:
        - fill `email` field in API
- if text is not considered an email:
    - show the autocomplete
    - if user selected in autocomplete, then fill user_id in API
    - if text is not an email and not a user selected in autocomplete, then fill public_name in API

Response (and behavior) of the `POST workspace/:id/member` API:

- public_name exists:
    - add the member to workspace + API 200 ok
- public_name not exists:
    - API 400 err
- email exists:
    - and known: API 200 ok
    - and unknown: 
        - if the current user can invite (ie trusted user or +) create user account + API 200 ok
        - else 403
- user_id exists:
    - same as public_name

**Comment by Skylsmoi** [comment]
@lebouquetin @inkhey   
There is a problematic case:  
If user type an email that exists and submit without clicking on the autocomplete popup entry, I can't send the id of that user to the api since the known member list api doesn't return the email, only public_name. So I can't find him in the list.

**Comment by lebouquetin** [comment]
We need to update the API in order to have 3 fields:

- public_name
- email
- user_id

@Skylsmoi you must put the information in the right field

For the case you point @Skylsmoi the solution is to always show the autocomplete and force user to select in the autocomplete.

If the typed word is an email which is unknown, then instead of "no result" you add an entry "invite this user". Doing it this way force user to select in the select field, and you won't have the case you identified

**Comment by Skylsmoi** [comment]
what the 3 fields in the API are for ?

**Comment by tracim** [comment]
The fields are for you to tell backend which user to invite. You fill one of the fields only.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi the result of research not working.
I'm an admin with role workspace manager

I have 3 account wtih test in name or email

If I type test => result is testtest
If I type test1 => result is test1
If I type test2 => result is test2

Expected: If I type test I can see this result:
testtest
test1
test2

I can see good result in json but not in frontend.

**Comment by Skylsmoi** [comment]
I have fixed the result list.

Now @inkhey shall do the necessary for the endpoint to expect to different properties "name" and "email"

**Comment by Skylsmoi** [comment]
to test: check that the add member to a workspace feature is still working
from dashboard and advanced dashboard

**Comment by PhilippeAccorsi** [comment]
Verified.
