### ISSUE TITLE
admin user: create user failed - error 500 not visible in flash message

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1035]
**At present**

Email is activated but something wrong in config of smtp

I tried to create a user with this information:
name: test1
email: test1@test1.test1
profile: user 

When I validate nothing append.

I can see this request error:

~~~
Error: 500

message | Notification for new created account can't be send (SMTP error), new account creation aborted
details | {…}
error_detail | {}
traceback | Traceback  (most recent call last):   File  "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/core/user.py",  line 411, in create_user     password=password   File  "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/mail_notifier/notifier.py",  line 426, in notify_created_account     message=message   File  "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/mail_notifier/sender.py",  line 29, in send_email_through     sendmail_callable(message)   File  "/home/algoo/repo/tracim_v2/backend/tracim_backend…ackages/hapic/decorator.py",  line 100, in _execute_wrapped_function     return func(*func_args, **func_kwargs)   File  "/home/algoo/repo/tracim_v2/backend/tracim_backend/views/core_api/user_controller.py",  line 229, in create_user     do_save=True   File  "/home/algoo/repo/tracim_v2/backend/tracim_backend/lib/core/user.py",  line 417, in create_user     ) from exc tracim_backend.exceptions.NotificationSendingFailed: Notification for  new created account can't be send (SMTP error), new account creation  aborted
code | null
~~~ 

**Expected**

- [ ] error need to be visible in flash message

**Comment by Skylsmoi** [comment]
I need an error code to handle it

**Comment by lebouquetin** [comment]
@Skylsmoi

1. You do not need an error code to show a flash message telling "there was an error".
2. You MUST always show a flash message if you get an error that you do not expect. This is the case when you receive a HTTP code not in the 2xx or 3xx range (eg 4xx or 5xx)
3. Backend can't give you an error code in that case because it's a HTTP 500 - internal server error. This is always an error case not managed on backend side, so it's not possible to return an error code.

The point 2. is the most important in my comment : you really MUST show a flash message if you get something other than a 2xx or 3xx HTTP code.

**Comment by Skylsmoi** [comment]
A flash message will now be prompted

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi translate in french is missing about flash message:

"Erreur
Unexpected error, please inform an administrator"

**Comment by Skylsmoi** [comment]
fixed in https://github.com/tracim/tracim_v2/commit/16c33b352f1ece6caef3d6dbcd12be2ab5575235

**Comment by PhilippeAccorsi** [comment]
Verified.

I special case here:
Link to https://github.com/tracim/tracim/issues/1085

**Comment by PhilippeAccorsi** [comment]
https://github.com/tracim/tracim/issues/1085
