### ISSUE TITLE
Timeline: app need to use the same code about timeline

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1055]
At present

In app file or app html-doc we can see some difference about timeline

Expected

All app use same timeline component to be sure the time line is realy identical in all app (functionnality and appearance)

**Comment by Skylsmoi** [comment]
all apps already use the same Timeline componant. https://github.com/tracim/tracim_v2/blob/develop/frontend_lib/src/component/Timeline/Timeline.jsx

Can I close this issue ?

**Comment by PhilippeAccorsi** [comment]
I have seen your discuss with @lebouquetin . I think you can close this issue.

**Comment by lebouquetin** [comment]
After a long thread with @Skylsmoi the current design is good enough for now - so no refactoring required for 2.0.

There is still some refactoring in order to make responsabilities more clear - the refactoring may concern both frontend and backend.

The goal is that app need as low as possible understanding of timeline.

**Comment by Skylsmoi** [comment]
We can close it.
I don't mean there cannot be more evolution and refactoring to the Timeline but the requirement for this issue is met.
