### ISSUE TITLE
Normalize usage of line breaks

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1090]
At present

If I reply directly by email I can see comment with big size just for one line of text. Exemple:

![capture d ecran de 2018-10-29 12-19-08](https://user-images.githubusercontent.com/25848257/47646670-eb968680-db74-11e8-9c2e-4ae8f005b9ea.png)

Expected
line breaks should be normalized

Todo:
- [ ] frontend: hack to convert comment send to api to html.
- [ ] frontend: remove display hack who convert `\n` to `<br/>` 
- [ ] frontend: surround msg with `<p>` tags

**Comment by PhilippeAccorsi** [comment]
Add information:
~~~

JSON |  
-- | --
0 | {…}
parent_id | 80
author | {…}
user_id | 1
public_name | administrateur
avatar_url | null
created | 2018-10-29T11:23:15Z
raw_content | tu vois le message?
content_id | 96
1 | {…}
parent_id | 80
author | {…}
user_id | 2
public_name | philippe@accorsi.info
avatar_url | null
created | 2018-10-29T11:23:32Z
raw_content | <p>oui très bien<br/> </p>
content_id | 97


~~~

**Comment by Skylsmoi** [comment]
after some research, there are 2 cases:
- normal text where line break are sent to api using '\n'
- rich text where line break are sent to api using `<br />`

To display line break created with normal text, frontend uses a function convertBackslashNToBr from frontend_lib.
The problem is that text created with rich text editor that contains a line break is as bellow:
`<p>My rich text</p>\n<p>My other text after line break</p>`
The line break should be generated by the 2 `<p>` tags. But, with the \n, it adds another line break.

With comments sent by email, the problem is even bigger since it is as bellow:
`\n<p>My text from email<br />\n</p>\n`
So there is even more line breaks

To normalize the behavior, frontend wont do anything to the content.
Instead, frontend will send to backend a boolean telling whether the text has been created using rich or normal text.
Then, the backend will convert the "\n" to `<br />` when text is sent using normal text editor.
For comments sent by emails, backend will also have to remove the extra line breaks

**Comment by Skylsmoi** [comment]
@lebouquetin Do you agree with my last comment ?
Note: I have edited the issue's description with todo list

**Comment by lebouquetin** [comment]
What about sending a `content type` instead? which would be `text`, `html`, ... (and possibly `markdown` etc, etc) ?

**Comment by inkhey** [comment]
@lebouquetin That look like a nice solution.
I see some problem in case we need this for other endpoint than comment (actually workspace description, file_description, etc..). Because we should be able to compare content type sended and content_type expected.

**Comment by inkhey** [comment]
After discussion a hack will be created in frontend for tracim v2.0 in order to convert all comment send as html. 
Better correction will be done later in https://github.com/tracim/tracim/issues/1101

**Comment by PhilippeAccorsi** [comment]
Verfieid.
