### ISSUE TITLE
app html-document: full screen dont show end of page

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1147]
At present

If you edit html-document in full screen you cant see the last line of the document. You scroll down but scroll doesn't go to the end. 

To reproduce:
write some text and if you don't put enough lines on bottom of the document you cant see the text you just wrote.

Expected

- [x] If you are in full screen you can see the last line of your document.

**Comment by Skylsmoi** [comment]
I have tried for a few minutes just to check if this would be easy.
I couldn't come up with an easy css fix.
The problem is not about a margin bottom, it's about the fullscreen mode which we give in css "top: 88px" to be bellow the header. But the "height: auto" of the fullscreen mode doesn't take into account the "top: 88px"

I didn't add the "fast" tag since I could find a quick and easy solution

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I remember that we have an issue with z-index problem here #943  do you think its related with this issue ?

**Comment by Skylsmoi** [comment]
It can be but not exactly. We should not solve this issue with z-index. The z-index management is the other issue

This is a height issue.
On the other hand, it would become a z-index issue if we decide to display the fullscreen mode over the tracim's header

**Comment by Skylsmoi** [comment]
it yet needs to handle the come back to normal mode ...

**Comment by PhilippeAccorsi** [comment]
Verified.
