### ISSUE TITLE
Re-introduce Radicale

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1181]
## Currently

Calendar system have been removed from v2.0.

## Expected

Re-introduce radicale server.

- [X] add Proxy mecanism to tracim
- [X] Update hapic version to support `disable_doc`
- [X] add radicale launcher with `tracimcli caldav start`
- [X] add radicale config to developement.ini file.
- [X] add proxy controller for radicale server
- [X] add lib tests for proxy
- [X] add functional test for radicale proxy
- [X] add new endpoint  `/users/{user_id}/calendar` and `/users/me/calendar`
- [X] add tests for theses endpoints
- [X] add `tracimcli caldav calendar create` command to create alls calendars
- [X] add debug mode for commands to inspect more clearly issues
- [X] force all user/workspace creation code to user execute on created method
- [X] add calendar creation  `on_created` event for both user and workspace.
- [X] remove caldav_url from user api.
- [ ] Make on created event work as hook for event, see https://github.com/tracim/tracim/issues/1487
- [X] add calendar_enabled temporary to workspace_api in order to allow frontend to activate/disactivate this.

Issues created (but not resolved) during coding this feature :
- endpoints factorization, see https://github.com/tracim/tracim/issues/1478
-  use class instead of validators, see https://github.com/tracim/tracim/issues/1477
- removing caldav_url for user in api may broke frontend https://github.com/tracim/tracim/issues/1486

**Comment by tracim** [comment]
Problems faced during development are related to trailing slash. Radicale always requires the trailing slash.

TODO :
- implement the `on_user_created` and add a command which creates the user calendar
- implement the `on_warkspace_created` and add a command which creates the workspace calendar
-  add a tracimcli command which loop on calendars and create/delete an event

**Comment by inkhey** [comment]
There is an issue with folder creation in caldav, its seems that radicale doesn't create dir when we decide to create a calendar. (There is a specific case with  auto create of /<basic-auth-user> dir)
That's why we actually create dir to avoid this problem:
https://github.com/tracim/tracim/blob/d83215fcdd55950f45ee5e3884188acc0779a668/backend/tracim_backend/lib/calendar/__init__.py#L26

see also the related issue of radicale : https://github.com/Kozea/Radicale/issues/934

**Comment by inkhey** [comment]
@lebouquetin @Skylsmoi.
It's still unclear what kind of information i should send to frontend to let him know where the calendar are.
- if i send him nothing, frontend is already able to determine where the calendar are because tracim is proxy. frontend can get `/calendar/user/{user_id}`/ calendars for example.
- if i send full url , i need specific endpoint to do so or modifiying existing endpoint for workspace and user, ex: `http://localhost:6543/calendar/user/1/`
- if i send partial url information in app config, i can give specific url information, so i don't really see what may be the goal of this. We can decide to make path of calendar proxy different but that's not really interesting , for example `/mycalendar/myuser` instead of `/calendar/user`. 
if we want to use another calendar server (working in another place and tweaked the same way as tracim radicale), we may thing about calendar path like `http://localhost:6543/calendar/user/` but that's not a good idea if we want to deal with right access. Best solution is simply to change `caldav.radicale_proxy.base_url` to make tracim calendar proxy point to another calendar server.

**Comment by inkhey** [comment]
After discussion, solution was to create an endpoint:

- it will return explicit list of single-one calendar (ressource, calendar not collection, folder of calendar) 
- url will be  `/api/v2/user/{user_id}calendar` 
- it will return list of item not just list of url some more config needed for each (currently, we think about passing or not passing auth information, which is needed for internal calendar).
- it will return only current_user calendar (personal one and user workspace one)
- filtering by workspace_id will work on those

Something like : 
```
GET http://localhost:6543/user/1/calendar?workspace_id=1
[
 {
   "url":"http://localhost:6543/calendar/workspace/1",
   "tracim_auth": true,
 }
 {
   "url":"http://externalcalendar/calendarwp1",
   "tracim_auth": false,
 }
]
```

**Comment by inkhey** [comment]
@lebouquetin @buxx In current code, i check for workspace feature enabled in workspace as workspace item contain : 
`    calendar_enabled = Column(Boolean, unique=False, nullable=False, default=False)`

Should we keep this code or should be do something else ? It will be nice that calendar stuff don't mix anymore with core of tracim (user/workspace/content).

**Comment by tracim** [comment]
Leep it for now. I do not seen where to put it in the current state of the code.

We'll probably move it when making applications really activable/deactivable

**Comment by PhilippeAccorsi** [comment]
Verified.
