### ISSUE TITLE
app folder: right about create folder or/and content in folder is not applied correctly

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1210]
at present:

User with role contributor can create folder but he cant access to app folder advanced and he cant create content in this folder.

Expected:

- [ ] Apply right about role for all content (look here https://github.com/tracim/tracim/blob/develop/backend/doc/roles.md   **warning**: role about folder is missing, issue about that is open).
- [ ] contributor cant create folder but he can create content in folder
- [ ] update documentation in backend too about this new rule

**Comment by tracim** [comment]
@PhilippeAccorsi all authorization/authentification related stuff MUST be first fixed in backend. What I understand here is "maybe the problem is frontend, maybe backend". Si first step is to validate/fix it in backend (maybe the problem does not appear in backend... if so, then add a comment in the issue telling that "checks have been done in backend and backend is ok")

**Comment by PhilippeAccorsi** [comment]
@lebouquetin ok. I have discuss with back and front before create this issue, and idea is frontend issue.

**Comment by tracim** [comment]
I understand. What I want is before assigning the issue to frontend, you *must be sure* that there are no problem in backend. It means "all checks have been done in backend", then if everything is fine (and you are sure about it) you can assign the issue to frontend.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi backend is done and merged. 
@inkhey please check all message on issue and change label and reassign when its necessary. This issue need frontend job before testing.

**Comment by PhilippeAccorsi** [comment]
Verified.
