### ISSUE TITLE
sidebar + dashborad: refresh problem when creating new shared space

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1216]
At present:

If I'm in one shared space with some content in recent activity, when I create new shared space I can see in recent activity of this new shared space the list of content that we have in previously sharedspace.

Expected

- [ ] dashboard just show content of the associated sharedspace

**Comment by tracim** [comment]
@Skylsmoi we must not have this kind of problem. All content stuff must be in a workspace context, so that we can't have content in wrong workspace. Contents are a sub-items of a workspace, it must be the same in frontend architecture.

When switching from a workspace to another, all stuff related to the workspace must be refreshed automatically (I mean... you must not code "refresh recent activity, refresh content list, refresh x or y: you code refresh workspace and everything must be contextualized so that this problem cant happen)

**Comment by Skylsmoi** [comment]
@lebouquetin It already is like that. The problem was a handler of custom event that was declared in two places and caused a double refresh of data with, for one the them, the previous workspace id. The data displayed was always the longest to respond.

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim/commit/91e58ae4f1074a263e888c629cf3e04603e23c77

**Comment by tracim** [comment]
ok, thanks for the explanation

**Comment by PhilippeAccorsi** [comment]
Verified.
