### ISSUE TITLE
Browser autocompletion is missing on login page

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1294]
## Feature description

Add autocompletion on login page. 
Minimum is to have autocompletion for email write before, but add possibility to save `email + password` its necessary also because no "Remember me" option exist on Tracim V2 (available feature in Tracim V1)

## Context

There is no browser auto completion on the entire project.

The reason is because browsers save this autocompletion on form submit and in full js applications, we don't submit form, we handle this manually with js and API.

There are some polyfill on the net, some research and test are require to find the most appropriate workaround.

React / Angular / Mozilla / Chome ... are aware of this issue, a proper fix might be released in futur

## Impacted components

*"unknown"*

**Comment by tracim** [comment]
On AirBnB there is an autocomplete on login... and airbnb is based on React - see https://www.airbnb.fr/ What do they use?

**Comment by metzgegu** [comment]
AirBnB use a `submit` type button to login, we could do the same and `preventDefault()` onClick the button.

**Comment by Skylsmoi** [comment]
Feel free to make a POC of any solution you find. With pros/cons list.
Ideally, we would prefer to avoid a full page refresh.

**Comment by PhilippeAccorsi** [comment]
@metzgegu on your poc:
I have tested on desktop version of Firefox (68.5.0esr) and Chrome (80) and its working good => its possible to save login/password

On mobile (Android 10, OnePlus 7T):
- firefox (68.5) => autocompletion is make if one login/password is saved but nothing purpose if I have saved 2 login/password
- chrome (80) => I can choose to use saved login/password (also if I have saved 2 login/password) 

Is it possible for the browser to save just login? For exemple on github, if I have not saved login/password, some login is purpose (I don't know where come from this list of login because some of one is come from another website).

**Comment by PhilippeAccorsi** [comment]
Maybe necessary documentation:
- https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element
- https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view

**Comment by PhilippeAccorsi** [comment]
After discuss with @lebouquetin:
- **highest priority** find solution to have autocompletion on email input (with history of email write in this input before)
- **normal priority** find solution for saving `email+password` on webbrowser (Firefox, Chrome, Safari. Also if possible on mobile version)

**Comment by metzgegu** [comment]
### Solutions I provide in this PR:
- Autocomplete email input when no email+password are already saved in the browser
- User can choose to save email+password in the browser

First solution needs uncontrolled inputs, because of this [issue](https://github.com/facebook/react/issues/17927)
Second solution needs only a real submit button in the form like I mentioned in my last comment

**Comment by metzgegu** [comment]
In order to use login auto completion in IOS (with any browser), login for each website has to be set in `Settings` > `Passwords & Accounts` > `Website & App Passwords` of the IPhone

**Comment by metzgegu** [comment]
The solution currently implemented in the pull request use the name: `email` for the email input, so the browser provide all email already used from every website.
If we want a list of email only used for Tracim we could use the name: `tracim_email` but some issues may appears:
- possible issue with Saphari in IOS (which use only specific name for auto completion)
- no autocomplete the first time in Tracim
- password management services may not be able to work

**Comment by PhilippeAccorsi** [comment]
Verified on branch ( wait merge to close issue)
