### ISSUE TITLE
Progressive webapp not working correctly

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1356]
Currently : 

@Skylsmoi added the manifest.json file allowing to transform tracim into a progressive webapp. Now that we have a SSL certificate, it is working... but the content is buggy and the installation of progressive webapp results in opening `<tracim host>/assets/` as home page instead of `<tracim host>`

Expected : 

- [x] use full path URIs instead of relative ones for `start_url` and `icons.src` (URIs must be like `/ui` or `/assets/icons/logo.png` - they start with a slash)
- [x] rename the `tracim_logo_192x.png` file to `wa-tracim-logo-192x192.png` (wa like webapp)
- [x] add a white background to the image (transparent is not very clear), with round corners (ask luc for help if necessary)
- [x] include all required declinations of the logo in sizes : 
    - icon-72x72
    - icon-96x96
    - icon-128x128
    - icon-144x144
    - icon-152x152
    - icon-192x192
    - icon-384x384
    - icon-512x512
    - icon-120x120 (required for iOS)
    - icon-180x180 (required for iOS)

See the stackoverflow thread: https://stackoverflow.com/questions/48839338/which-icon-sizes-are-required-for-progressive-web-apps-pwa-as-of-q1-2018

A tool which may help fixing this: https://app-manifest.firebaseapp.com/

**Comment by PhilippeAccorsi** [comment]
To use manifest correctly:
Change "start_url": "." by "start_url": "/" => this is working good.

**Comment by PhilippeAccorsi** [comment]
Information about "description" => https://stackoverflow.com/questions/8420730/where-appears-androiddescription-label-from-your-manifest

**Comment by PhilippeAccorsi** [comment]
Some information for manifest:
https://w3c.github.io/manifest/

**Comment by PhilippeAccorsi** [comment]
After some test:

- splash-screen working (background color and icon are the good one) with Chrome and Opera on android phone and tablet.
- splash-screen not working (background color and icon are the good one) with Firefox on android phone and tablet.
- icone and splash-screen not working with Safari on ios 12.2 

- if you click on back in "app" you just return to `http://{tracim_url}/ui` so its normal to have blank page because you don't try to load this url. If you load this url, automatic redirection is make.

- If we want to have information about the possibility of saving Tracim app to dashboard (like a webapp) directly when you arrive in home page, we need to use "workers". Its just possible with firefox to have this message without "workers".

**Comment by PhilippeAccorsi** [comment]
@lebouquetin What do you think about this issue? 
Do we need to work more for tracim 2.1 or we merge this fix and we continu to work for this issue after 2.1 ?

**Comment by PhilippeAccorsi** [comment]
Idea for IOS => https://medium.com/appscope/designing-native-like-progressive-web-apps-for-ios-1b3cdda1d0e8

**Comment by PhilippeAccorsi** [comment]
Verified.
