### ISSUE TITLE
Cant reset password if never logged in

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1359]
Currently: 
- someone created an account for me on tracim
- i receive an email with login and password
- i lost the email
- i go to tracim in order to reset my password
- i get an error saying that auth type is unknown

(which seems logical with the current strategy of logging / managing several authentication backend)

Expected:

- find a way to allow this. When creating an account through admin interface, the authentication type should be "internal", doesn't it ? (in ldap or apache auth cases, the account is created on the fly in tracim, no?)

**Comment by inkhey** [comment]
@lebouquetin When creating an account through admin interface, default type is unknown. Account type is setted to any other value as soon as the user log in first time.

 This allow to create account for other case than internal. If we don't do this you will have trouble if you want to preset right and access for a ldap/apache account before any user log in.

The solution i see to fix this issue was to accept reset password for 'unknown' account. Not sure we should set user to direcly set user to internal in that case or wait for first loggin to fix account type.

**Comment by lebouquetin** [comment]
> @lebouquetin When creating an account through admin interface, default type is unknown. Account type is setted to any other value as soon as the user log in first time.

You mean auth type is unknown, right ? I understand that auth type is identified as soon as the user first log in.

> This allow to create account for other case than internal. If we don't do this you will have trouble if you want to preset right and access for a ldap/apache account before any user log in.

Nice. I understand you take into account advanced use cases, but first, we must address basic use cases. Basic use cases are:

- internal authentication
- auto-activation of an account based on ldap or apache authentication

Then, presets are a good case, but this is the third case in priority.

1. first case must allow user to reset his password (this is not working)
2. second case is when a user has dynamically created his account, he should not be able to reset the password (this is already ok, I think)
3. the presets case is difficult to manage correctly, so we can accept border cases and a "not totally nice fix" (I mean, if there are some drawbacks, its ok.

> The solution i see to fix this issue was to accept reset password for 'unknown' account. 
Good.
> Not sure if we should set user auth type directly to internal or wait for first loggin to fix account type.
I think waiting is better for now. We'll see in the future if something else is better (users will tell us).
>This solution was done in PR #1366 without modification of auth_type.
Ok, lets see

**Comment by tracim** [comment]
@lebouquetin @inkhey 

I have tested this 5 cases:

- [x] Internal auth: create account in tracim => if I'm going directly to reset password email is accepted. (new bdd for this test)
- [x] LDAP auth: connexion in tracim. disconnect and try to reset password => flash message about this kink of auth not permit change password. (new bdd for this test)
- [x] LDAP auth: try to reset password directly without first connection in tracim => flash message about `Unknown email`.(new bdd for this test)

- [ ] LDAP,INTERNAL auth for first connection with `admin` and create account for `user`. Now this user try to reset password => an email is send.
Now I change auth to just LDAP => user try reset password => **email send to this user (but auth is LDAP!!!!!!)**
Now I try connection in tracim, its works (LDAP account) disconnect and try reset password => flash message about this kink of auth not permit change password.

- [ ] Same creation for new user like we have in last point. But now I try to connect with password receive in email. Its just LDAP so its not working `**GOOD**`.
Now I try reset password => email is send to this email. I click on link => url is charge correctly. I try to change password => password is changed with flash message `success`. If I try to connect with this password => its not working.
The problem here is we can show `change password` popup and have a success flash message after type new password, but this password is not available because we use LDAP.

@lebouquetin can you comment to know what is necessary in backend and if this two last case need some more modification for this release 2.1

Thanks.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin @inkhey 

I have tested this 5 cases with new bdd for each case:

- [x] Internal auth: create account in tracim => if I'm going directly to reset password email is accepted.
- [x] LDAP auth: connection in tracim (with ldap account). disconnect and try to reset password => flash message about this kink of auth not permit change password.
- [x] LDAP auth: try to reset password directly without first connection in tracim => flash message about `Unknown email`.

- [ ] LDAP,INTERNAL auth for first connection with `admin` and create account for `user`. Now this user try to reset password => an email is send.
Now I change auth to just LDAP => user try reset password => **email send to this user (but auth is LDAP!!!!!!)**
Now I try connection in tracim, its works (LDAP account) disconnect and try reset password => flash message about this LDAP auth not permit change password.

- [ ] Same creation for new user like we have in last point. But now I try to connect with password receive in email. Its just LDAP so its not working `**GOOD**`.
Now I try reset password => email is send to this email. I click on link => url is charge correctly. I try to change password => password is changed with flash message `success`. If I try to connect with this password => its not working.
The problem here is we can show `change password` popup and have a success flash message after type new password, but this password is not available because we use LDAP.

@lebouquetin can you comment to know what is necessary in backend and if this two last case need some more modification for this release 2.1

Thanks.

**Comment by lebouquetin** [comment]
Last two cases => create issues "to sort" (they are advanced use cases, we'll fix them later.
You can close the current issue after the two new issues created

**Comment by PhilippeAccorsi** [comment]
Verified.
