### ISSUE TITLE
Set user lang through api according to user lang

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1374]
Currently, frontend doesn't set at all lang parameter of user. This should be done in order to allow translation of email generated by backend.

**Comment by inkhey** [comment]
@PhilippeAccorsi we need user lang in backend database to correctly translate email. currently frontend doesn't set lang in user update endpoint.

**Comment by PhilippeAccorsi** [comment]
Ex:

If user as "french" in webbrowser config, all tracim is visible in french. But when user receive an notification email, this email is in english. The reason is: backend is not updated with actual value of language in web interface.

To solved that:
If user does not manually change the language, email notifications will stay in English. In order to get notifications in French, change language to English, then back to French.

**Comment by Skylsmoi** [comment]
The same process is required after login successful in case it's a new user

**Comment by Skylsmoi** [comment]
same process added

**Comment by PhilippeAccorsi** [comment]
Verified.
