### ISSUE TITLE
Update preview generator from v0.9 to v0.10

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1472]
## At present

Tracim use v0.9 of preview-generator.

## Expected

- [ ] preview-generator v0.10 its used by tracim
- [ ] verify if it solved this issue #1126

**Comment by inkhey** [comment]
@PhilippeAccorsi i've made a https://github.com/tracim/tracim/pull/1481 about it.
As we need a new dependencies to make it work, i've update file.
I didn't try yet docker image.
If you test this be careful of this bug : https://github.com/algoo/preview-generator/issues/80
It means that old pdf created bugged preview content will not work directly because preview_generator has stored bad information.

**Comment by PhilippeAccorsi** [comment]
Verified
