### ISSUE TITLE
Its not possible to delete event created by calendar client (exemple with thunderbird)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1533]
## at present

If I try to delete one event in Tracim created with thunderbird I got error 404:

Console error =>
 ```Error: [deleteVcalendarFromCollection: 'DELETE http://192.168.1.150:6543/calendar/workspace/2/2d89ab53-e66f-6a48-634a-f112fb27b5e8.ics']: code: '404' status: 'error'```

Network error =>
 ```
message | /calendar/workspace/2/2d89ab53-e66f-6a48-634a-f112fb27b5e8.ics is not a valid path
-- | --
details | {…}
error_detail | {}
code | null
```

This file exist in tracim/backend/radicale_storage/collection-root/calendar/workspace/

## Expected

- [ ] its possible to telete event if this event is not created with tracim

**Comment by inkhey** [comment]
issue is fixed by #1546.
This happened because caldavzap and thunderbird behaviours are distinct. 
Thunderbird do get/put/delete on calendar root whereas caldavzap do method on subitems. When thunderbird create an items, it create a file like: 2d89ab53-e66f-6a48-634a-f112fb27b5e8.ics, items created with caldavzap are similar but do not contain "-" characters. Currently to avoid most issue we will allow [anything but "/"].ics as subitems file.

**Comment by inkhey** [comment]
New behavior decided is to allow any subpath:

>  /calendar/workspace/2/{anything

**Comment by PhilippeAccorsi** [comment]
Verified.
