### ISSUE TITLE
Some improvements to calendar (agenda)

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1556]
## Feature description

- [x] Rename calendar into agenda in all tracim
  - [x] frontend
  - [x] backend
- [x] set default padding to calendar to match all other pages
- [x] add button fullscreen to agenda
- [x] remove btn "scroll to top" (see https://github.com/tracim/tracim/issues/1554)
- [x] define a color for calendar to set in color.json.sample
- [x] rename title of agenda pages to differentiate all calendar from one workspace's calendar
- [x] add .ics url of own calendar in my account page
- [x] add .ics url of workspace in it's dashboard
- [x] button agenda in header should be have some intelligence (hide when not logged and when calendars are disabled through backend conf (get info from list in app list))
- ~disable btn to edit calendar it user doesn't have enough permissions~ This task has been moved to this issue https://github.com/tracim/tracim/issues/1581

## Context

Some improvements to calendar

## Impacted components
app agenda
app frontend (core)

**Comment by Skylsmoi** [comment]
adding @inkhey and backend tag so that he can include the modifications for renaming agenda in backend in the same branch

**Comment by Skylsmoi** [comment]
set default agenda color to #f63434

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi (after discuss with you) I reopen this issue because I have detected a bug with agenda in my account page.

The problem is when you deactivate radicale in development.ini, when you go in My account page, you can see an error 404 :
"Error while loading your agenda"
`{"message": "/api/v2/users/me/agenda is not a valid path", "details": {"error_detail": {}}, "code": null}`

I think it's because the link is not show in this case but still exist in dom.

**Comment by Skylsmoi** [comment]
account page wont ask api for agenda list if app is deactivated in backend

**Comment by PhilippeAccorsi** [comment]
Verified.
