### ISSUE TITLE
add research in tracim with elastic search

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1667]
## Feature description

Add basic research in tracim

## Context
For the moment its not possible to find content available in tracim.

## Prerequisites

"Unknown"

## Impacted components

- *backend*
- *frontend*

## Extra information

After meeting on 2019/05/03 we have discussed what we need in first time and what we expect for the future:
# 1 : Working search mecanism
- [X] research is optional (can be activated or not in development.ini)
- [X] list of content for research : thread, doc-html, file, folder -> search anything but comment (which are indexed in parent content)
- [X] show last version of content and index also comment
- [X] search with specific characters like "é, ù, ç" etc. -> done with **asciifolding**
- [X] add possibility to use CLI command to drop index and recreate index
- [X] for each new event in timeline, update index -> need more tests. :warning: 
- [ ] Make a documented code for future refactor/improvement
- [X] search with complete word or not: "activ" give result of word "activity"  -> done with query_string and '*' pattern
- [X] result of research use privileges of user to just show what is possible-> filter by user workspace
- [X] result of research are in JSON file with:
    - ~~title~~ -> label
    - ~~breadcrumbs~~ -> list of parents
    - author
    - etc.

# 2 : Extend features
- [X] add possibility to search in file (PDF, odt, etc.)
- [X] simple search mecanism: add search with sql only to avoid need of elasticsearch for some user.
- [X] pagination mecansim
# 3 : Better query
- [X] add possibility to add some filter for research : try using `simple_query_search` instead of query_search ? (in order to have extended filter search mecanism without having to create it fully)
- [X] fix ranking (link to avoid wildcard search) : https://stackoverflow.com/questions/16933800/elasticsearch-how-to-use-multi-match-with-wildcard
- [X] use edge_ngram tokenizer
- [X] Add functional tests for query and indexing.
- [X] :warning:  hack! settable index names and index alias
- [X] sort by content_types, deleted/archived/active
- [X] allow limiting file ingesting to list of mimetype
- [ ] define default allowed mimetype to ingest
- [ ] check about using custom analyzer for ingest content
- [ ] use fuzziness

# Future:

- [ ] check about lang tokenizing ?
- [ ] return search position
- [ ] more tests ? (order, rank ?)

**Comment by buxx** [comment]
There is a [subject](https://stackoverflow.com/questions/6467067/how-to-search-for-a-part-of-a-word-with-elasticsearch) about 

> search with complete word or not: "activ" give result of word "activity"

@lebouquetin it not seems easy/fast to implement. Do we must take more look or not ?

**Comment by buxx** [comment]
> 
> 
> There is a [subject](https://stackoverflow.com/questions/6467067/how-to-search-for-a-part-of-a-word-with-elasticsearch) about
> 
> > search with complete word or not: "activ" give result of word "activity"
> 
> @lebouquetin it not seems easy/fast to implement. Do we must take more look or not ?

But seems easly to search as [prefix](https://stackoverflow.com/a/37731294/801924)

**Comment by inkhey** [comment]
Some issues to discuss:
- config parameters in entry to setup elasticsearch: should we allow multiple elasticsearch server ? and if yes, how (https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch allow multiple value in hosts but i do not understand the mecanism behind). It may interesting to solve partially this issue in order to not have refactoring config parameter name later.
- What should we return, should we return list of Content object (which mean call database for this and performances issue), or something different.
- How should we limit the result to allowed content ? Easiest way is actually to limit research to user workspace content, that's easy but that's mean a call to database too in order to retrieve user workspace.

**Comment by inkhey** [comment]
Some others information about https://github.com/tracim/tracim/pull/1717:
- Index "updating" mecanism with open/close is still unclear for me.
- Auto-index mecanism is done by other method to call after content update/creation that's not really nice (we need to not forgot put the method in many place but that's the current way to deal with it on workspace and user), I propose to keep it like this because putting this into method itself is tricky and mean big refactoring. see https://github.com/tracim/tracim/issues/1589
- I use elasticsearch dsl to make query, it permit also to have some kind of sqlalchemy object which are really nice. Reason for using it instead of raw query is that conditional query in raw elasticsearch are really messy, and we need it to filter query.

**Comment by inkhey** [comment]
ElasticSearch configuration is a bit tricky when we try to go deeper.

I've few trouble:
- Activating ranking, currently ranking is always to 1 due to fact we use query_string for query, that may take time to understand this (documentation is complex)
- special character search do work only in one way  searching `écho` find  `echo` but `échoe` does not find  `echo`
- How should we index comments ?
- Search for incomplete word, work currently with "*" pattern but only at end of the search string. Not sure that what we want.

**Comment by inkhey** [comment]
Other problem:
- Indexing html : with é -> &eacute;  search doesn't work on raw html, we should apply some kind of processing when we put html into the system

**Comment by inkhey** [comment]
#1717 include now:
- Better command to create/delete index
- Better indexing with comments, parent, author, etc...
- Search into comment content too
- Better handling of html field (html_folding analyze)

**Comment by inkhey** [comment]
@PhilippeAccorsi la variable d'environnement pour l'index c'est:
`TRACIM_SEARCH__ELASTICSEARCH__INDEX_ALIAS`

le code est censé planté et de dire pourquoi si tu lance la recherche elasticsearch sans ça.

**Comment by PhilippeAccorsi** [comment]
Update:
This variable is now in development.ini (see https://github.com/tracim/tracim/issues/1835).

**Comment by PhilippeAccorsi** [comment]
Tested with: docx, odt, pdf (search word inside file)
Need improvement for the futur but its working good.
Verified.
