### ISSUE TITLE
webdav not working with MacOS (v10.14.4)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1734]
## Bug description & symptom

When we try to move some file with Webdav and finder, one file ._*** is created for each file (we think is temporary file) and one file is created with normal name. But no data is written. So this two file are empty and file ._*** is not deleted.

After this try, its not possible to reconnect with webdav. Thats also not working with linux.

## Diagnostic

*"unknown"*

## Expected

- [ ] it should be possible to upload files with finder in macos
- [ ] upload file with finder not create temporary file **or** this file is not detected like a good file by tracim to make sure no notification is send. *note de damien: we should probably consider ._xxx as temporary files like we do for windows and do not store them (i think this is what we do currently)*

## Context and version information

- Desktop environment 
    - *OS: MacOs 10.14.4*
    - *Soft: finder*

## Prerequisites

*"unknown"*

## How to reproduce

- Open finder
- try to move file with webdav

## Impacted components

- *backend*
- *webdav*

**Comment by inkhey** [comment]
Bug cannot be reproduce with waitress 1.1.0, but happened with uWSGI 2.0.14-debian

**Comment by lebouquetin** [comment]
@inkhey please test with latest uwsgi version (2.0.18)

**Comment by inkhey** [comment]
Latest version of uwsgi(2.0.18) doesn't work.

After some research, i found that problem is link to the fact we send this header:
`Transfer-Encoding`: chunked and no `Content-Length` .
https://en.wikipedia.org/wiki/Chunked_transfer_encoding

Uwsgi is not able to support this kind of chunked transfer encoding.

There is a discussion about a feature about a flag `--wsgi-manage-chunked-input` which **may** solve the issue : https://github.com/unbit/uwsgi/issues/1428 but this feature doesn't exist yet in last version of uwsgi.

Waitress server which work doesn't really use chunk for security reason, as found here:
https://github.com/Pylons/waitress/issues/179 and https://github.com/Pylons/waitress/pull/203 . In fact it convert chunked file into normal one with buffering, and set Content-Length header.

One idea to verify behavior in chunked context (which doesn't happened in waitress case), may be testing with cheroot, which is the server used by wsgidav sample.

Another way to fix this issue is by using same mecanism as waitress in webserver proxy.
for `mod_proxy_http` of apache , https://httpd.apache.org/docs/trunk/mod/mod_proxy_http.html 
we can use:
`SetEnv proxy-sendcl`
Tested and this is working.

**Comment by lebouquetin** [comment]
If I understand correctly, we are able to make webdav work with only apache configuration upgrade. So we must do this configuration.

By the way, I do not understand: webdav is based on cheroot (and webdav is directly served, it does not go through tracimweb, am i wrong?)

**Comment by inkhey** [comment]
> By the way, I do not understand: webdav is based on cheroot (and webdav is directly served, it does not go through tracimweb, am i wrong?)

You're wrong, in tracimv2, webdav is a wsgi app like tracimweb. it can be run with different wsgi server like cheroot, uwsgi, waitress, ....
We currently use the same uwsgi server for all wsgi app in debug : waitress, and the same for production: uwsgi.

**Comment by inkhey** [comment]
@lebouquetin @PhilippeAccorsi fix with apache config for upload with macosx is available in #1842 , i suggest to create another issue for more complex fixing behavior with macosx : temporary file, etc.. which is not a trivial fix.

**Comment by PhilippeAccorsi** [comment]
We have fix webdav with macosx when tracim running with docker. This fix just change one parameter in apache2 conf to make sure copy file is working.

This issue #1885  is created to find solution for other problem and to find solution when you use tracim with uwsgi but without proxy (apache).

**Comment by PhilippeAccorsi** [comment]
Verified.
