### ISSUE TITLE
Workspace management: update rights

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#177]
Currently, when an user has "Create Workspace" right, he can manage all workspaces where he has a role. So he can manage workspaces without workspace manager role.

TODO:
A user with "create workspace" right 
- must be allowed to manage workspaces he created
- must be set as "workspace manager" of all workspaces he created
- can't change his own role on workspace he created

**Comment by algooapy** [comment]
## Functional situation summary as experienced in the browser ##

### Todo related status ###

The three tasks from the `TODO` above behave as expected.

### Role related status ###

When a user has the `Create Workspace` right, the operations he _**is**_ allowed, or not, to perform depend on his role in each workspace:
- `Reader`
  - can't add users
  - can remove users (workspace manager included)
  - can edit other users role
- `Contributor`
  - can add users
  - can remove users (workspace manager included)
  - can edit other users role
- `Content Manager`
  - can add users
  - can remove users (workspace manager included)
  - can edit other users role
- `Workspace Manager`
  - can add users
  - can remove users (workspace manager included)
  - can edit other users role

## Is this the expected behavior ? ##

When a user has the `Create Workspace` right, the operations he _**should be**_ allowed, or not, to perform depend on his role in each workspace:
- `Reader`
  - can't add user
  - can't remove user
  - can't edit other users role
- `Contributor`
  - can't add user
  - can't remove user
  - can't edit other users role
- `Content Manager`
  - can't add user
  - can't remove user
  - can't edit other users role
- `Workspace Manager`
  - can add user
  - can remove user
  - can edit other users role

**Comment by tracim** [comment]
There are two ways of managing rights on tracim :

- user profile (super admin, «user can create workspace», normal user)
- user role in workspace (reader , contributor, content manager, workspace manager).

The rights you defined in your comments are right for a normal user.

The «user can create workspace» is actually an admin. The differences with the super admin are :

- a superadmin can disable a user (so he wont be able to login)
- a superadmin can see all workspaces, even ones he has no role in.

Do you see the differences between «roles» and «profiles» ? Roles are related to a given workspace and have no meaning outside of this context, profiles are context-free and are more global

**Comment by tracim** [comment]
So, if a user has «create workspace» right, he can manage workspaces where he is member but he cant even see other workspaces.

This bug is currently about workspaces the user shouldnt see.

For example, if you have «can create workspace» right, you should be able to create and manage workspaces about technical stuff, but you are not a superadmin because you must not be able to access workspaces related to business/management/money/salary, etc.

Currently, i cant give you right to create workspaces because you would get access to information you shouldnt.

**Comment by algooapy** [comment]
- "Do you see the differences between «roles» and «profiles» ?"
Yep, I understood that well. I must admit my above comment lacks proper "relative to the given workspace" notion. I edited it to take this into account.

The tests I conducted lead to the following rule: A user who «can create workspace» cannot see workspaces if he has no role in them.

**Comment by tracim** [comment]
I re-tested and you are totally right. There us still an improvment to do. In /admin/users/<id> the «can create workspace » user can see all workspaces the user is subscribed to, but cant do anything. My feeling is these workspaces should not appear here... but its another issue, not urgent.

Can you close the current issue and open a new one ? Thanks

**Comment by xandercagexxx** [comment]
verified.
