### ISSUE TITLE
Rename restored content with same name that other content is possible in special case, we can also rename sharedspace with name of another sharedspace

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1770]
## Bug description & symptom

*We can have two files with the same name if we delete the file and it rename with the same name that other already existent.*

## Expected

*Message "A content with the same name already exists" when we try this.*

## How to reproduce

1. *Create a content of type X with the name Y*
2. *Validate and create*
3. *Create an other content of type X with the name Z*
4. *Delete and restore the content Z*
5. *Rename the content Z to Y*

## Screenshots

![Peek 2019-05-21 11-01](https://user-images.githubusercontent.com/35422692/58083003-6cbc7600-7bb8-11e9-8b06-7f94e8da57d5.gif)

**Comment by gbonaspetti** [comment]
The same thing happens when we archive and restore the file.

**Comment by gbonaspetti** [comment]
And a similar thing happens to shared spaces. We can't create shared spaces with the same name, but we can rename for the same name that other shared space.
![Peek 2019-05-21 11-26](https://user-images.githubusercontent.com/35422692/58084936-15200980-7bbc-11e9-80ae-d4d8d8efd729.gif)

**Comment by inkhey** [comment]
Rapid check about the meaning of these issue:
- bug with content naming is an extension issue -> it create file.html instead of file.thread.html after deletion/archive.
- bug with workspace renaming is easy to fix, it just a not handled case.

**Comment by celiamgtt** [comment]
Bug still existing for all contents (except workspaces)

![Capture d'écran de 2019-06-17 15-19-17](https://user-images.githubusercontent.com/50453784/59607455-a75ff280-9113-11e9-859a-bdb7cadf6c32.png)

**Comment by inkhey** [comment]
@celiamgtt as discovered, problem happened because when deleting content `.thread.html`
 and `.document.html` is converted to `.html` because we change throught 
`.file_name` instead of setting only .label.

@lebouquetin 
I see two solution to fix this:
- set only label at deletion and archiving (and do not remove file_name check but don't rely on it in order to no split incorrectly label/file_extension)
- tested in https://github.com/tracim/tracim/tree/fix/1770_better_handling_of_double_file_extensions : support some double_file_extension and set always label using file_name. This allow to repair easily copy issue by copy content.document.html throught webdav as  content.document (copy).html  which renamed to content `content2.document.html` or `content2.document` in web ui has file_extension correctly setted again.

**Comment by inkhey** [comment]
after discussion current fix decided is 1 : 

> set only label at deletion and archiving (and do not remove file_name check but don't rely on it in order to no split incorrectly label/file_extension)

**Comment by inkhey** [comment]
for more deep discussion about filename and related issue : https://github.com/tracim/tracim/issues/1952

**Comment by celiamgtt** [comment]
Verified
