### ISSUE TITLE
Indicate in changelog how to enable calendar

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1819]
## Feature description

Add information in changelog about how to enable calendar. Add information for docker mlage user and source code users.

## Context

When using an running 2.1 Tracim and migrate to 2.2 calendar is not enabled by default. Indicate in changelog (with link to documentation) how to enable it.

**Comment by PhilippeAccorsi** [comment]
In tracim 2.3, agenda is activated by default.
We need to find where we can add information about starting agenda if user switch from 2.1 to 2.2. Some documentation exist here [start agenda](https://github.com/tracim/tracim/blob/release_02.02.00/tools_docker/README.md)

**Comment by PhilippeAccorsi** [comment]
I have updated release description.
~~~
Agenda (add "-e START_CALDAV=1" if you start docker image. Documentation here)
Migration of agenda from tracim v1 to tracim v2 is now available. Documentation here
~~~

Thats enought because new release arrive soon and with new release CALDAV is started by default with docker image.
