### ISSUE TITLE
its possible to open new tab whis shortcut on all header button

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1845]
## Bug description & symptom

It's possible to open new tab if I click on Administration and after that if I ctrl+click, (or other shortcut) on user or shared space.
But its not possible to open agenda in new tab because this button not have choice inside.

## Diagnostic

"unknown"

## Expected

- [ ] Its possible to open new tab for all clickable button on tracim.

## Impacted components

- *frontend*

**Comment by celiamgtt** [comment]
Open sometimes a blank page on ctrl+click or middle click

**Comment by basilelegal** [comment]
@Skylsmoi 
![Screenshot at 2019-06-17 09-54-24](https://user-images.githubusercontent.com/7879232/59610849-38b96f80-90e8-11e9-91ab-bc31420a3d63.png)
![Screenshot at 2019-06-17 09-54-37](https://user-images.githubusercontent.com/7879232/59610853-39ea9c80-90e8-11e9-943b-9b07d0b53418.png)

**Comment by Skylsmoi** [comment]
This happens every time but only on first page load with an url that opens the app agenda:
- /ui/agenda
- /ui/workspaces/:id/agenda

**Comment by Skylsmoi** [comment]
The same crash appears when loading app admin workspace user on first load.
Which coherent, issue seems to come from app fullscreen

**Comment by Skylsmoi** [comment]
### investigation
Problem is nothing but a race condition in scripts loading orders.
- Apps need frontend core to be loader or they crash with "generator.runtime" in undefined
- appInterface need to be loaded after apps
- frontend core need to be loaded last to be sure everything exists when it runs

So frontend need to be loaded either first AND last.

Why does it work then ?

Because apps feature are run always later because frontend needs to wait for some more async calls run by `<WorkspaceContent />`. 
So while frontend waits for api to respond, the browser have time to load everything.

Apps fullscreen are run earlier because frontend doesn't needs to wait for as much API to respond. And browser usually doesn't have enough time to load every scripts. Therefore, the crash.

### possible solution

#### 1
apps includes generator.runtime (from babel) and can be loaded without frontend core.
frontend core is loaded last
**pros**: it works
**cons**:
- it requires some research to implement properly
- will increase the size of all apps
- frontend will be run last and after every apps. So the browser will take much more time to displays something on the screen

#### 1(alt)
it also might be possible to put the generator.runtime in the vendor script to avoid duplicate it in every apps. I'm not sure.

#### 2
find a way to force frontend to wait for all apps to be loaded by the browser before trying to open one
**pros**: it works
**cons**: I don't know how right now. One possible way is to use global variables that get set by apps and frontend needs to wait for theses global variables to be set. It's not great and will add some non intuitive behavior

**Comment by Skylsmoi** [comment]
solution given is to try catch the missing variable and to retry after a few ms if get into the catch

**Comment by celiamgtt** [comment]
Verified
