### ISSUE TITLE
one user account is added to tracim but his own calendar is not created

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1852]
## Bug description & symptom

When we add new user in tracim (2.2), agenda of this new user is not created but link is visible in user account.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] all calendar is correctly created when user is added in tracim

## How to reproduce

- Add one user in tracim
- go to `radicale_storage/collection-root/agenda/user` and verify if new folder is created

## Impacted components

*"unknown"*

**Comment by PhilippeAccorsi** [comment]
In this instance of tracim, agenda exist since tracim v1. We have make migration of calendar before see this bug.

**Comment by inkhey** [comment]
Log issue when reproducing error using `.Radicales.props` in /user/ .

Tracim web side (trying to create agenda for user)
```
16:17:10 ERROR [tracim:41][waitress] [UserApi] Agenda http://localhost:5232/agenda/user/2/ cannot be created:403,b'Action on the requested resource refused.'
Traceback (most recent call last):
  File "/home/user/Public/tracim/backend/tracim_backend/lib/core/user.py", line 852, in execute_updated_user_actions
    agenda_api.ensure_user_agenda_exists(user)
  File "/home/user/Public/tracim/backend/tracim_backend/lib/agenda/agenda.py", line 163, in ensure_user_agenda_exists
    agenda_url=user_agenda_url, agenda_name=user.display_name, agenda_description=""
  File "/home/user/Public/tracim/backend/tracim_backend/lib/agenda/agenda.py", line 84, in _create_agenda
    agenda_url, response.status_code, response.content
```

Radicale side:
```
16:16:31 INFO  [radicale:409][waitress] GET request for '/agenda/user/2/' received from ::1 using 'python-requests/2.21.0'
16:16:31 INFO  [radicale:387][waitress] GET response status for '/agenda/user/2/' in 0.014 seconds: 404 Not Found
16:16:31 INFO  [radicale:409][waitress] MKCOL request for '/agenda/user/2/' received from ::1 using 'python-requests/2.21.0'
16:17:10 INFO  [radicale:387][waitress] MKCOL response status for '/agenda/user/2/' in 38.112 seconds: 403 Forbidden
```

issue happened with on line 712 of `radicale.__init__.py `(radicale 2.1.11)
https://github.com/Kozea/Radicale/blob/8387a4c33f650d4392d6085750000f27ee51f278/radicale/__init__.py#L712
```
            if (not isinstance(parent_item, storage.BaseCollection) or
                    parent_item.get_meta("tag")):
                return FORBIDDEN
```

The fact is that `parent_item.get_meta("tag")` return true and error is raised.

That's because tag exist in `/user/ `/props, here content of `/user/.Radicale.props` :

`
{"ICAL:calendar-color": "#26098a", "tag": "VCALENDAR"}
`

Idea is that radicale doesn't want to create calendar into another calendar, so as we have weird information saying that /user/ dir is a calendar (which is uncorrect) it doesn't want to create calendar into it.

Part of the problem is why do we have such meaningless information as production data. Data from v1 are incorrect too but mechanism is different so similar issue can not happened.

**Comment by PhilippeAccorsi** [comment]
@PhilippeAccorsi check if its ok on all production instance first. If its ok, this issue is verified.

**Comment by PhilippeAccorsi** [comment]
Verified.
