### ISSUE TITLE
We never find anything when we search for a & 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1923]
## Bug description & symptom

When we search for a & we never find any results, even if there is.

## How to reproduce

1. Create a content of any type named *toto&*
2. Search for &

## Screenshots

![search](https://user-images.githubusercontent.com/35422692/59586681-c3e43680-90e3-11e9-9fac-468caaf8d7b3.gif)

**Comment by inkhey** [comment]
@gbonaspetti are you using simple search or elasticsearch search ?

Not sure the reason of the issue but as simple search does search directly with content stored in database, that's mean it doesn't handle properly some case.

**Comment by gbonaspetti** [comment]
@inkhey simple

**Comment by inkhey** [comment]
issue is frontend related:
`http://localhost:6543/api/v2/search/content?show_archived=0&content_types=html-document,file,thread,folder,comment&show_deleted=0&show_active=1&search_string=&&page_nb=1&size=10`
call is uncorrect as it handle & not as & character but as "set another query parameter" 

characters passed through query parameters should always be urlencoded, at any place of tracim in order to not have any similar trouble.

for exemple:
& should be transform to %26%0A in url.

**Comment by lebouquetin** [comment]
The right way to fix this is to url-encode every url parameter

**Comment by Skylsmoi** [comment]
We will only fix the search string with url-encode for 2.3
The rest of the refactor will be done after

**Comment by inkhey** [comment]
Verified.
