### ISSUE TITLE
add token in code to make sure you have last code when new version of tracim is available.

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2010]
## Feature description

Add something to make sure, web browser download new version of tracim when new version is available.

## Context

 At present we need to refresh cache of browser manually. If we had specific token with very long persistence, we can change token version on each new version of tracim and in this case, the frontend refresh cache automatically.

## Impacted components

*"unknown"*

## Extra information

This is also necessary for progressive web app to make sure this app used the last version of tracim.

**Comment by buxx** [comment]
I think we need to add a token in css/js files urls, like:  `/main.js?{version}` . This token should be generated at build, based on tracim version. Tracim version must be stored in repository (this can be last commit number for example).

**Comment by inkhey** [comment]
This may be related to https://github.com/tracim/tracim/issues/1484, as we need a way to get tracim version. setuptool-scm offer a way to get it.

**Comment by inkhey** [comment]
Discussion with @PhilippeAccorsi, lead to fixing tracim backend package version ( see #2619). 

setuptool-scm cannot be used properly as new release are accessible only in master branch (we will get tracim 2.4... version.

**Proposal:**

- We add a new "build_version" parameter in tracim config. 
- If it is not setted, the default value should be something we can checkout to (git checkout {build_value) should work).
- if current commit has a tag associated, we use it instead of hash. we do need to find a solution for multiple tag per commit case.
- if git is not installed or where are not in a git repository, and config parameter not setted we do need a default value like "{tracim_backend_python_package_version}-unknown".
- this "build_version" parameter should be overriden with parameter in docker process (we do remove git in this process)

**Comment by inkhey** [comment]
i've made a poc: https://github.com/tracim/tracim/compare/fix/1484__consistent_python_version_using_setup_cfg_for_metadata...feature/2010__add_build_version_parameter_as_token_for_frontend_served_file (need #2619 )

**Comment by inkhey** [comment]
@PhilippeAccorsi For Docker support of build_version, you need to :
1. have git installed
2. get build_version with `tracimcli dev parameters value -n -r "build_version"`
3. then set env var TRACIM_BUILD_VERSION
4. uninstall git

**Comment by inkhey** [comment]
"Unknown build" alternative naming:
1. "unknown-default-value"
2.  "unset"
3. "undefined-and-unset"

**Comment by lebouquetin** [comment]
@inkhey could you give examples of what it would be like ?

**Comment by inkhey** [comment]
modifications after discussion with @lebouquetin : 
- add cache token for all assets
- separate build_version from cache_token, cache_token use git hash or autogenerated uuid but stay overridable like any tracim configuration parameter.

**Comment by inkhey** [comment]
after discussion with @lebouquetin, "unknown" as defautl buid_version is ok.

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi For Docker support of build_version, you need to :
>     1. have git installed
>     2. get build_version with `tracimcli dev parameters value -r -n "build_version"`
>     3. get frontend cache token with `tracimcli dev parameters value -r -n "frontend.cache_token"`
>     4. then set env var TRACIM_BUILD_VERSION
>     5. then set env var TRACIM_FRONTEND__CACHE_TOKEN
>     6. uninstall git

Finaly, better solution with docker for the moment is to not uninstall git at end of docker build. If we uninstall git, we need to find another way to use tracimcli command, tracim config file not exist in docker build process and some other problem appear like:
- how to set default env variable and this env variable can be overright by docker-compose env variable.
- how to use variable in config file if env variable also exist (env variable is set by docker build, but config file can be changed after that)

**Comment by PhilippeAccorsi** [comment]
Tested on branch and with new docker image.
Verified.
