### ISSUE TITLE
Author of a content is not the original author but the last modifier

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#202]
Currently : 
if a userA creates a content (page, file or thread), he/she is the author and appears as author.
if a userB modifies the content, then the author shown is userB instead of userA.
This is due to the fact that the author is taken from the last revision of the content, which embeds all information.

Expected :
Author should be taken from the first (historically) revision of the content.

**Comment by tracim** [comment]
Check that this code has been merged, if not : merge it

**Comment by algooapy** [comment]
* Code merged : see #205
* Expected result checked : the author is the first to create the content even if someone else edit his/her content

**Comment by lebouquetin** [comment]
The bug seems not to be fixed - it looks like author and last modifier are inverted - example on http://algoo.trac.im/workspaces/30/folders/4098/pages/4238

This is also the case with the file previewer built with react - example : http://algoo.trac.im/workspaces/30/folders/2071/files/3497

@algooapy please fix this for the template part then attribute the bug to @Skylsmoi

**Comment by algooapy** [comment]
I checked this issue anew; `Tracim`, from up to date master branch, behaves as expected.
Is this an issue specific to `algoo.trac.im` instance, maybe about templates cache refresh?

**Comment by tracim** [comment]
Could you have a look at the production with @bux in order to validate this hypothesis ? (And purge the production cache if required)

**Comment by algooapy** [comment]
We just finished looking at it :)
- Old contents, created before this issue was solved, are corrupted,
- new contents are sane.

**Comment by lebouquetin** [comment]
I can imagine author is corrupted for old contents (because they were stored with wrong information). I added at the moment a minor upgrade to http://algoo.trac.im/workspaces/30/folders/4098/pages/4238. So, last modification is mine, done after the upgrade of the code. The last modification which appears is still an old revision.

By the way, the revisions list is right, I do not understand how old contents may be corrupted. I need a fix or a technical explanation.

**Comment by lebouquetin** [comment]
for information, the last revision is this one: http://algoo.trac.im/workspaces/30/folders/4098/pages/4238?revision_id=9812

**Comment by buxx** [comment]
If need investigations, i suggest replicate prod database on dev machine and inspect.

**Comment by lebouquetin** [comment]
Reminder of what is expected: 

- author and creation date must be taken from the author and creation date of the first revision of a content
- last modifier and last modification date must be taken from author and creation date of the last revision of a content.

This behavior should probably be implemented in class Content (from tracim.models.data). There are getter/setter for both author, creation and modification datetimes, which may conflict with current expectations.

@algooapy get a dump from production and work with it for local investigations as suggested by @buxx

**Comment by tracim** [comment]
I did look at the code of the model, which is probably ambigus and same code used for two different goals... lets discuss about it on monday

**Comment by algooapy** [comment]
Closing this issue because:
- the original bug is fixed,
- the bug mentioned lately in this discussion is new and now has its own issue #335.

**Comment by xandercagexxx** [comment]
Verified.
