### ISSUE TITLE
Preview (frame) of video available in tracim and add player to see video directly

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2103]
See also https://github.com/tracim/tracim/issues/1462 for the backend.

Changelog: app file can now play mp4 and webm video format with a new "play video" button

## Feature description

Currently, it is possible to preview of video file by walking through 10 extracted frames.
Users expect to be able to play the video directly from the tracim user interface.

## Context

When sharing a video, according to the usecase you may want to play it online or just to share it.

My point of view is we should allow both to walk through the video and to play it.

## Prerequisites

N/A

## Impacted components

- *backend*
- *frontend*

**Comment by inkhey** [comment]
#### For preview of video with frame: 
 it should be done in  preview_generator. 
Problem is that we should decide how we generate these frame. 
I do think we should divide video into the number of frame we want (which should be configurable) in order to have frame from different part of the video.
We want probably have a similar result as for multipage file but i do think we should find a way to make this not too much meaningless, frame are not page.
We should also think about limitation here as we should not process to big video.

#### For direct video view:

This is easier.
This can already been done directly by frontend. We should maybe return to frontend information about if it is viewable as video according to mimetype/size but frontend is already able to get the video and show it.

**Comment by YannickBiet** [comment]
@PhilippeAccorsi the need of the feature has become redundant for the last two leads I have asking to put multimedia files (audio and or video) in Tracim and be able to read it via the cloud (streaming)

Would be great to add a basic video player controls and frame in Tracim (we need to check which video formats you can easily stream : mkv, av1, heiv, mp4, mov, ...)

The same for audio : WAV, FLAC, AAC, MP3 ?

**Comment by YannickBiet** [comment]
I am unsure about the direct video view answer as it might prevent the user to see the comments associated with the file (within the file history)

ideally i would replace the images previewing system by a streaming player. User would have the possibility to switch full screen thanks to a icon within the player (like Youtube do)

**Comment by lebouquetin** [comment]
> ideally i would replace the images previewing system by a streaming player. User would have the possibility to switch full screen thanks to a icon within the player (like Youtube do)

Framing a video has an interest: allow to walk through the video without downloading large amount of data. I'm not convinced that frames must be straight away replaced by a player. I agree we need to include a button in order to play the video online.

**Comment by lebouquetin** [comment]
By the way, a point to check is we allow to stream video file. It requires probably HTTP Range to be implemented - see #1462

**Comment by lebouquetin** [comment]
@inkhey could you evaluate the workload for allowing online video play?
@Skylsmoi could you evaluate the workload for including a button to play the video (or a complete player inserted on click)?

These evaluations should be done in two implementation ways: "quick and dirty" and "state of the art".

Thanks

**Comment by inkhey** [comment]
After some checks:
1. video can be seen from browser without need of http range, but this mean load the all video. We clearly need to support http range if we do want to support more use case.
2. Browser do support just a subset of video and audio format: https://en.wikipedia.org/wiki/HTML5_video#Browser%20support , https://en.wikipedia.org/wiki/HTML5_audio#Supported%20audio%20coding%20formats

So in backend, it seems that http range is enough: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests. Supporting it should be done at hapic layer and require some change. support for pyramid framework only in hapic, seems not really complicated.

**Comment by lebouquetin** [comment]
@inkhey thanks for the investigation. Do you think there are more than a few days of work for the HTTP Range support?

**Comment by inkhey** [comment]
> @inkhey thanks for the investigation. Do you think there are more than a few days (1 to 4 days) of work for the HTTP Range support?

I think so.

**Comment by inkhey** [comment]
Probably unneeded here, but i found this interesting article about HLS:
https://medium.com/canal-tech/how-video-streaming-works-on-the-web-an-introduction-7919739f7e1
So, in case, we later need a more complex mechanism, it seems no too difficult to implement.

**Comment by lebouquetin** [comment]
@inkhey managing HLS playlists is probably not the job of tracim... maybe a way to implement embedded video player would be to dispatch video to a peertube backend and allow streaming from it.

**Comment by inkhey** [comment]
Just read the RFC : https://tools.ietf.org/html/rfc7233
Some remark:
- we should not support **other range units**.
- we should return Accept-Ranges: bytes on get.
- if we can't process the range, we could return 200 with full content instead of 416, it's easier.
- support for "bytes=500-700,601-999" type (multiple part range) of range seems too much complex.  We should avoid to support it in a first time and trying to add it only if we see a clear usage in browser (don't think so).
- Support for IF range can be done, related to date (if unmodified) or etag (if match), it's not required, but it can be useful.
- More globally, we can support Etag mecanism (if range but not only) for content download, this allow to improve behavior when updating content or when getting content (don't recache same content). The requirement is we need of having unique name for content, we can use filedepot or revision id for this as there are unique for one revision (don't think we do need to have some hash from the full content). Anyway as we do have date in revision, we can also use date for this kind of mechanism. Limitation is client support. This is also a good step if we decide to support some kind of "sync client".

**Comment by Skylsmoi** [comment]
@lebouquetin workload for frontend
The 2 possibilities I have checked are:
1) Use the html tag `<video>`
2) Use [videojs](https://videojs.com/)
___
1)
- is easier and simpler
- its features will be enough for a first version but we might get blocked for future features (video tag doesn't handle adaptive streaming for example)
- its design is different on different browsers
  - but it can be styled manually

2)
- free and open source
- mature project, last release about 2month ago
- used by 400 000 websites
- more complex but more powerful
  - but seems easy to integrate as a POC

___

For a "quick and dirty" integration, I would say about 2 to 4 hours for each possibilities (2 longer than 1)

For a "state of the art" integration, I would recommend doing some refactor in the app File, especially on the `<PreviewComponent />` since it currently only handles images.
So 2 to 3 days seems fair.

These estimations assumes that the backend is ready and handle everything it needs. Like video sources at the proper format and well encoded, handles the streaming and allow the seeks and some other things that I don't know about.

Side note: MDN has a great encoding guide. See [https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs)
It also have a lot a documentation about playing video in a browser

**Comment by lebouquetin** [comment]
@Skylsmoi what video file types are supported with `videojs` and `<video>` tag ?

**Comment by Skylsmoi** [comment]
videojs uses a `<video>` tag so they basically have the same supported file types. Or codecs.
You have a list [here](https://en.wikipedia.org/wiki/HTML5_video#Browser_support)
And a more detailed one [here](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs)

**Comment by YannickBiet** [comment]
@lebouquetin do we have an ETA for this feature ? just to know if it is on the rails as still labeled as "to sort"

TY

**Comment by Skylsmoi** [comment]
A first version have been implemented to play video from app File.

It lacks a few architecture improvements and it has a design flaw where the header of Tracim is still visible when opening the player.

It stands as a v0, we will improve what is required

**Comment by Skylsmoi** [comment]
> It lacks a few architecture improvements and it has a design flaw where the header of Tracim is still visible when opening the player.

about the visible header, it's because its z-index is 30 while the apps are in a container which z-index is 20.
And a tag can't have a z-index higher than one of its parents.

The solution is to create a process that will insert the player htlm tags directly into the DOM instead of letting react handling it. That way, we will can put it anywhere we want, out of a container with a fixed z-index (it will most likely be inserted right before the `</body>` tag)

**Comment by Skylsmoi** [comment]
I have changed the app file so that it now recreate a `<video>` tag entirely.
This fixes the issue where switch file content didn't change the video played by the player.

It will also allow to fix the z-index issue more easily

But I had to break the fadeIn animation of the player and it's background when opening

**Comment by PhilippeAccorsi** [comment]
Last commit permit to show all video mime type (video/*) and add possibility to add some mime type in a blacklist. Test need to be done on `maintenance/2.7` branch directly.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I do not understand the Z-index issue because some buttons are hidden and some are visible, timeline information is not visible but comments are.

![Screenshot_2020-06-12 file_example_MP4_1920_18MG · test vid · sandbox · Tracim(1)](https://user-images.githubusercontent.com/25848257/84494573-0ebe6d00-acaa-11ea-8661-91e4f683409e.png)

Visible in shared page (cancel button is hidden and validate button is visible):

![Screenshot_2020-06-12 file_example_MP4_1920_18MG · test vid · sandbox · Tracim](https://user-images.githubusercontent.com/25848257/84494662-344b7680-acaa-11ea-85e5-b26094c155f6.png)

Can you see why ?

**Comment by Skylsmoi** [comment]
I have just looked more deeply into it and it's actually a bit confusing.
For the button it appears it the property `opacity` that make it visible. But for the comment I could find what is making it visible over the overlay.

I have a solution though, currently, I'm inserting the video player and the overlay inside the app file. The proper solution would be to insert it right before the `</body>` tag.
This solves the "z-index" issue. (it's actually not a z-index issue but it's easier to understand that way)

I have tested this solution using dev tools and it seems to work.

Should I commit it asap ?

**Comment by PhilippeAccorsi** [comment]
You can commit your fix.
Need also a fix to show error with warning visible in console when video format is not supported by web browser. Message like this:
`This video format is not supported by this browser. Please download the video to play it locally.`

This message need to be translated in French and Portugues (if possible).

**Comment by Skylsmoi** [comment]
I have added a message to tell the user if the browser knows that it might not be able to read the video

I have also fixed the z-index issue

**Comment by PhilippeAccorsi** [comment]
Tested and verified in branch maintenance/2.7.
