### ISSUE TITLE
Search result isn't linked with a document when its parent folder has been moved

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2114]
## Bug description & symptom

Search result isn't linked with the document when its parent folder has been moved from one sharedspace to another. When we're clicking on the result, the app opens but nothing is displayed.

## Expected

Search result should display the correct link (and display the document when we're clicking on it).

## Context and version information

- Firefox 60.8.0esr (64 bits)
- Algoo Tracim Instance

## Screenshots

Here, I moved "MAJ Site Web" parent folder from the sharedspace "Tracim" to the sharedspace "Communication".

![bug_search](https://user-images.githubusercontent.com/50453784/61644239-9cfdbf00-aca4-11e9-806d-80ee53908c76.gif)

## Impacted components

- backend
- frontend

**Comment by lebouquetin** [comment]
C'est à mettre dans les nice to have de la 2.4

**Comment by PhilippeAccorsi** [comment]
Done.

**Comment by inkhey** [comment]
as explain in #1833, Problem is related to technical debt ticket #1589 and #1487 . We currently do need to explicitly launch post action in code instead of relying on lib itself. This is not done for both moving and copying cases. 

#1833 is more about the performance issue of updating all children when we update a content.

**Comment by grignards** [comment]
Corrected with #4146.

**Comment by Skylsmoi** [comment]
as seen with @grignards , the fix is already on develop so it's ready to be tested

**Comment by PhilippeAccorsi** [comment]
Done.
