### ISSUE TITLE
A reader can edit a file using collaborative edition

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2160]
## Bug description & symptom

The user interface show a button edit to a reader and a reader can access to the dition iframe if he knows the url - even if he can't save.

## Expected

The button should be hidden in the `file` popin.
A flash message saying the user can't edit the file and redirect when opening the url.

**Comment by lebouquetin** [comment]
I do not understand this issue and the associated fix. This issue tells that a user can edit a file even if he is a reader. There is no backend fix about right management of the `save()` operation, so I do not understand how this bug is fixed.

There are two possibilities:

- the description is wrong (the bug is : "the user interface allow a reader to edit the file - even if he can't save)
- the fix is wrong (the button is hidden but the API still allow to modify a doc)

@inkhey @basilelegal I need you to clarify this.

**Comment by basilelegal** [comment]
@lebouquetin Yes the description is wrong, I'll update it

**Comment by PhilippeAccorsi** [comment]
Verified.
