### ISSUE TITLE
Updates needed at new share form.

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2280]
## Bug description & symptom

- [x] Change error message for invalid emails to a clearer one and put a size limit.
- [x] Leave the password mechanism similar to the one used when a new user is created.
- [x] Do not refresh page while all inputs aren't perfects
- [x] In case there is no sharing in progress on the file, the view should directly display the form for entering emails (same type of workflow as when creating an html document for example).
- [x] The name of the button to create the share should be "Validate" instead of "new".

**Comment by PhilippeAccorsi** [comment]
tested and working:
- ~~hange error message for invalid emails to a clearer one and put a size limit.~~
- ~~Leave the password mechanism similar to the one used when a new user is created.~~
- ~~Do not refresh page while all inputs aren't perfects~~
- ~~In case there is no sharing in progress on the file, the view should directly display the form for entering emails (same type of workflow as when creating an html document for example).~~
- ~~The name of the button to create the share should be "Validate" instead of "new".~~

Verified.
