### ISSUE TITLE
Hide the archiving function

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2347]
## Bug description & symptom

We need to hide the archive buttons because it is not possible to retrieve the archives yet.

## Expected

Hide the archive buttons.

**Comment by PhilippeAccorsi** [comment]
I think its just necessary to not show button about archive.
What do you think about this issue @lebouquetin ?

**Comment by gbonaspetti** [comment]
> I think its just necessary to not show button about archive.
> What do you think about this issue @lebouquetin ?

The idea to delete everything linked to archive came from a conversation with @Skylsmoi, this will not pollute the code with comments and, as this branch will be just for that, it will be easy to reverse if necessary. Besides, all the archiving functionality should change when we decide to put it again, and the interfaces will also have changed, so much of the code will need to be redone anyway.

**Comment by lebouquetin** [comment]
The archive/unarchive feature is already working, even in frontend. If you remove the code we will have to test that re-inserting it will work (actually, I'm pretty sure there may be refactors in the next weeks), so I do not agree with "removing all the stuff".

We do not remove the feature, we hide it because there is no way to always restore an archived content. We already implemented the restoration (try on algoo.tracim.fr)

**Comment by lebouquetin** [comment]
by the way, the only part which must be commented is the component in the UI, all implementation mechanisms should not be commented - there is no requirement for that

**Comment by PhilippeAccorsi** [comment]
Verified.
