### ISSUE TITLE
Stabilize preview generator integration

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#249]

**Comment by tracim** [comment]
3 things to do :
- use the latest version of preview-generator (using the github depot) instead of the official release
- create a bug for RC2 that change back this "preview-generator latest version dependency"
- check that for an office document, the page previewed is the right one (this remark is due to the latest fixes I did on Preview Generator)

**Comment by algooapy** [comment]
* add an indication about displaying download pdf buttons in tracim/tracim/templates/file/getone.mak and relevant controller
