### ISSUE TITLE
Tracim installation with docker image

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#260]
Expected : 
- have a docker image allowing end users to use tracim
- have a "one line installation" process in the documentation

**Comment by PhilippeAccorsi** [comment]
expected: 

have a "one line installation" process in the documentation

**Comment by tracim** [comment]
@algooapy what is "not working" on the one line installation through docker ?

**Comment by algooapy** [comment]
Things to fix I have in mind:
- `tracim`/`nginx`/`uwsgi` settings to get calendars,
- `libreoffice` missing dependencies,
- test `PostgreSQL` / `MySQL`:
  About that: What about data persistence ? `SQLite` file is in host filesystem but no idea for the two former... Anyway, this is more a [`docker_tracim`](https://github.com/tracim/docker_tracim) issue for now because tracim `README` advertises the use of a `SQLite` based docker tracim container.
