### ISSUE TITLE
Add the automatic focus in the text areas

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2679]
## Feature description
When the user clicks to add/edit a text somewhere, the focus in the text area should be automatic.
It concerns:
- [x] edit a file or folder title
- [x] add a member in a workspace

## Context

Currently, when the user edit a title or add a new member, he/she has to click a second time in the text area.

**Comment by metzgegu** [comment]
In order to add autoFocus with tinyMce we need to enable it in its configuration, it can be enabled like [this](https://www.tiny.cloud/docs/configure/integration-and-setup/#auto_focus) but it will focus the first character of the text, In order to focus the last character of the text we can use [this](https://community.tiny.cloud/communityQuestion?id=90661000000IhC9AAK) instead

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
