### ISSUE TITLE
Default config fail with fresh install

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#273]
With fresh install, radicale have problem if don't set following parameters:

```
## Radical (CalDav server) configuration
# radicale.server.host = 0.0.0.0
# radicale.server.port = 5232
# radicale.server.ssl = false
radicale.server.filesystem.folder = /tmp
radicale.server.allow_origin = *
radicale.server.realm_message = Tracim Calendar - Password Required
## url can be extended like http://127.0.0.1:5232/calendar
## in this case, you have to create your own proxy behind this url.
## and update following parameters
radicale.client.base_url.host = http://127.0.0.1:5232
radicale.client.base_url.prefix = /
```

Détails:
* radicale.server.filesystem.folder: without set, strange path and radical fail to create ics files
* radicale.server.allow_origin: CORS fail when radicale on other port/domain. Logical but, maybe * should be default value ?
* radicale.client.base_url.host: without this param, calendar url is 127.0.0.1:5232 and caldavzap regex fail because search starting http://

**Comment by algooapy** [comment]
The `radicale.server.allow_origin` configuration parameter is after all not involved: by default, `radicale.server.allow_origin` reuses `website.base_url`.

The `CORS` errors are the result of caldavzap misunderstanding its inability to retrieve calendars, which is finally due to improper `filesystem_folder` `Radicale` setup.
