### ISSUE TITLE
Agenda in docker stuck on "loading ressource"

### ISSUE THREAD

**Issue by jbonlinea** [tracim/tracim#2774]
Hi

I'm new to tracim and did a first test run with "quick start  (using docker)" ! 
The only change I did is the port used by tracim "9880:80' instead of "8080:80" as I already use this port.

## Bug description & symptom

Tracim runs but the agenda tabs stay stuck on "loading ressources", both for "shared space agenda" and "all my agendas"

## Diagnostic

I've seen this issue from which I assume agenda should be working https://github.com/tracim/tracim/issues/1567

and I couldn't find any other relevant info

## Expected

I expect the agenda to load

## Context and version information

- Desktop environment (if applicable)
    - *OS: debian stretch for the host and debian stretch for the guest on virtual box
    - *Browser fifrefox 68.6.0esr and chrome Version 80.0.3987.132 (Build officiel) (64 bits)
    - *Version see above

## Prerequisites

none that i'm aware of

## How to reproduce

see above

## Screenshots

![Capture du 2020-03-19 16-37-46](https://user-images.githubusercontent.com/23659411/77085013-0387d800-6a00-11ea-9234-18eb9b5f9258.png)

## Impacted components

agenda

## Extra information

? 

Beyond that Tracim looks awesome :)

Cheers

**Comment by PhilippeAccorsi** [comment]
I jbonlinea,

The problem here is Tracim configuration is make for port 8080 (by default for testing Tracim on local machine). If you want to use another port and/or another url for accessing to Tracim, you need to change default value visible in this file `~/tracim/etc/development.ini` (you need sudo/root access to change this file).

This config file is created automatically when you start Tracim for the first time.

For your installation you need to change this line `basic_setup.website_base_url = http://localhost:8080` by `basic_setup.website_base_url = http://localhost:9880`. If you want to access to Tracim from another machine on your network, you need to change line from this `basic_setup.website_base_url = http://localhost:8080` to this `basic_setup.website_base_url = http://<ip_of_tracim_host>:9880`.

After this chnage you need to stop docker container and start again tracim with docker run (simple way). 

Best regards.

**Comment by Skylsmoi** [comment]
Question is answered and no more activity.
Closing
