### ISSUE TITLE
Add Tracim Events and Tracim Live Message related tables in database and fill them

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2828]
## Feature description

To support notification feature of tracim, we do need two new database tables:

- [x] `event`

| name       | type     | comment                                                     |
|------------|----------|-------------------------------------------------------------|
| event_id   | integer  |                                                             |
| event_type | string   |                                                             |
| date       | datetime |                                                             |
| fields     | JSON     | information needed to display a message (related ids+names) |

- [x] `message` : same as event but related to someone and with a read/unread status.

| name        | type     | comment                                                   |
|-------------|----------|-----------------------------------------------------------|
| event_id    | integer  | foreign key to event                                      |
| receiver_id | integer  | user id that is the recipient of the message              |
| sent_date   | datetime | when the message was sent                                 |
| read_date   | datetime | initially NULL, used to confirm the message has been read |

And a generic mechanism  in Tracim for creating events in the database :

- [x] it will observe the database entities changes and generate events based on those
- [x] the contents of the `fields` column shall be enough for the frontend to display the messages without needing to query the backend (messages are "self-sufficient")
- [x] The generation and publication of messages (using #2837) will be delegated to a RQ job called "TLMBuilder"
- [x] the new mechanism has to take #1589 into account: it is not needed to do it in this issue, but it must provide a satisfactory solution for it.

## Implemention summary

- entity events are generated when their respective objects are flushed to the database by using sqlalchemy's event mecanism. This solution has been chosen because it ensures all changes are captured at the right time as the various api classes have rather complex behavior regarding save parameters (see #3035). When this complexity has been refactored and an access to the plugin manager has been provided to the apis (#1834) we can think of moving those hook directly in the api classes.
- `pluggy` hooks are used to propagate events (`on_user_created`/... hooks)
- Event creation is done by one class `EventBuilder` which also post a job in RQ for message creation & dispatch
- Message creation is done by `LiveMessageBuilder`, currently not integrated in a RQ worker (waiting for #2991).
- Endpoint for retrieving messages has been written (`MessageController` class).

**Comment by Skylsmoi** [comment]
@inkhey Can you edit this issue description please ?

**Comment by inkhey** [comment]
Suggestion of database table:

For Tracim Event:

| Field Name | Type                                  | Others caracteristics                                       | goal                                                    |
|------------|---------------------------------------|-------------------------------------------------------------|---------------------------------------------------------|
| event_id   | integer                               |                                                             | identify event                                          |
| event_type | varchar                               |                                                             | store type of event like                                |
| author/initiator     | integer                               | nullable                                                    | author/initiator of the event if exist                            |
| event_data | json type or varchar with json inside | using https://github.com/penguinolog/sqlalchemy_jsonfield ? | contains all ids and more needed to get info from event |
| date       | datetime                              |                                                             | store the date when the event occured                   |

For Tracim Live Message:

| Field Name  | Type    | Others caracteristics | goal                                      |
|-------------|---------|-----------------------|-------------------------------------------|
| event_id    | integer | foreign key ?         | allow to join event ("parent")            |
| message_id  | integer |                       | identify a TLM                            |
| receiver_id | integer |                       | id of the user which will receive the TLM |

**event_data** remain unclear, we can instead of using this have normal ids field, but it will make thing less clear and less adaptable:
- we can have a multiple meaning id field but that seem a bad idea
- having a workspace_id, content_id, user_id, etc… fields will probably mean empty field …

**Comment by lebouquetin** [comment]
TODO clarify @inkhey @lebouquetin together the way to represent this in the database

**Comment by inkhey** [comment]
@lebouquetin 
This issue is related to these technical debt issue:
- #1487
-#1834
- #1589

These issue are related to the fact the event mecanism of tracim for pluginification is not fully used in tracim itself.

We should decide if we : 
- add event feature but create some technical debt.
- remove partially the technical debt here.
- remove all technical debt.

**Comment by grignards** [comment]
@lebouquetin @inkhey 
I got some ideas/questions about the storage of Tracim Events:

- I think the relationship between an event and its entity should be stored using a dedicated foreign key column (not in the JSON column) as this allows the DB to handle all the data integrity. This also simplifies the queries joining an event and its entity(-ies).

- Is an event always related to *zero or one* entity ?

If yes an approach with a base common table for all entities (id + name/label(?)) and a foreign key in the `event` table pointing to this common table would be the "cleaner" way, at the price of a potentially harder migration (I'll check how this is handled in alembic).
If an event can be related to several entities we would need an additional reference table with `(entity_id,event_id)` as columns.

- a third possibility would be to have as many `xxx_id` columns in the `event` table as we have entity types, but as you mentioned earlier, this means many NULL values in the `event` table, more complex queries and would require to add columns to this table each time a new entity type is created.

**Comment by grignards** [comment]
BTW we'll also have to decide whether to keep the `created`/`updated`/`is_deleted`/... attributes in the entity tables as with this information will also be written in the `event` table. Of course if we go the "full-event" way, this can be realized after the v3.0.

**Comment by inkhey** [comment]
> BTW we'll also have to decide whether to keep the `created`/`updated`/`is_deleted`/... attributes in the entity tables as with this information will also be written in the `event` table. Of course if we go the "full-event" way, this can be realized after the v3.0.

I see some issue with a full-event way:
- Performances issue to get the information, in particular when we need to get the created/updated value for multiple items.
- Not always easy to deal with that in code. We move last revision_id into content table to allow to easily make performant join for content instead of making weird join stuff to get the last revision of the content at each request
- We can's delete event this way. And event table will probably becoming huge. TLM table should maybe be deletable from tracim UI and i do think event should be deletable too.

**Comment by grignards** [comment]
> - Performances issue to get the information, in particular when we need to get the created/updated value for multiple items.

Yes of course this is a balance between performance/simple code and having one source of information.

> - Not always easy to deal with that in code. We move last revision_id into content table to allow to easily make performant join for content instead of making weird join stuff to get the last revision of the content at each request

The `Content`/`ContentRevisionR0` modeling is still a bit unclear for me, do you have documentation on it ? Or is it "Use the code, Luke" :wink: ?

> - We can't delete event this way. And event table will probably becoming huge. TLM table should maybe be deletable from tracim UI and i do think event should be deletable too.

The size of the `tlm` table is is the first concern, `event` is a less problematic as the TLM table's size is a multiple of the `event` table size (assuming nothing is never deleted). This is not important right now, but can have an impact if/then the `tlm`/`event` tables become big (I would expect that a few millions rows is the "sustainable" size for such a table).

And do you know if events should be kept independently of their entity ? Or do we delete events when their entity is deleted ?

**Comment by inkhey** [comment]
> > * Performances issue to get the information, in particular when we need to get the created/updated value for multiple items.
> 
> Yes of course this is a balance between performance/simple code and having one source of information.

I agree, i do think for the revision_id and event case, this is acceptable. we don't have much duplication in other part of the database (i don't remember any other case than the specific revision_id).

> The `Content`/`ContentRevisionR0` modeling is still a bit unclear for me, do you have documentation on it ? Or is it "Use the code, Luke" wink ?

There is no documentation yet about this part. But the basic is that content can completely change from one revision to one other. Also in current code each revision contain his self data, which mean currently lot of file duplication for file object. I suggest you to check the database schema first and then check the code.

> 
> > * We can't delete event this way. And event table will probably becoming huge. TLM table should maybe be deletable from tracim UI and i do think event should be deletable too.
> 
> The size of the `tlm` table is is the first concern, `event` is a less problematic as the TLM table's size is a multiple of the `event` table size (assuming nothing is never deleted). This is not important right now, but can have an impact if/then the `tlm`/`event` tables become big (I would expect that a few millions rows to be the "sustainable" size for such a table).
> 


> And do you know if events should be kept independently of their entity ? Or do we delete events when their entity is deleted ?

We probably need to notify user that something has happened whenever the related content has been deleted, if not we may have unconsistent TLM that disappear from user side which is annoying.

**Comment by grignards** [comment]
> If yes an approach with a base common table for all entities (id + common columns) and a foreign key in the `event` table pointing to this common table would be the "cleaner" way, at the price of a potentially harder migration (I'll check how this is handled in alembic).

I checked with alembic, it doesn't provide a proper auto-generated migration for such a case (as I expected). We'll have to write the migration operations manually.

**Comment by lebouquetin** [comment]
> And do you know if events should be kept independently of their entity ? Or do we delete events when their entity is deleted ?

TLM MUST be independant from entities. If you delete a content, associated TLM must remain in the database: users still have history

For the Content/ContentRO, there is no specific documentation but @inkhey @buxx or @lebouquetin can explain how it is working

It's ok for now to have a data model which does not scale larger than millions of TLM entities. We'll rework this when "Mon Tracim" instance will be in the process of slowing down (or just before). Do not "code scalable stuff" before to have working stuff

**Comment by lebouquetin** [comment]
close was a misclick, sorry
