### ISSUE TITLE
Allow searching members in a given list of workspaces in the known_members endpoint

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2830]
## Feature description

In order to allow mentioning users, a parameter needs to be added to the `known_members` endpoint  to filter returned results for a given workspace: `include_workspace_ids`.

This parameter must be optional and is mutually exclusive with the `exclude_workspace_ids` parameter. Allowing to use both parameters at the same time would be possible. However, the exact behavior of the endpoint when both parameters are set will need to be specified.

Expected:
 - [X] add support for an `include_workspace_ids`
 - [X] Produce an error when both `include_workspace_ids` and `exclude_workspace_ids` are set to non empty lists
 - [X] Allow both parameter to be set if at least one is set to the empty list

## Extra information

Previously done:
- ability to search on the `username` field => done with #2829 
- have a `username` in the response structure. (raphj: it was already there as far as I can see)

_____
_Edited 2020-07-21: update the ticket with the latest decisions ("expected" list), and move what was actually already done in previous developments in the Extra information section._

**Comment by raphj** [comment]
This endpoint supports a `exclude_workspace_ids` parameter. I suggest implementing an `include_workspace_ids` parameter for symmetry, instead of `workspace_id`. We will also need to make these parameter mutually exclusive.

**Comment by lebouquetin** [comment]
> We will also need to make these parameter mutually exclusive.

Not sure this is required; and it can make programmation of API more complex.

For example, when you do mathematics, it's not forbidden to calculate: `2-2+3-3+4+5-5-4`. You know what I mean?

I don't see a good reason for writing code which raise an error if the user call the API with `?exclude_workspace_ids=1,2,3&include_workspace_ids=1,2` (which result in exclude 3, I think).

Do you agree?

**Comment by raphj** [comment]
Mhm... the difference with an arithmetic operation is that the order of operations matters. Excluding and then including is not the same as including and then excluding. You described the latter. When I wrote my comment I did not know how the code worked. After implementation, this is luckily what the code does if we remove the exception but this needs to be explicitly specified.

I'm ok with not raising, but we then need to specify whether:
 - we should exclude and then include, or vice versa. It is not clear to me which order is best: what a code both excluding including some workspaces would want to achieve 
 - we should leave this unspecified to avoid adding constraint on future refactoring

Not raising actually smells like a feature that needs thorough thinking. Because of these complicated questions, in my opinion, it is best to raise for now, and remove the exception when we need the feature. The exception will help catch an incorrect usage of the API since we don't really know wath both including and excluding worskpace at the same time should really do.

What do you think @lebouquetin?

**Comment by PhilippeAccorsi** [comment]
Verified.
