### ISSUE TITLE
[META] Handle mentions in the backend

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2838]
## Feature description & context

Tracim will offer the possibility to mention other users (`@user`) when creating/editing html documents, threads and comments. 

What needs to be done:

- [x] #3347: generate events for mentions for created HTML documents and comments (including threads)
- [x] #3349: create and publish TLMs for `mention.created` events.

## Discussed

Agree to parse content to find mentions in the backend (see discussion below):

- a first parsing of the mentions will be done in frontend where all the mentions will be surrounded with an html tag, this tag will have a unique id, the backend will parse the content looking for this tag. Html tag as generated by the frontend:
```html
<span id="mention-<uuid>">@all</span>
```
A `mention.created` TLM will then have a `mention` field:
```json
"mention": {
  "recipient": "all",
  "id": "<uuid>"
}
```

- if the user makes a mention in an html-doc and decide to change it afterwards, the new user mentioned will not be notified
- The backend does not manage a specific entity for the mentions (they will just be included in the TLMs and the api allowing to retrieve the notifications).

## Extra information

Can be found in Algoo's Tracim, search for "Projet refonte des notifications".

----
_13-07-2020 - Description edition:_
      - _Added task "should send a error message if username collides with group mentions and linked with translations._
      - _Added task list and linked with Algoo's Tracim document "Projet refonte des notifications"._
      - _Added mention fields._
      - _Added translations._
_16-07-2020 - Description edition: Put context at beginning._
_17-07-2020 - Description edition:_ 
      - _Delete line field._
      - _Divide this meta issue into multiples smaller issues._
_20-07-2020 - Description edition: Reference threads._
_23-07-2020 - Description edition: Solve discussion._
_29-07-2020 - Remove #3348 and update description of the html tag for mentions._
_07-08-2020 - Remove the checkbox associated to #3348 - irrelevant with the new design we settled on
_07-08-2020 - Remove the checkbox associated to #3350: handle the translations of group mentions - we are not doing this yet finally

**Comment by lebouquetin** [comment]
I labelled this issue with `blocker` because it needs to be refactor before anything else

**Comment by inkhey** [comment]
Not sure to understand what the idea for parsing mention in backend:
- Content is considered to be HTML Based for both **html-content** and **comment** which mean potential issue because mixing html and regex is not a great idea.
- some text based file do use `@someone` syntax like plantuml which mean potential "fake-positive".

It's also unclear where is the beginning or the end of the mentionned content ? Should it be all comment ? just a part of the comment ? Html based content ? text version only ?

**Comment by raphj** [comment]
@inkey you can still parse HTML using a proper parser (vs regexes). I think the heavy lifting of finding the mentions should be done in the backend (imagine someone uploading a document or leaving a comment with a dumb client or through webdav: we have no choice of handling this in the backend if we want to handle mentions in this case).

If you don't agree we should discuss with the frontend team.

**Comment by lebouquetin** [comment]
@raphj @inkhey by the way, mentions are not dedicated to html documents and comments: they are expected in all contents (like thread, markdown-document, custom forms, etc). So the right way to implement it is to parse the description field of content creation/content update, not specifically html-document and content.

Design principle: `Ouvert à l'extension, fermé à la modification.`

**Comment by raphj** [comment]
@lebouquetin I think the idea is indeed to make things as generic as possible. However, the parsing itself will probably have to be specific per format. IMHO we can't enable mentions in custom forms or markdown documents without specific handling (we must make adding support for a new format as easy as possible though). Given this, it seems to me that enabling mention first in HTML documents and comments (which effectively enables mentions in threads for free) is a good start for Tracim v3.1. What do you think?

**Comment by raphj** [comment]
I advocated parsing mentions in the backend last week but coming back to this today, I also have arguments against it, or at least concerns to address. How do we handle the case where there is `@something` in the document, but we don't actually mention someone (say, because we are speaking about Tracim mentions in a Tracim document). Should we implement some escape mechanism? Otherwise, it might make sense to generate mentions in the frontend.

We should definitively speak about this before starting the development.
@lebouquetin @inkhey @Skylsmoi  @gbonaspetti

**Comment by raphj** [comment]
What's more, it could make handling the diff far more easier than re-parsing a new version of a document, trying to find the new mentions. This, however, forces us to hook into TinyMCE to detect mentions, but this is something we will need to do at some point anyway to allow mention autocomplete.

**Comment by grignards** [comment]
@raphj Both your comments are right, but the aim is to allow users to add mentions even by editing outside of the frontend's gui, so a frontend-assisted mention generation is difficult to realize. This also would make the mention system tighly linked on the content's format (html/text/…) which is not wanted either.

**Comment by inkhey** [comment]
> @raphj @inkhey by the way, mentions are not dedicated to html documents and comments: they are expected in all contents (like thread, markdown-document, custom forms, etc). So the right way to implement it is to parse the description field of content creation/content update, not specifically html-document and content.
> 
> Design principle: `Ouvert à l'extension, fermé à la modification.`

We can implement it in description fields, but this also mean that if we do want to convert html document to "standard file" later, we should do some refactoring to keep support for it.

Support for real file content is possible but will need rule to avoid checking binary file or very big text file for mention.

As we do want something that can work everywhere, without any html specific rule, this probably make regex mandatory. This also mean that we may accept some "weird" case as we do not expect html, so mention may be hidden into html code.

For regex, after rechecking the rule for username, we should probably use a regex like this one:
`(^|\s)@[\w-]{3,255}`

**Comment by inkhey** [comment]
> I advocated parsing mentions in the backend last week but coming back to this today, I also have arguments against it, or at least concerns to address. How do we handle the case where there is `@something` in the document, but we don't actually want to mention someone (say, because we are speaking about Tracim mentions in a Tracim document). Should we implement some escape mechanism? Otherwise, it might make sense to generate mentions in the frontend.

There is effectively one issue here with the "reply to" email feature case if the original message contain mention.

**Comment by raphj** [comment]
Right.

As for the regex: we might need something more complicated, like `(^|[\s.;:!?])@[\w]{3,255}` (not complete) to allow punctuation before the mention.

**Comment by raphj** [comment]
> This also would make the mention system tighly linked to the content's format (html/text/…) which is not wanted either

It seems to me we don't really have a choice here. But I agree with you that we probably want to support mentions with webdav or when uploading files. Though this can have unintended side effects: if you mass move files in a Tracim instance, you might be generating a lot of mentions. So I'm not really sure we should support generating mentions with webdav and file uploads for the first iteration neither. I think we want to be really sure that the user actually intended to create a mention, instead of having accidental generations of mentions. This might require an UI action. Let's invoke @celiamgtt to know what she thinks here.

**Comment by inkhey** [comment]
> Right.
> 
> As for the regex: we might need something more complicated, like `(^|[\s.;:!?])@[\w]{3,255}` (not complete) to allow punctuation before the mention.

`¡¿` too.

**Comment by raphj** [comment]
After discussion with inkey, for the regular expression, we probably want to adopt a blacklist-based approach instead of a whitelist based approach. something like `[not an alphanumeric character]@[usernameAllowedCharacters]+`. This will handle all the corner case, and prevent false positive on the only(?) case that matters: email addresses.

**Comment by lebouquetin** [comment]
@raphj @inkhey why not something like [whitechar or nothing]@[username] ? this seems enough, no? for example, in github comments you cant put a mention right after a point.

**Comment by raphj** [comment]
We discussed with @lebouquetin on this issue: `titi.@example.org` is actually a valid email address, so the issue is more complicated than we (@inkhey and me) anticipated.

We probably should start with `[whitechar or nothing]@[username]` and then support more complicated things later if needed.

We can also make the frontend add a space before the `@` sign (later, if needed too).

**Comment by raphj** [comment]
Moved to "To close", all the items of this meta bug have been handled.
Should we use `not in changelog` for this kind of case @PhilippeAccorsi?

**Comment by PhilippeAccorsi** [comment]
> Moved to "To close", all the items of this meta bug have been handled.
> Should we use `not in changelog` for this kind of case @PhilippeAccorsi?

Yes.
