### ISSUE TITLE
word not translated in date format

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#286]
modification date of a file contains a "at" which is not localized

```${h.format_short(created_localized)|n}``` should returned a fully localized string

**Comment by algooapy** [comment]
Did not reproduced this issue: The string `${h.format_short(created_localized)|n}` is conveniently translated, either in french or in english.

However:
- the french translation adds the grammar article _le_ at the beginning of the translated string, making a duplicate _le_ with the previous string _Modifié le_,
- the date should be `updated_localized` instead of `created_localized`.
