### ISSUE TITLE
Feat: Get rid of the button to select the language in the header bar

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2884]
## Feature description

In order to unclutter the header bar, I suggest we remove the button to select the language from the header bar. This button takes space and is probably never or very rarely used by the majority of people who have one language they work with.

I suggest we move this button to the settings page.

The language can be determined (and is already, as far as I know) using the setting given by the browser. We may also decide to add a screen to make the user choose their language during the first login if we are afraid people could have their browser misconfigured.

@celiamgtt told me that some people like @PhilippeAccorsi may need an easy access to this feature for testing purposes. We could add the possibility to use a GET parameter such as `?lang=fr` to easily switch languages.

## Impacted components

- *frontend*

**Comment by PhilippeAccorsi** [comment]
I not sure is a good idea to not show button (maybe just show flag), because when you are not on your computer (ex: technicien in travel) you cant understand interface of tracim to know where you need to go to chnage language.

Also for testing (but maybe for testing we need an option to show this button on local), if we nned to go in user parameter to chnage language and check if translation working, its very  very long to make test or to help users.

Actually login page show language of your browser (and I think its the same for first connection). After that, language in interface is normally the language of the user (parameter seved in database).

We can also define default language for tracim in backend config file.

we need to think about the use case (client use case), not just us case.

**Comment by Skylsmoi** [comment]
I think that on the web, websites allowing to change the language usually display the button on the header.

We, as user, are used to change the language using a parameter menu only for mobile apps, games or software. On a website, you only have a parameter menu when you are logged in which is the "my account" page.

I don't think removing it is the solution to the problem of having enough space in the header. To me, a redesign seems easier and more suited.
Some redesign should happen for the v3, see this issue https://github.com/tracim/tracim/issues/2839
