### ISSUE TITLE
Feat: Create database migration script for username column

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3048]
## Feature description

A `username` column has been added to `users` table. This must be handled in a database migration script.

## Context

It must be possible to migrate an existing database to the schema of the 3.0 version.

## Prerequisites

- #2933 
- #2828 (so that its migration script is available)

## Impacted components

- backend

## Extra information

The development should be done starting from the feature/2829__unique_user_username branch. develop must have been pulled (with #2828 merged in it) before creating the script.

## Implemented Solution
see https://github.com/tracim/tracim/pull/3118
- rename username or email constraint to follow ck convention (not activated now because it break migration on mysql)
- add one more downgrade/upgrade in migration test to ensure consistency.
- add migration script to add username field and check constraint (with specific code for sqlite to handle the fact that check constraint are drop automagically with batch ops).

**Comment by lebouquetin** [comment]
@grignards for the future, I suggest to include this kind of development in the same issue that add the new fields in the database.

Reasons are the following ones:

- there are tools (CLI commands) that allow to generate the scripts in one command line
- it allows to directly test with production database (we take a dump from a production database and start it with the new version of the code)

The tradeoff is that we may have several migrations for a given release. But it allows to run `develop` branch at any time with any data source - this is a very important point (especially for testing behavior with data: it allows to get large reallife datasets at no cost).

By the way, automatic tests should fail when modifying schema without associated migration because there is a scenario which downgrade/upgrade. @inkhey you confirm?

**Comment by lebouquetin** [comment]
@buxx when fixing #2933, you did not implement migrations?

@inkhey you validated the merge request https://github.com/tracim/tracim/pull/2961/files. When there is a model modification [like here](https://github.com/tracim/tracim/pull/2961/files#diff-b060f7734d2ced4612cba2b2f0f77fe8) you must reject merge request if no migration scripts are included. Currently *develo* is broken.

You would tell me "it works in dev environment" but it breaks a rolling release strategy which is opposite to the development strategy of the project, and more critical: it prevent from testing with real data sets. (and I'm pretty sure there are no good reasons for spliting feature dev and migration dev)

**Comment by grignards** [comment]
> @grignards for the future, I suggest to include this kind of development in the same issue that add the new fields in the database.

OK for me, I will do the event/message part in the related issue.

I checked the PR (#2961)  of the `username` column and didn't see the migration script, so I modified this issue to ensure a migration script is created.

**Comment by buxx** [comment]
@lebouquetin 

> @buxx when fixing #2933, you did not implement migrations?

No I didn't. The target branch of these developments was not `develop` branch but `feature/2829__unique_user_username` so migration scripts was not required. That was a summed choice (no such time in my week to develop most urgent features for frontend team).

**Comment by lebouquetin** [comment]
I misread the impact of your development @buxx . I understand that CI is not broken.

I think the main point in my messages is that we must deliver migration scripts in same MR than model modification. I'd like you all agre with me or we need to have a chat about this. @grignards @buxx @inkhey @raphj 

In the current case, my feeling is @inkhey should have continued your development by adding migrations. Do you agree?

**Comment by buxx** [comment]
I agree that deviler migration script at same time is a better strategy ^^

**Comment by inkhey** [comment]
> I misread the impact of your development @buxx . I understand that CI is not broken.
> 
> I think the main point in my messages is that we must deliver migration scripts in same MR than model modification. I'd like you all agre with me or we need to have a chat about this. @grignards @buxx @inkhey @raphj

I agree, it's better to have a MR with needed migration script for subticket (ticket about a part of a ticket, done in a specific big ticket branch). We should maybe have a clear strategy for these kind of cases, about what should and what should not be broken or not fully functional in develop or specific big ticket branch .
For example, in live_message support branch, we do not solve yet the "docker" support issue (for pushpin), as we do need to make a simple working mecanism to help frontend work and there is some discussion about how we manage this in docker (architecture change). So, it may mean broken docker not fully functional on develop or on a specific big ticket branch.

> 
> In the current case, my feeling is @inkhey should have continued your development by adding migrations. Do you agree?

I agree, i wasn't aware that the backend development was unfinished.

**Comment by inkhey** [comment]
Need frontend merge conflict solving with develop to fix this issue.

**Comment by lebouquetin** [comment]
@inkhey why writing a SQL migration need a frontend conflict merge? You are working from a conflicting shared branch? If so, this should be something like a priority, no? All backend developments are blocked... otherwise I do not understand why it would be blocked for this specific task.

**Comment by lebouquetin** [comment]
misclicked on close and comment instead of comment.

**Comment by inkhey** [comment]
> @inkhey why writing a SQL migration need a frontend conflict merge? You are working from a conflicting shared branch? If so, this should be something like a priority, no? All backend developments are blocked... otherwise I do not understand why it would be blocked for this specific task.

In fact it's not completely, required, it may be possible to rollback to previous commit, create the migration from here (in order to use the automatic feature of alembic which does not proper migration but allow us to be more confident about if something missing). I don't think there is migration conflict here, but may be better to ask @grignards first.

The fact is that we do not support branch in migration history, so we most probably need to do manual "rebase", in any case, before merging to develop. So we have to resolve merge conflict with both frontend and backend here, and as far in checked, it's not an easy task.

About blocking :as the feature for username is in a specific branch and migration script is not required to work on it, this doesn't block any development now. TLM feature can always been merge in develop and username lacking feature can be merge in username branch.
