### ISSUE TITLE
Feat: Remove v2/ in endpoints

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3052]
## Bug description & symptom

Current tracim api endpoint begin with `/api/v2/`
As we go to version 3, rule to follow is unclear for both new and existing endpoints.

## Impacted components

*For example:*

- *backend*
- *frontend*

## Implemented solution:
https://github.com/tracim/tracim/pull/3089
- [X] Remove /v2/ from endpoint in backend
- [x] adapt the frontend code to not use` /v2/` at all (including tests)

**Comment by lebouquetin** [comment]
I suggest to rename v2 to V3 *or* to remove the version part of the API (this is often considered as a bad design)

**Comment by inkhey** [comment]
@Skylsmoi Is this kind of refactoring complex to do in frontend ?

**Comment by grignards** [comment]
The main goal of API versioning is (IMHO) to be able to ensure retro-compatibility with old API clients.
I do not think we currently plan to ensure this retro-compatibility.

The other interest we could find is that it makes clear that something has changed (old API clients would get 404 if we move endpoints to `v3`).
And versioning through the uris is not RESTful as this means that the same resource is available through several uris (whereas REST recommends to only have one stable uri for a resource). Versioning is better done using the `Accept` HTTP header (the client uses it to specify the available version, the server can use it to indicate which versions it supports).

To conclude: if my hypothesis that we don't plan to ensure retro-compatibility is right, I would rather remove the `/v2/` prefix altogether as I think this or changing to v3 is more or less the same refactoring effort.

**Comment by lebouquetin** [comment]
> The main goal of API versioning is (IMHO) to be able to ensure retro-compatibility with old API clients.
> I do not think we currently plan to ensure this retro-compatibility.

We dont.

> The other interest we could find is that it makes clear that something has changed (old API clients would get 404 if we move endpoints to v3).

This is an explicit way to identify that things have changed and that there may be some refactoring required on the client side.

> And versioning through the uris is not RESTful as this means that the same resource is available through several uris (whereas REST recommends to only have one stable uri for a resource).

This is right if we maintain two or more versions of the API. For the case we want to explicitly inform that API has changed, it may stay RESTful.

> Versioning is better done using the Accept HTTP header (the client uses it to specify the available version, the server can use it to indicate which versions it supports).

I disagree with this: HTTP headers are not easy to use and to trace/monitor. One good example of "well engineered but hard to use" API is the mailjet one. Even pagination is done through HTTP headers which is counter-intuitive / difficult to use. The easier our APIs are to be used, the most they will be used.

> To conclude: if my hypothesis that we don't plan to ensure retro-compatibility is right, I would rather remove the /v2/ prefix altogether as I think this or changing to v3 is more or less the same refactoring effort.

I agree with this. I think we can remove the prefix. By the way I'd prefer to avoid using HTTP headers if possible for our entire API in order to make it as easy-to-use as possible (and as intuitive for non developer people as possible)

**Comment by PhilippeAccorsi** [comment]
I think this modification can implicate some modification in  custom_toolbox feature (maybe also frontend).

**Comment by Skylsmoi** [comment]
yes, it does have implications in frontend.
Kinda minor though

**Comment by Skylsmoi** [comment]
@inkhey please add clarification with the tag "blocked by frontend"
I don't see why frontend is blocking

**Comment by inkhey** [comment]
> @inkhey please add clarification with the tag "blocked by frontend"
> I don't see why frontend is blocking

Frontend need to be updated properly, especially in test to net rely on /v2/ so the current PR : https://github.com/tracim/tracim/pull/3089
is waiting for frontend fix.

**Comment by Skylsmoi** [comment]
Mmh, to me, this is not "blocking", it just a todo for frontend.

I would add the tag "frontend" with a checkbox in the issue description for the frontend refactor to do

Because "blocking by frontend" would mean that the backend can't do the work until the frontend does the refactor, which isn't the case I suppose

**Comment by inkhey** [comment]
> Mmh, to me, this is not "blocking", it is just a todo for frontend.
> 
> Instead, I would add the tag "frontend" with a checkbox in the issue description for the frontend refactor to do
> 
> Because "blocked by frontend" would mean that the backend can't do the work until the frontend does the refactor, which isn't the case I suppose

i do agree.

**Comment by raphj** [comment]
tested on branch
