### ISSUE TITLE
Feat: Handle TLM for app Gallery

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3107]
## Feature description

Refactor the app gallery with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

App gallery

## Design

(discussed with @celiamgtt):

- when a currently displayed image is deleted, the previous image is automatically changed. If this was the first picture, we move on to the "new first"
- when an unprinted image is deleted, the thumbnail is silently removed
- when an unprinted image is modified, the thumbnail is silently updated
- when a displayed image is modified, the display is updated
- if an image is added (or undeleted), the thumbnail is silently added

@celiamgtt says that people are used to content that automatically update, provided it is not disruptive (e.g. it does not loose work)

## Extra info

I'm not sure there is a lot to do here

**Comment by raphj** [comment]
This comment explains the implementation design for this refactor.

With the live messages, we are going to update the list of pictures as well as the currently displayed picture according to the live messages we receive.
 A first approach was to just reload the list of pictures from the server to ensure that we are always consistent with the list the backend sends. However, this did not end well.
 
 If several pictures are uploaded / modified in a short time, the list of pictures was downloaded several times before the state of the component had time to change even once, leading to crashes and weird behavior. Even if it worked, this would be an easy but inefficient way of handling
 updates.
 
 Imagine a folder with 1000 pictures. Are we handling this list again and again if 10 pictures are added? Come on, what was I thinking.
 
 So we are applying the harder but more correct approach: updating the list using the TLM.
 
 We still want to ensure consistency with what would be displayed if we downloaded the list of pictures from the backend though.
 
 This list built there at the time of writing this comment:
 
    backend/tracim_backend/views/core_api/workspace_controller.py
 
 In the workspace_content method of the WorkspaceController class we can see that the contents of a folder is **sorted by label**.
 
 That's what we are going to do.
 
 This is bad news though: if we are currently watching a picture that is renamed, it will move in the list.
 
 What is the correct behavior?
1. Not changing the current picture index if a picture is renamed.  This will not change the position, but this will make the currently picture change "out of nowhere"
2. Changing the position does not has this downside, but the user might lose track of its picture browsing session.
 
Since anything could happen with the list of pictures anyway (imagine someone taking the time to sort their Tracim folder and renaming random pictures for instance). We cannot really avoid the downsides of 2) anyway. We will at least free the user from liberal image jumping.
 
 We are not done yet though. As you may know, sorting is a rabbit hole. You may know that sorting depends on a lot of things like the charset and the locale. How does the backend sorts strings here?
 
 This is defined by the order_by_properties attribute, used in method _get_all_query of the ContentApi class defined in `backend/tracim_backend/lib/core/content.py`.
 
 There, we can see that this property is used to build an `ORDER BY` SQL clause. So how does SQL sort? [Here is the relevant documentation for PostgreSQL](https://www.postgresql.org/docs/current/locale.html). Long story short, this is configurable using LC_COLLATE. This means we need to get this piece of information from the backend, which we probably don't have yet.
 
 In Javascript, we have the [String.localeCompare method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) to sort strings.
 
 It takes an optional locale parameter to use the right sorting algorithm.
 We have two choices:
1. leave it blank. The exact sorting is implementation-defined.
2. we pick an arbitrary value (like English).
 
 For now:
  - we will not specify the locale. Any value is incorrect anyway. We can hope that visitors and the serveur are set to the same locale so this will work by chance in many cases.
  - this will cause discrepancies between the backend and the frontend if it's not the case and people use accents or other funny characters.
  - relevant issue: https://github.com/tracim/tracim/issues/3159

**Comment by lebouquetin** [comment]
> @celiamgtt says that people are used to content that automatically update, provided it is not disruptive (e.g. it does not loose work)

If you are reading/looking at something and the interface is dropping it, people are not used to accept this. This is not only about loosing work but about disturbing what you are doing.

**Comment by gbonaspetti** [comment]
Verified on develop.
