### ISSUE TITLE
Bug: finding how to add workspace members is hard

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3208]
## Bug description & symptom

To add workspace members, one needs to click on a small button labeled "advanced dashboard". There is already a list of members in the dashboard from which one can already delete members. One could expect to be able to search for a member and change their role right from this list.

I think we should get rid for the workspace advanced app and puts its features right in the dashboard, including a red delete button that could require the user to input a sentence like "yes, I'm sure I want to delete this workspace" like when deleting a github repository.

It is also a problem that the list of member is almost hidden when the scoll bar is at the top on many regular screens, and therefore hard to notice.

On a related note, the person who gave me feedback that prompted the creation of this issue was willing to read some help to find out how to change the role of a member but could not find it.

## Expected

The list of members in the dashboard is visible on regular screens, and allows fully managing the members.

## Impacted components

- *backend*

**Comment by Skylsmoi** [comment]
Dashboard is meant to be visible by any ROLEs of the shared space.
We plan to have different dashboard related to the user's ROLE but this is for later development.

For the advanced workspace app, we also plan on adding more configuration features later, that's why we have a specific app.

Basically, the dashboard should be for reading datas and having shortcut for creating content and all the management should be in the advanced dashboard.
This means that I agree with you about the delete button for members in the dashboard, it shouldn't be there.
The dashboard layout/design can also be reworked indeed.

But I don't think we should put the configuration options in it

**Comment by yvan-algoo** [comment]
@lebouquetin

**Comment by yvan-algoo** [comment]
Wontfix
