### ISSUE TITLE
Feat: Give the opportunity to members to unsubscribe from a shared space.

### ISSUE THREAD

**Issue by obrowny** [tracim/tracim#3301]
First of all, thank you for your good work :)

## Feature description
- Give the opportunity to members to validate the subscription.
Bob shares a space with Alice. Alice has to accept the sharing space before it appears on her Tracim.

- Give the opportunity to members to unsubscribe anytime from a shared space.
Alice considers she doesn't need Bob's shared space anymore, she should be able to unsubscribe without the acknowledgement of Bob. After all this is «son.tracim» and she should be able to choose what she wants to see.

## Very bad context

Let's say Bob creates a new «naked nazi cats with guns» shared space and adds Alice as a member to it. Alice can't unsubscribe to that unwanted shared space.
Moreover, knowing that, on the public instance, Bob potentially has access to anybody (typing 2 letters), it is easy to force users to access unwanted shared spaces with no possibility for Alice or any member to refuse that space.

Such context could ruined the public instance.

**Comment by gbonaspetti** [comment]
Hey @obrowny 
Thank you for your contribution here.
Can you tell me which version of Tracim you have? We have had the option to leave a space since version 3.2.1.
If you are on a version that has the functionality, I will leave below a GIF that shows how to leave a space. The interface you see in the GIF is from version 4.0.2.
![leaveSpace](https://user-images.githubusercontent.com/35422692/142588882-1b559e72-a6fa-4e16-985b-e8a7227e89b3.gif)
Step by step:
1. Click on your name in the header
2. Click on "Account Settings"
3. Click on "Spaces"
4. Leave the space that you want :smile: 

While I am at it, I would like to recommend to you our community space. Whenever you need a more quicker answer or want to share your feedbacks and experiences with us: https://public-community.tracim.fr/

**Comment by gbonaspetti** [comment]
Since everything looks fine and the feature already exists, I'll close this issue.
