### ISSUE TITLE
Feat: Generate events for mentions in HTML documents and comments

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3347]
## Feature description and goals

In order to generate TLMs for mentions (meta: #2838), we need to be able to generate events for mentions in:
 - [x] HTML documents
 - [x] comments

Those events, of type `mention.created`, will have a `mention` field (with the found mention and its id in the content), `workspace`, `content` and `author` fields:

```json
"mention": {
  "recipient": "all",
  "id": "<uuid>"
}
```

Those events will be created for new mentions when creating and modifying the content. This will be done by parsing the `description` field of contents as it is used to store the html documents and comments.

- [x] new `EntityType.MENTION`, create the related migration script.
- [x] add `parent_content_type` in `CommentSchema` and ensure it is present. The frontend needs it to link back to the content in the notification panel.

##  Discussed

- How to do the parsing of HTML: we'll use [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/) which is already a backend dependency.
- Agree to do it in the backend (see discussion in the meta-issue): The frontend will do a first parsing adding html tags and the backend will search this tags.
- Be sure to address this comment: https://github.com/tracim/tracim/issues/3347#issuecomment-660313273 (and edit the issue accordingly)

## Extra information

- Keep #3348 in mind when working on this issue.
- We plan to handle the translation of the group mentions: #3350

----
_20-07-2020 - Description edition: linked this issue to #3347 discussion_

**Comment by lebouquetin** [comment]
the mentions are not related to html content or comment but about content description. It should be generic otherwise all new contents will require to upgrade the mention process.

Other point: I think if a user mention another one in a comment, I'm not sure there should be two TLM... otherwise when showing the full history, there will be two events:

- one being the comment `Hi @damien, could you read the new revision of the documentation?` linking to the comment?
- one being the mention `Hi @damien, could you read the new revision of the documentation?` linking to the comment?

I would add a mention property to existing TLM (property could be structured), no? No backend developer talked to you about this issue?

**Comment by grignards** [comment]
> the mentions are not related to html content or comment but about content description. It should be generic otherwise all new contents will require to upgrade the mention process.
> 
> Other point: I think if a user mention another one in a comment, I'm not sure there should be two TLM... otherwise when showing the full history, there will be two events:
> 
>     * one being the comment `Hi @damien, could you read the new revision of the documentation?` linking to the comment?
> 
>     * one being the mention `Hi @damien, could you read the new revision of the documentation?` linking to the comment?
> 
> 
> I would add a mention property to existing TLM (property could be structured), no? No backend developer talked to you about this issue?

This is possible but more "implicit" than a separate TLM with the `mention.created` type. The filter in the notification pane (`all`/`mention`) will also be less natural.

**Comment by PhilippeAccorsi** [comment]
Verified.
