### ISSUE TITLE
Bug: Cannot update a note with a mention to a user who does not exist (anymore)

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3722]
## Description and expectations

I have a note that contains a mention to a fictive user (that could also be a mention to a user that has left the space).

Updating the note is impossible without removing this mention, because it is rejected by the backend. It should be possible to edit a note that contains an existing mention without it being handled, it should be possible to add a mention to a non existent user.

Here's how we want to solve this:
 - [x] In the frontend, when loading a note, build the set of all the strings that look like a mention (`@something`, there is a regex for this in frontend_lib) - let's name this set `BEFORE_MENTIONS`
 - [x] save this list in the state of the editing component / the app (to be defined by the developer)
 - [x] when saving: 
     - [x] build the set of all the strings that look like a mention again (`AFTER_MENTIONS`)
     - [x] build `NEW_MENTIONS`, which is `AFTER_MENTIONS - BEFORE_MENTIONS`
     - [x] build `NEW_INVALID_MENTIONS =  (NEW_MENTIONS - the set of members of the space)`
          - [x] the set of members is ideally retrieved thanks to redux; maybe it is in the `config` prop of the HTML app. If it is not, either add this to the prop - it has the advantage of being updated in real time using the TLMs, or fetch the members from the API if this is too painful 
     - [x] if the `NEW_INVALID_MENTIONS` set is not empty, show a Confirm popup listing the new invalid mentions, letting the user decide if they are ok with these things that look like mentions not triggering actual mentions to real members. It should say something like "These mentions do not match any member of this space: {list}. Save anyway? [OK] [Cancel]".
          :warning: the list of members can change between the moment the popup is shown and the moment the user actually saves the document, which could lead to interesting bugs. A way around this could be to update the displayed member list while the popup is shown.

:warning:: the described operations are set operations, not list operations (duplicates in "lists" are removed).

## Work branch
`fix/3722__allow_invalid_mentions`

## Translation

|English|French|Portuguese|
|-|-|-|
|Your text contains mentions that do not match any member of this space:|Votre texte contient des mentions qui ne correspondent à aucun membre de cet espace :|O seu texto contém menções que não correspondem a nenhum membro deste espaço:|
|Validate anyway|Valider quand même|Validar de qualquer forma|
|Edit|Modifier|Editar|

## Discussed

 - the message shown in the popup

`Your text contains mentions that do not match any member of this space: {{list_of_mentions}}.`
` [Validate anyway][Edit]`

With the same UI that the popup of space deletion and the primary color of the instance.

 - whether the default action / call to action of the popup is cancelling the save or saving anyway.

default is "Modify"

### Discussed solutions

**Initially Chosen: option 2, after discussed we choose option 1 with the details at description**

1. Have a frontend check for each mention, if any of the new mentions is to an invalid user it is not surrounded by span and a popup appears, with a message like: "these mentions {{mentions_list}} does not match any member of this space and will not have any effect. Continue? [Cancel] [OK]"

Cons: Slows down content saving

2. Have a frontend check for each mention, if any of the new mentions is to an invalid user it is just not surrounded by span

Cons: Slows down content saving

3. Instead of sending an error, if the backend finds an invalid mention it adds a "not-member" class, the frontend does not highlight mentions with that class.

Cons: create useless span tags and increases coupling between the backend and the frontend

## Related issue

#3517 

## Abandoned idea

In the backend, silently ignore the invalid mentions. Ideally, list the invalid mentions in the response to the frontend so alternative clients can decide to design this feature using another way (we could imagine a client uploading a note and then showing to the user "warning, these mentions are invalid: {list}).

**Comment by PhilippeAccorsi** [comment]
I have seen the same problem today, and its very difficult to understand what is going on.

I hace search `@` in the note and find some mention but don't know which one is "broken". I have search if all user are member of this space and find one user missing (I know that this user is now deactivated on Tracim instance).

So I have tried to modified the mention like this to save note :
- ~~@tatatat~~ => not work
- "@tatatat" => not work
So
I remove all mention (@tititit @tototot etc.), save the note and edit again and add list of mention like this "@tititit @tototot etc.". Now I save again the note to not modify history of note.

I think many way can be explored to solved this issue:
- [ ] check the mentions just in all new lines added/removed in note
- [ ] like describe in this issue, add message with list of broken mention and give opportunity to save note without solve error.
- [ ] select all mention in error (with red color for exemple) to help user to find where error exist

This is very important for me to find a solution because you are very ungry when you whant to save document and you not find solution to solve the error.

**Comment by lebouquetin** [comment]
`s/This applies to notes and comments/This applies to modification of description field/.`

This is for example the case for file description.

Actually, it looks like you did not implement mentions for the file description, which is related to bad design (you link the mention process to a UI widget instead of a given property).

I expect this kind of fix to be related to a frontend widget / a property, not a type of content (otherwise we'll naver get a sdandardized user interface)

**Comment by raphj** [comment]
> Actually, it looks like you did not implement mentions for the file description

After internal discussion, we found out that is this most certainly a deliberate design choice that was made when implementing the feature.

This mechanism is implemented at one single place in the frontend and the fix will apply to any place in the frontend where this feature may be added in the future.

**Comment by PhilippeAccorsi** [comment]
I not know what is going on if I modify note (with some mention inside) and not add mention. Tracim send again mention ?

**Comment by gbonaspetti** [comment]
> the message shown in the popup

Suggestion: "The following mentions are for invalid users and will have no effect: {{list_of_mentions}}
Do you want to save the document anyway or go back to edit mode?
[Edit] [Save]"

Something like this: 
![Screenshot from 2020-11-27 11-39-58](https://user-images.githubusercontent.com/35422692/100440672-87bd4f80-30a5-11eb-8fc1-b76534e4dd09.png)


> whether the default action / call to action of the popup is cancelling the save or saving anyway.

For me it should be the cancel.

> I not know what is going on if I modify note (with some mention inside) and not add mention. Tracim send again mention ?

No, the user is not mentioned again. But when we allow save "invalid" mentions, each time that the user save the document the popup will show up.

**Comment by lebouquetin** [comment]
@gbonaspetti here is my suggestion of wording:

`Your entry contains mentions of unknown users: {{list_of_mentions}}.`

`[Modify] [Save anyway]`

My feeling is the color should be orange like a warning

**Comment by raphj** [comment]
- I'd put the title "Invalid mention" at the top of the box (no space before)
- I think both buttons should be close to each others (them being one at the left, one at the right looks odd to me, I've not seen this elsewhere)
- "edit" looks like a new action and does not look like it means cancel
- "These mentions do not match members of this space:"
- I'd remove the question and use the following buttons : "Cancel saving" and "Save anyway"

**Comment by raphj** [comment]
> My feeling is the color should be orange like a warning

I agree

**Comment by gbonaspetti** [comment]
> @gbonaspetti here is my suggestion of wording:
> 
> `Your entry contains mentions of unknown users: {{list_of_mentions}}.`
> 
> `[Modify] [Save anyway]`
> 
> My feeling is the color should be orange like a warning

@lebouquetin I'm ok with your suggestion. But orange is already the color of file contents, my idea is or use the color of the app that the user is trying to edit/comment or the primary color.

**Comment by lebouquetin** [comment]
> I'd put the title "Invalid mention" at the top of the box (no space before)

:+1: 

> I think both buttons should be close to each others (them being one at the left, one at the right looks odd to me, I've not seen this elsewhere)

This is relatively standard for `back` and `forward` meaning.

> I'd remove the question and use the following buttons : "Cancel saving" and "Save anyway" (edit: modify is good for me too)

I suggested `modify` but the real meaning I have is something like `correct my entry` (`rectifier ma saisie` en français)

**Comment by lebouquetin** [comment]
For the color, I think we should have a normalized color (same message in different applications = same color), that's why I suggest orange and not app primary color.

I understand the misunderstanding with app color; I think there is a rework to do for file application in order to avoid the misunderstanding of messages like that.

**Comment by gbonaspetti** [comment]
> For the color, I think we should have a normalized color (same message in different applications = same color), that's why I suggest orange and not app primary color.
> 
> I understand the misunderstanding with app color; I think there is a rework to do for file application in order to avoid the misunderstanding of messages like that.
> 
> What do you think?

I agree, maybe we can use the primary color (of the instance) for now and make an issue for a refactor of the colors.

**Comment by gbonaspetti** [comment]
Frontend part finished and approved, missing the backend part to merge (issue will return to To Do, the PR is https://github.com/tracim/tracim/pull/3932).

**Comment by inkhey** [comment]
With this PR, there is very few case where the backend will refuse due to invalid mention:
- frontend does not use <span> for invalid mention, so backend doesn't consider them
- backend does check previous mention before and check only new mention, so removing user from space will not cause issue.

So, it should appear only if a user explictly force <span> with invalid mention

The process of invalidation of mentions is done as trigger, so it's complicated to return the list of invalid mention to the user.

**Comment by raphj** [comment]
It could still happen though, if a member is removed from the space after the check but before the submission. Unlikely but possible because the operation is not atomic and cannot be.

If this is problematic, we then should silently ignore invalid mentions.

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
