### ISSUE TITLE
Feat: Improve messages mecanism to handle pre-join space events

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3824]
## Feature description and goals

Allow getting all or part of previous workspace events when joining a space, in order to avoid empty activity feed for new space members.

To do:
- [x] have a config parameter : `workspace.join.max_messages_history_count`  (-1 means no limit)
- [x] have a filter "include_not_sent" that allows including these events created after joining.
- [x] add events in a workspace join trigger that generate the last  `workspace.join.max_messages_history_count`  space messages for the user that has joined
  - do not send them and set them as read but not sent.
  - mark them as read (date = the workspace join time) (not marking messages as read would mess up the number of unread notifications)
 ## To be discussed

> should we set read to current datetime for newly created message ? (frontend will have to handle this case, so frontend should know the sent date which is currently not available in endpoint)

I do think yes for a first step. we will also not sent the "sent" information for a first step as this doesn't seems necessary and need some adaptation to handle current and previous messages with this cfange.

> should we have a symmetric mecanism with message deletion at workspace leaving (probably using hook on_user_role_in_workspace_deleted ?)

For a first step, i do think we can just skip this part and consider the deleting if really we do see some real need to.

> should we limit the number of old created event (i do suggest yes), which default value ? (i do suggest to stay with infinite by default but allow to limit in tracim configuration if needed).

Lets allow to limit this.

> Should we show `not_sent` event in notifications ?

Clearly depend on how frontend want to handle this. Best solution is allowing to filter on it but let the frontend his own decision there.

After some discussion with both @raphj  and @grignards, we though about a mechanism that will create messages for previous event at user members join:  https://github.com/tracim/tracim/issues/3824#issuecomment-728174579:

see https://github.com/tracim/tracim/issues/3824#issuecomment-728801525 for more technical details

## Implemented solution:
https://github.com/tracim/tracim/pull/3859
-  add a config parameter : `workspace.join.max_messages_history_count`  (-1 means no limit, 0 disable the feature, >0 limit the number of element to generate if needed) which allow to set the number of last space message in space to add at space join. it will add only the n items. If user has already them, it will not add them or add more.
- add a filter "include_not_sent" that add not_sent event to /messages endpoint, by default not_sent event (aka generated historic messages) are not included in /messages endpoints.
- add events in a workspace join trigger that generate the last  `workspace.join.max_messages_history_count`  space messages for the user that has joined, these historic messages are already mark as read and set to not sent (which allow distinguist them with normal messages)
- Fix issue related to autoflush in role creation during workspace creation
- Few fix related to pushpin tests.
- add frontend fix to use include_not_sent for space feed
--------

_Legacy ticket info (about /events endpoint):_
> 
> ### Context
> 
> When joining a space, a user has no chance of building the activity feed (#3600) using TLMs. Since they were not member of this space, they could not possibly receive them, leading to an empty activity feed on arrival. We therefore need to be able to retrieve events related to the space that happened before the user joined it. That is what this development shall address.
> 
> ### Description
> 
> To do:
>  - [x] add a endpoint `/events` that looks like `/messages`, possibly reusing most of the code. Instead of using `Messages`, this endpoint will query `Events`.
> 
> ## To be discussed before development
> 
> ### Is this endpoint mandatory?
> 
> Couldn't we create (but not send) the related messages when a user joins a space?
> In this case should we remove the related messages when a user leaves the space?
> What about of administrator messages?
> :warning: we should then provide a filter to `/messages` in order to only get messages after joining for the notification wall.
> 
> ### Should we not create a new endpoint and add the possibility to request events instead of messages in the `/messages` endpoint?
> 
> Arguments against:
> -  `/messages` offers to request only read / unread messages, which makes no sense for events, which cannot be marked as read. Moreover,
> - mixing both would mean that we do not always return the same object type depending on the request (notably, messages have a `read` field and events to not).
> 
> 
> ### How can we ensure that access rights are consistent?
> 
> The messages are created/sent to specified users, depending on their rights (profile, space membership). Currently the `messages` API naturally returns the correct events as it only returns the events which have a message for the given user.
> If we go for a separate event/allow to request "any" event in `messages` we have to ensure that the returned event match the access rights when creating/sending messages.
> 
> This could still be a possibility by either allowing to create a message +set its read date when an event without message is marked as `read` OR refusing to mark events without message as read.
>

**Comment by inkhey** [comment]
If we decide to recreate previous event when user join a space to avoid creating a new endpoint, we do need for the filter, to store the date of role creation for user in workspace, we do not store such information now.

**Comment by inkhey** [comment]
As far i understood the issue, the problem here is that we do not need user messages but space-related event.
Is there any good reason to get some old event for user which are not related to workspace ? Does a newly added administrator for example, should be able to get some previous event unrelated to any space ?

So, i do suggest:
- personal feed is `/api/users/{user_id:\d+}/messages`  based and updated with TLM
- workspace_event feed is `/api/workspaces/{workspace_id:\d+}/events` based and updated with TLM with workspace provided

We do need also to clarify if we want personalization on both of theses feed and how.
If we do expect personalization later at endpoint level, i do suggest to change  `/api/workspaces/{workspace_id:\d+}/events` and use  `/api/users/{user_id:\d+}/workspaces/{workspace_id:\d+}/events` insteand

**Comment by grignards** [comment]
Yes an endpoint for spaces' events can work.

**Comment by raphj** [comment]
We might want to call the endpoint as follows if we go this route (no pun intended):

- `/api/workspaces/{workspace_id:\d+}/messages`

`messages` might be both less correct and less confusing for the API user. Either way, I don't have a strong opinion on this.

**Comment by raphj** [comment]
What do you mean by "with TLM with space provided" by the way? live messages should never be involved here. Messages (or even Events), yes

**Comment by inkhey** [comment]
> What do you mean by "with TLM with space provided" by the way? live messages should never be involved here. Messages (or even Events), yes

The endpoint is used to get the list at time T. in ui, we should use TLM to update it interactively, despite object returned are not exactly the same, It's not perfect but this look the best solution (creating multiple SSE feed or pushing different kind of data in TLM feed is not a great idea).

**Comment by raphj** [comment]
Do you confirm that by TLMs, you mean messages?

For me, TLMs are restricted to what `/live_messages` outputs. `/messages` outputs messages that are not "live" (so, they are not TLMs).

If so, I agree.

**Comment by lebouquetin** [comment]
I do not understand. We plan to have a user based activity feed. If this feed is filled from events, then we need a generic /events endpoint, not a space-related endpoint (otherwise, my interface will require plenty of requests for filling-in my activity feed)

**Comment by inkhey** [comment]
After discussion with @grignards, @lebouquetin and @raphj , we get to the point that:
- futur user feed should be an aggregate of all user workspace feed by default and having a workspace based endpoint is too restrictive for this.

So, https://github.com/tracim/tracim/issues/3824#issuecomment-726003310 solution is not good, we should find another solution.

We do see with @raphj  and @grignards , 2 main solutions:
1. Have a /events endpoint with similar filter as /messages to get all events it should have access. This is a bit tricky as we do need to redo the privacy mechanism but in the other side ( instead of checking which messages should be created for which person, we do check which event should mean a message creation).
2. Create "not send" messages  at  user members add (should be read by default ?), we do create message for previous event with the similar code as existing but do not send them to pushpin, we need to note them as explictly not sent in order to allow ui to know that these are message that user does not receive at all (and have proper treatment on it).

After some discussion, it's seems that the solution 2 seems a good approach if we can have some mechanism to limit the previous event message creation (just save something like 100 old messages, this way we ensure most of the time that feed is not empty and we do not create a huge amounts of messages. This permit also to reuse most of the current mechanism. This limit may be a configuration parameters of tracim.

**Comment by inkhey** [comment]
About the solution 2:
It mean : 
1. having a method similar to  `_publish_messages_for_event` which : 
  - create message object
  - set sent as None (sent is always set in current process, so we can rely on it for this case)
  - limit to only one given user if user_id given is in the list of valid user id
  - check if the message already exist in database (event_id, user_id)
  - do not send message to pushpin.

2. use this method on trigger on `on_user_role_in_workspace_created` which:
 - will select all or configurable limited number of last event on workspace.
 - will process the user message creation for each of these events if user is allowed to using  `_publish_messages_for_event`  like method.

3. Endpoint /messages will return message for old event and workspace, so field should not being empty at start on workspace, we can adjust the number of old message to generate in order to avoid creating too much stuff.

Unclear point:
- should we set read to current datetime for newly created message ? (frontend will have to handle this case, so frontend should know the sent date which is currently not available in endpoint)
- should we have a symmetric mecanism with message deletion at workspace leaving (probably using hook `on_user_role_in_workspace_deleted` ?)

**Comment by grignards** [comment]
Do not forget the `include_not_sent` (or whatever) parameter which will allow the activity feed to get those messages while allowing the notification panel to not get them (provided we want to keep the current behavior of the notification panel to be empty when a user joins a space).

> Unclear point:
> 
>     * should we set read to current datetime for newly created message ? (frontend will have to handle this case, so frontend should know the sent date which is currently not available in endpoint)

If think we can but it shouldn't have any consequence if the notification panel does not use `include_not_sent`.

>     * should we have a symmetric mecanism with message deletion at workspace leaving (probably using hook `on_user_role_in_workspace_deleted` ?)

I do not have a strong opinion on this: theoretically it is cleaner but we don't gain much in this case. We also do not lose anything as long as we only remove unsent messages.

>     * should we limit the number of old created event (i do suggest yes), which default value ? (i do suggest to stay with infinite by default but allow to limit in tracim configuration if needed).

If we'd like to fill one page of activities we need 15 activities. We cannot directly compute a minimum on messages for this as activities do not have a predetermined cardinality with messages (the relation is *1-n* with a varying *n*). So I agree to create all messages unless a configuration bounds it.

**Comment by inkhey** [comment]
proper testing the PR can only be done at API level, unless you tweak the code or the frontend request to set include_not_sent=1 in /messages query:
https://github.com/tracim/tracim/pull/3859

**Comment by PhilippeAccorsi** [comment]
Done.
