### ISSUE TITLE
Bug: Link at frontend_lib causes white page using servdev

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3999]
## Description and expectations

`frontend_lib/helper.js` and `frontend_lib/PageTitle.jsx` have _Link_ imports, but `frontend_lib` is not inside the _Router_, this causes some errors like `Error: Invariant failed`, `The above error occurred in the <Context.Consumer> component`, `Cannot update during an existing state transition (such as withinrender). Render methods should be a pure function of props and state.`, when using servdev.

### How to reproduce

1. Activate servdev
2. At your browser go to a space's dashboard

### Version information

- Tracim version: at least v3.4.1
- Web browser: at least Google Chrome
- Device / System: PC

________________________________________________

**Comment by Skylsmoi** [comment]
The general issue is about having different instances of react-router-dom in the project.

I have tested:
- passing the link component as parmeter where it is required
- with and without putting react-router-dom in forntend_vendor
- removing the call to frontend_lib and frontend_vendor in the index.html of servdev
- simplifying the app to the maximum by only calling Breadcrumb component in frontend/src/index.js
  - even removing every other HOC from frontend/src/index.js

None of this worked.

Side note: importing Breadcrumbs directly through `tracim_frontend_lib/src/component/Breadcrumbs/Breadcrumbs.jsx` worked. Which is obvious because there isn't any external library in that case.

**Comment by Skylsmoi** [comment]
Solution that works (currently without any apps included in Tracim, only frontend_lib and frontend):

In frontend_lib, setting react-router-dom as an external dependency.

This is the case by the `.external` key in `frontend_lib/webpack.config.js` for the `standalone` build and by putting it in the frontend_vendors bundle (adding 'react-router-dom' in `frontend_vendors/src/index.js`) for the `optimized` build

That way, there always is only once instance of react-router-dom which is:
- for standalone build: the one in frontend/
- for optimized build: the one in frontend_vendors/

This working solution hasn't been tested with apps yet.

**Comment by Skylsmoi** [comment]
List of others fixes done during investigation:
- use BrowserRouter instead of Router in frontend/
- remove any import and usage of react-router, only use react-router-dom
- removed unused `optimized-dev` case from frontend_lib/build-script.sh
- fixed frontend_lib/build-script.sh error output to standard output instead of redirecting error to standard
- removed .dev extension in frontend_lib builds that where never used
  - because, in package.json, the main property is `tracim_frontend_lib.lib.js`
- homogenized react-router-dom version number to 5.2.0 in every folders

**Comment by Skylsmoi** [comment]
## To work
### 1) working in frontend
#### 1.1) with frontend servdev
    yarn run servdev
you must have run `build_full_frontend_standalone.sh` once and once each time apps are modified (by git pull for example)
server will update automatically on change

#### 1.2) with pushpin
    yarn run buildoptimized
or

    yarn run buildoptimized-dev
redo on each change

### 2) working in apps:
#### 2.1) with app's servdev
    yarn run servdev
server will update automatically on change

##### When the app is ready to be tested in frontend
    yarn run build
or

    yarn run build-dev
then

    cp dist/[appName].app.standalone.js ../frontend/dist/app/[appName].app.standalone.js
redo both on each app's change
todo: have a script that handle 

#### 2.2) With pushpin
    ./build_[appName].sh
or

    ./build_[appName].sh dev
redo on each app's change

### 3) Working in frontend_lib
#### 3.1) When working with the servdev of frontend or of any app
build frontend_lib

    yarn run build
or

    yarn run build-dev
your servdev will update automatically when frontend_lib build is ready

#### 3.2) When working with pushpin
build frontend_lib

    yarn run buildoptimized
or

    yarn run buildoptimized-dev

##### 3.2.1) if your are working on frontend, rebuild the frontend

    yarn run buildoptimized
or

    yarn run buildoprimized-dev

##### 3.2.2) if your are working on an app, rebuild the app

    ./build_[appName].sh
or

    ./build_[appName].sh dev

**Comment by Skylsmoi** [comment]
For manual tests:
- Check some app's servdev (don't forget to update debug.js)
- run build_full_frontend_standalone.sh then run frontend servdev and check it works fine
- in the frontend's servdev, open an app feature for a content and check that the breadcrumbs is well updated
- check the breadcrumbs for some other pages

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.

**Comment by Skylsmoi** [comment]
see https://github.com/tracim/tracim/issues/4894 for evolution, update spec from my last comment when done

and add this spec in a tracim's readme
