### ISSUE TITLE
Feat: Add "personal page" at public profile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4039]
## Feature description and goals

- [x] Add a free field, using TinyMCE.
- [x] An administrator is allowed to edit the information of any user.
- [x] When the user/administrator clicks on edit, only the selected part switches to edit mode.
- [x] When the user/administrator clicks to confirm, the selected part returns to the view mode with the changes made.
- [x] Update loading screen if necessary
- [x] Changing the language must refresh content (since translations comes from backend)

## Translations

|English|French|Portuguese|
|-|-|-|
|Personal Page|Page personnelle|Página pessoal|
|Edit|Éditer|Editar|
|Confirm|Valider|Confirmar|

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

- Public profile of the logged user

![public_profile_before_edit](https://user-images.githubusercontent.com/35422692/100880595-33530f00-34ad-11eb-9d6a-a72a701e9ec8.jpg)

- Public profile of the logged user in edition mode

![public_profile_after_edit](https://user-images.githubusercontent.com/35422692/100776027-4fe73c80-3404-11eb-83ab-d37e8d3466ed.jpg)

- Public profile of other user and menu details

![public_profile](https://user-images.githubusercontent.com/35422692/100880616-3817c300-34ad-11eb-9753-42af8e06aafc.jpg)

## Prerequisites

- #3829 

## Time Estimation
2 man/day (using JSONSchema as CustomForms)

**Comment by grignards** [comment]
From what we discussed last week the personal page field will be stored as a custom user property (see #2935). What is left to decide is whether the frontend uses the property's name to display it as a personal page or will it use a `ui` parameter to indicate which property is the "main" one.
I would be in favor of using a `ui` parameter, for example `tracim:display_attributes`:

```json
{
  "personal_page": {
    "tracim:display_attributes": ["profile_main"]
  }
}
```

**Comment by Skylsmoi** [comment]
added blocked by backend because waiting for this issue to be done https://github.com/tracim/tracim/issues/2935

**Comment by PhilippeAccorsi** [comment]
> added blocked by backend because waiting for this issue to be done #2935

I remove "blocked by backend" because issue is done.

**Comment by asf-algoo** [comment]
> Following what we discussed last week the personal page field will be stored as a custom user property (see #2935). What is left to decide is whether the frontend uses the property's name to display it as a personal page or will it use a `ui` parameter to indicate which property is the "main" one.
> I would be in favor of using a `ui` parameter, for example `tracim:display_attributes`:
> 
> ```json
> {
>   "personal_page": {
>     "tracim:display_attributes": ["profile_main"]
>   }
> }
> ```

the ui parameter name is `tracim:display_group`. And the frontend expects the 2 possible values: `public_profile_first` for the Information part and `public_profile_second` for the Personal page part

**Comment by Skylsmoi** [comment]
### handled react json schema feature for the renderer CustomFormManager.jsx
    Note that we parse the dataSchema, not the schema
The list of features is taken from here https://rjsf-team.github.io/react-jsonschema-form/
- :heavy_check_mark: simple (DisplaySchemaPropertyString)
- :heavy_check_mark: nested (DisplaySchemaArray for a list of objects)
- :heavy_check_mark: array (DisplaySchemaArray for a list of strings)
- :heavy_check_mark: number (DisplaySchemaPropertyString)
- :heavy_check_mark: widget (DisplaySchemaObject > DisplaySchemaPropertyString)
- :heavy_check_mark: ordering (DisplaySchemaPropertyString)
- :x: reference
  - not handled
  - need to handle the $ref in schema related to value we give to DisplaySchemaPropertyString
- :heavy_check_mark: custom (DisplaySchemaPropertyString)
  - since its called "customs" I'm not sure it handles every possible cases
- :heavy_check_mark: errors (nothing to handle)
- :mag_right: : examples
  - doesn't work in playground, should not have anything to handle though
- :heavy_check_mark: large (DisplaySchemaPropertyString)
- :heavy_check_mark: date and time (DisplaySchemaObject > DisplaySchemaPropertyString)
- :heavy_check_mark: validation
  - nothing to handle
- :x: files
  - not handled, it returns a b64 encode
- :mag_right: single
  - :x: not handled at schema root. DisplaySchemaObject expects an object, not a string
  - :heavy_check_mark: handled in nested properties
- :mag_right: custom array
  - :x: not handled at shema root. DisplaySchemaObject expects an object, not an array
  - :heavy_check_mark: handled in nested properties
- :heavy_check_mark: custom object (DisplaySchemaObject)
- :heavy_check_mark: alternatives (DisplaySchemaObject into any)
- :heavy_check_mark: property dependencies (DisplaySchemaObject > DisplaySchemaPropertyString)
- :heavy_check_mark: schema dependencies (DisplaySchemaObject > DisplaySchemaArray > DisplaySchemaPropertyString)
- :mag_right:  additional properties (DisplaySchemaPropertyString)
  - partially supported: properties will be displayed as in separated properties, not related
    - this means they will be one bellow the other, not on the same line
- :mag_right:  any of (DisplaySchemaPropertyString)
  - partially supported: won't display the section's title
- :mag_right:  one of (DisplaySchemaPropertyString)
  - partially supported: won't display the section's title
- :mag_right:  all of (DisplaySchemaPropertyString)
  - partially supported: won't display the section's title
- :heavy_check_mark: null field (DisplaySchemaPropertyString)
  - nothing to do
- :heavy_check_mark: nullable (DisplaySchemaPropertyString)
  - nothing to do
- :heavy_check_mark: error schema (DisplaySchemaPropertyString)
  - nothing to do
- :heavy_check_mark: default
  - nothing to do, the default value is for the form. If the user remove it, it will save the removal as ""


#### Additional features
- :heavy_check_mark: boolean value (DisplaySchemaPropertyBoolean)
- :heavy_check_mark: Text rich. It uses tinyMCE in a custom widget (TextRichWidget)

**Comment by Skylsmoi** [comment]
To test each features:
- reset your user's custom property in database using

    `sqlite3 path/to/tracim.sqlite "update user_custom_properties set fields='{}'"`

- go to [react json schema form](https://rjsf-team.github.io/react-jsonschema-form/)
- select the feature you want to test
- copy each json in its respective .json file in backend/examples/user_custom_properties/organization/
  - JSONSchema in `schema.json`
  - UISchema in `ui.json`
- restart your backend server and refresh your browser's page

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
