### ISSUE TITLE
Lint code : command line “flake8“ killed“ ?

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4249]
**/// TEST ENVIRONMENT ///**
Machine : remote VPS 2vCore
OS distro : Ubuntu 18.04 (bionic beaver)
User :  root with sudo permissions
Web server : apache 2.4
Cpanel : ISPConfig 3.2.2

Hello,

**/// NOTE ///**
I was advised to post any further issue in the same thread, but I observed that doing so, my questions are not replied (or are replied many days later…) !

**/////// BUG DESCRIPTION ///////**
I can now connect my Tracim instance, login and logout without issues.
**However, there was none output for command line “Flake8“** (last one before connexion), until **I pressed twice the button enter:**

- first output : **killed**
- second output : cursor ascended back within the **backend directory**

**/////// HELP REQUIRED ///////**
What could be the reason why was “Flake8“ command line killed ?
Does it or not matter for if using Tracim for production ?

Regards,

**Comment by lebouquetin** [comment]
@Keepshango could you please use the bug report template we defined in order to report questions/bugs/issues?

> I was advised to post any further issue in the same thread, but I observed that doing so, my questions are not replied (or are replied many days later…) !

If you are in a hurry, we can offer professional support. If you are interested, please [contact us by email](https://www.algoo.fr/fr/contact?context=algoo).

Be sure we do our best in order to help you.

Please notice that `flake8` command is not required for Tracim installation. There is probably something not clear in the documentation.

**Comment by Keepshango** [comment]
> If you are in a hurry, we can offer professional support. If you are interested, please [contact us by email](https://www.algoo.fr/fr/contact?context=algoo).

Fine, but for now time is on my side, and only very few installation issues remains, before I can concretly test Tracim in production.

That said, when an issue not compares another, it seems more efficient to me to post one issue per thread.


> Please notice that `flake8` command is not required for Tracim installation

Thanks !
