### ISSUE TITLE
Feat: Handle preview for links to pictures

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4439]
## Feature description and goals

Linking a JPG/PNG/GIF image  in a comment does not currently trigger the link preview. We may want to show a preview of the image. This can be tricky:
 - the links do not always bear a familiar file extension
 - we should avoid trying to download the whole picture

There is probably some processing to do in the backend.

## Implemented solution
- use improved version of webpreview which allow to limit the size of response we do accept.
- limit webpreview generation if content_length > 1mo
- add code to handle direct image.

PR ref: #5439
issue ref: #4439

**Comment by inkhey** [comment]
We may imagine that if the backend read the content-size and content-type and decided to process on these two parameters.
It's far from perfect but i don't see any other good solution to avoid download too big file or wrong content.

**Comment by inkhey** [comment]
Currently the mecanism doesn't cache image, it's only the link to the image that is cached here (all element necessary to generate the preview). The webpreview lib doesn't look to support non-html page, 
so potential solution may be :
- Propose a fix to webpreview to handle this and check content-type .
- Doing a HEAD request before running webpreview or returning a custom preview if file is itself an image

**Comment by raphj** [comment]
I'm speaking about resizing (reducing the size) of the picture in the backend.

**Comment by inkhey** [comment]
Did some try on this. Some thought:
- Frontend doesn't return any element with empty title or description.
- There is no easy way to use `webpreview` with the content of the url instead of the url itself (which may help us to avoid doing multiples requests instead of one).
- I do suggest return filename (obtained for content-disposition at first and url as fallback) as title.
- description for image doesn't make much sense. Have you any idea ?
- size may be a great information to have for non html page file, if we do provide it maybe we should have preview links systematically (icon fallback support ?)
- resizing the picture image mean store a copy of the original image, which should be accessible through api, this is not so easy and raise many questions.
- If we do store image preview for image file, i suggest to do the same for all link return by the webpreview mecanism.
- if we do store image preview for image file, we can decide to do preview for non-image format too, so using preview-generator is the way to go.
- If we do store image preview for image file we should have a limit to which we do add the image preview. Doing requests "stream" get query permit to obtain header without loading the full content. Having name/size without preview seems acceptable.

**Comment by inkhey** [comment]
For a first step, i suggest this:

- get the image check the content-type.
- if content-type is html, do same stuff as currently
- if content-type is image file (only some mimetype ?) and smaller than a define size, generate preview with original image link.
- else no preview.

**Comment by inkhey** [comment]
Tried a poc there: https://github.com/tracim/tracim/pull/5439

**Comment by inkhey** [comment]
another bug with image preview in link (should probably be fixed at the same time) : https://github.com/tracim/tracim/issues/4812

**Comment by grignards** [comment]
Is is a bit unfortunate that two requests are done in the nominal case (preview of an html link) :-/
But I do not see a way out of this apart from contributing to `webpreview` so that it supports streamed requests.

**Comment by inkhey** [comment]
> Is is a bit unfortunate that two requests are done in the nominal case (preview of an html link) :-/ But I do not see a way out of this apart from contributing to `webpreview` so that it supports streamed requests.
> 
> BTW a `HEAD` request should be enough to get the required headers.

The reason to do stream request is to avoid doing 2 request in the image case.

**Comment by inkhey** [comment]
According to discussion with the tracim team, decision has been made to check how to improve the webpreview library in order to fill our need.

**Comment by charline-rageade** [comment]
need bug correction

**Comment by inkhey** [comment]
To test this:
- test with big content ( > 1mo), you should not have image preview for theses
- test with image direct link (< 1mo), you should get title, description and image (title = description because frontend need description) see https://github.com/tracim/tracim/issues/4574
- test with standard case: http page link which create proper link preview e.g github issue page.

**Comment by knodelle** [comment]
done
