### ISSUE TITLE
Bug: you can react (emoji) on a non-editable content

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4511]
## Description and expectations

You can react with an emoji on a non-editable content (obsolete/validated/...), even if you can react with a comment. 
For consistency, at a minimum, the API must refuse.

Frontend issue: https://github.com/tracim/tracim/issues/4456

### Version information

- Tracim version: v3.8
- Web browser: Firefox
- Device / System: PC

________________________________________________

## Prerequisites

None

**Comment by inkhey** [comment]
I'm not sure what to do with this ticket in backend.
Backend currently does not unallow to edit a non-editable content at all.
The reason to not doing this in backend as far i remember are:
 - make it easier to change the behavior as many solutions about what is allowed or not can make sense. 
 - status of content are expected to be configurable per content type, so the behavior may diverge between two content type.
 
There was not much work/thinking on theses subjects since the beginning of tracim v2 as far i know.

**Comment by Sarah-Pelle** [comment]
Won't fix
