### ISSUE TITLE
Feat: Configuration of authorized document extensions in collabora

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4713]
## Feature description and goals

Add settings for authorized document extensions in collabora.

- [x] Add backend setting
~~- [ ] Update `PopupCreateOfficeDocument.jsx` (and/or other components) to take into consideration this settings.~~ => Not needed, the required filtering is done in the backend.

## Prerequisites

None

## Implementation

- [x] add a `collaborative_document_edition.enabled_extensions` setting in `development.ini`: a list of file extensions which, if defined, will be used to filter `/api/system/config.collaborative_document_edition.supported_file_types.`
- [x] the filter will be done in the `CollaborativeDocumentEditionLib.get_supported_file_types` method
- [x] the original `CollaborativeDocumentEditionLib.get_supported_file_types` (abstract) will be renamed to `_get_supported_file_types` (also in the current implementation in `CollaboraCollaborativeDocumentEditionLib`).

**Comment by inkhey** [comment]
Our current implementation return both mimetypes and file extension, so filtering by file-extension may not be the logical mecanism, as collabora-online 4+ discovery endpoint is mimetype based.
In one side, mimetype is more explicit than file-extension.
in other side, collabora online 6 seems to have change the discovery endpoint to be extension based leading to some weird result in tracim config endpoint (but without breaking feature due to compatibility code in collabora).

**Comment by grignards** [comment]
> Our current implementation return both mimetypes and file extension, so filtering by file-extension may not be the logical mecanism, as collabora-online 4+ discovery endpoint is mimetype based.
> In one side, mimetype is more explicit than file-extension.
> in other side, collabora online 6 seems to have change the discovery endpoint to be extension based leading to some weird result in tracim config endpoint (but without breaking feature due to compatibility code in collabora).

I wrote https://github.com/tracim/tracim/issues/4733 to take care of this potential problem.

**Comment by MariePrandstetter** [comment]
tested on branch
