### ISSUE TITLE
Bug: Flash messages when switching between spaces

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4946]
## Description and expectations

Switching between spaces causes some flash messages sometimes. Like "Warning Error while getting the reaction list".

### Version information

- Tracim version: v3.10
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Diagnostic

Possible that it's linked to old information that stays on Redux.

## Prerequisites

None

## Linked PR
#5718

**Comment by Skylsmoi** [comment]
### to reproduce
- open space A dashboard
- open space A content list
- move a content to space B
- open space A dashboard
- the error appear

If you first load the content list and then move the content without having already loaded the dashboard, then the redux state worspaceActivity is empty and will load properly.
If you already have load the dashboard (which is the default page when clicking on a space in the sidebar) and then move the content, the activity list will first render BEFORE the action reset/activitylist witll be fired and the error will display (because it will load the reactions of a content url that doesn't exists because it has a wrong space id in the url).

**Comment by gbonaspetti** [comment]
https://github.com/tracim/tracim/issues/3556

**Comment by Skylsmoi** [comment]
What ever the solution we come up with to fix this issue, it is always dependent on a TLM to properly update the reducer activityList (which is currently never updated through any content modification action).

Problem is, there is this issue: https://github.com/tracim/tracim/issues/3556

So we cannot handle every cases whatever we do until the above issue is fixed.

Only current solution is to remove the error handling of the endpoint for the reactions to avoid displaying a flash message.

**Comment by Skylsmoi** [comment]
Solution implemented is to remove the flash message when the emoji reaction are loaded.

This works because the issue is that dashboard will load recent activity from redux right before it is reset.
So it render a first time with outdated data, fail to load the reactions, then redux is reset and activity list is loaded again properly

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
