### ISSUE TITLE
Bug: its not possible to edit publication and remove mention (error 500)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4972]
## Description and expectations

I have created a publication and after seeing an error about mention I tried to edit my publication and remove de `@` before the name.

Text before modification `tatata ... @myriam et @mathis`.
Text after modification `tatata ... myriam et mathis`

When I validate my modification, I can seen this error
~~~
Erreur
[object Object]
~~~

In devtool I can seen 
~~~
500 Internal Server Error
~~~
And detail of error
~~~
{
	"details": {
		"error_detail": {}
	},
	"code": 2067,
	"message": "This user is not a member of this workspace: athis"
}
~~~

### How to reproduce

- create a publication with mention of user present in the space
- edit publication end remove the `@`
- save the modification
=> error 500 appear

### Version information

- Tracim version: v3.9.2 build 055 (commit `d97ac550af` )
- Web browser: firefox
- Version: 92.0
- Device / System: Ubuntu 20.04

## Related PR
PR #6058

**Comment by Skylsmoi** [comment]
I have encountered the issue and adding some intel:
The issue is about modification of a comment or publication.
When editing, the mention detection has some issues separating words.

If I edit a comment and add a mention:
first version "@ someone1 can you do this?"
edited version "@ someone1 @ someone2 can you do this?"
(I'm adding spaces after @ to avoid mentionning someone in github)
the sent mention is @ someone1someone2
