### ISSUE TITLE
Perf/UX: POST file is very long because preview-generator usage is synchronous

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#4988]
## Description and expectations

I'm currently posting a lot of files with [trsync software](https://github.com/buxx/trsync) and I notice a very long response time of each post.

On the following picture, the first red zone is a log about posting a file (response is very long). The second red zone show libreoffice process on the Tracim host server which use 100% of CPU.

![2021-10-07_12-05](https://user-images.githubusercontent.com/1104637/136364779-799ef1ce-af70-43c6-95fd-c53b9a3a4f63.png)

A first diagnostic is the following: When file is posted on Tracim, event is generated. The event contains information about file (like page count, if there is pdf preview, etc).

![2021-10-07_12-03](https://user-images.githubusercontent.com/1104637/136366317-6387271e-7fc9-4cd5-bb36-5fce62c0d034.png)

It is probable that computing this information at file creation is synchronous and explain long time post response.

Note that a big .doc or pdf file which increase the response time.

### How to reproduce

Upload a .doc file on Tracim and watch host processes.

### Version information

Tracim 3.8.2

________________________________________________

**Comment by inkhey** [comment]
About this kind of problem, i think we should consider splitting the preview logic from the content endpoint, this a some drawback (need to call more endpoint for the frontend), but also some advantages (don't need to generate preview were not needed).

**Comment by grignards** [comment]
The reasoning behind @inkhey comment:
- avoiding the lenghty POST means that it shouldn't return attributes generated by the preview computing (as @buxx noticed).
- if those are removed this is a breaking change in the API => work is needed in the frontend to handle it

So directly separating the content and preview attributes is not really more time-consuming than an asynchronous preview generaton for instance.

@charline-rageade @lebouquetin Solving this issue seems to be time-consuming.

**Comment by grignards** [comment]
This issue is duplicated by #5495 and is solved by its fix which was shorter than expected when I wrote the previous comment.
