### ISSUE TITLE
Feat: merge the main header with the sidebar

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5111]
## Feature description and goals

A good idea to make better use of vertical space, reduce the number of headers and make the interface cleaner would be to merge the main header and the sidebar.

### Interface proposal and specifications

![Capture d’écran de 2022-07-28 11-04-32](https://user-images.githubusercontent.com/35422692/181467102-c6658773-64bf-465b-99ba-c246c4048513.png)
![Capture d’écran de 2022-07-28 11-04-41](https://user-images.githubusercontent.com/35422692/181467098-e3af3685-de36-40f7-bc66-48195cd5cbd2.png)

## Prerequisites

None

## PR

#5805

**Comment by Haskaris** [comment]
I love this design, with this sidebar we definitely gain some space! Without contrast (black and white like we got today), it even allows us to think a day/night theme
I'm wondering tho, have you thought about smartphone display? (if you already thought about it)
Because the (big) majority use their smartphone vertically, I'm affraid a vertical sidebar on smartphone will be rough and leads to a lack of space... Maybe put the sidebar on the top/bottom (only on smartphone) would allow user to gain some space

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by Millefeuille42** [comment]
Done
