### ISSUE TITLE
Feat: allow to create annotations on file previews (thinking and estimation)

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5570]
## Feature description and goals

The purpose of this issue is to do a reflection and estimation of a new functionality.

The functionality itself is to be able to make annotations on previews, similar to the library [react-picture-annotation](https://github.com/Secretmapper/react-image-annotation).

We would have around three different colored shapes.
It should be a mode that you can activate or not through a tab, similar as tag and share tabs.

In the tab, we should have something like [react-picture-annotate](https://github.com/UniversalDataTool/react-image-annotate).
A list of annotations, a way to display it or not, etc.

Concerning the model, an annotation is a commentary, linked to a geographical form with a specific revision. This way we can display the information that the annotation may be not relevant.
When adding a new revision, we have to ask if we want to duplicate every annotations.

## Prerequisites

None

**Comment by inkhey** [comment]
Point to clarify:
- Annotation associated to ? : 
  -  a content (consistency issue by looking at older revision)
  -  a revision (can we still add annotation to an older revision ?)
- Annotation are  ? : 
  - content (special comment case ?)
  - something specific (like reactions)
  - properties of content (simplify some things but cause a lot of revisions !)

**Comment by inkhey** [comment]
### Proposal 1: annotation are link between a content and a comment

#### image_preview_annotation table:

content_id: (of the original content)
revision_id (of the revision we do annotation of the original content)
comment_id (add text metadata to the annotation)
comment_revision_id (specific revision for the annotation, make sense ?)
location_x: % (precision?)
location_y: % (precision?)
shape: ... (to clarify)
created: datetime
updated: datetime
author: user_id

```
content -> revision 1
 ^         revision 2  <__ image_preview_annotation 20% x , 42% y, cercle 5%
  \                              |
   \                             v
    \------------------- content(comment) __> revision 3
```

#### TODO backend:
- add image_preview_annotation table and model in tracim
- add endpoint get all content annotation: GET /api/workspaces/{workspace_id}/contents/{content_id}/image_preview_annotation
- add endpoint get one content annotation: GET /api/workspaces/{workspace_id}/contents/{content_id}/image_preview_annotation/{annotation_id}
- add endpoint creation annotation: POST /api/workspaces/{workspace_id}/contents/{content_id}/image_preview_annotation
- add endpoint modify annotation: PUT /api/workspaces/{workspace_id}/contents/{content_id}/image_preview_annotation/{annotation_id}
- add endpoint deletion annotation DELETE /api/workspaces/{workspace_id}/contents/{content_id}/image_preview_annotation/{annotation_id}
- adjust deletion of all user item : deletion annotation too
- add specific tlm

### To clarify:
- are annotation without related comment make sense ? (if not we should find some way to link theses notions
- are annotation with file instead of comment make sense ?

### Proposal 2: annotation are comment with specific metadata:

#### content_revisions table
parent_id: (of the original content)
content_id: (of the annotation/comment content)
revision_id: (of the annotation/comment content)
properties: { "original_parent_revision_id":"" ,"image_annotation": {"location_x": "location_y": , "shape": } }
...

all changes are done in properties ?

#### TODO BACKEND:
- add filter to get only comments with/without annotations:  /api/workspaces/{workspace_id}/contents/{content_id}/comments?with_annotation=1
- add optionals annotations params to :
  - PUT /api/workspaces/{workspace_id}/contents/{content_id}/comments/{comment_id}
  - POST /api/workspaces/{workspace_id}/contents/{content_id}/comments
- update comment tlm with annotation informations
#### To clarify:
- we can decide to make an associate table instead to store specific data but this look like more complications for now, maybe for a rapid poc, using
properties field can be a temporary solution ?

**Comment by inkhey** [comment]
Some pro of proposal 2:
- having the information of original_parent_revision_id for normal comment may be nice too, we currently obtain it with timestamp but this is not the most accurate solution. Also we can decide having a similar logic about warning non-last revision annotation.
- updating the comment with annotation may automatically modified the original_parent_revision_id, we can deal with this with a sort of "verification step" which is done by just clicking on a check button.

some cons of proposal 2:
- using properties object may make filtering on annotations costly if there are a lot of comments in a content. If we do want to avoid performance issue we do at least need to have a way to distinct comment and annotations without relying on json fields.

**Comment by Haskaris** [comment]
## For the frontend part
#### Endpoint/TLM required
- A way to retrieve every annotations of a file
- A way to CRUD one annotation of a file

### Functionalities
We need these several modes
- Create
  - If no form selected, square by default, over wise will draw the selected form
  - Now either drag and drop, either two clicks to draw:
    - First mouse down will start the annotation drawing
    - First mouse up will end the annotation drawing
  OR
    - First click of the mouse will start the annotation drawing
    - Second click of the mouse will end the annotation drawing
- Update
  - Select the annotation
  - Now you should be able to:
    - Change the form by extension (little square that you drag and drop)
    - Change the commentary
    - Delete the annotation
To simplify the utilization we can add a mode (button) to delete an annotation

### With backend proposal 1
- Connect TLMs

### With backend proposal 2
- CRUD an annotation is done by modification of the comment

### TODO without using any library **(4.75 - 6.25)**
- Create separated tabs/menu **(0.25)**
- Create an Annotation component **(3.25 - 4)**
  - Change shape (square/circle) (0.25)
  - Change color (0.25)
  - Connect TLM / Modify a comment (0.75)
  - Draw the shape (1)
  - Move the shape (1)
- Create the history/annotation tab **(1.25 - 2)**
  - Display a list of every annotation (0.5)
  - Display the commentary linked to an annotation (0.5)
  - Display/hide an annotation (0.25)

**Comment by Haskaris** [comment]
The choice is to create a POC

For the frontend part:
We will use the library [react-picture-annotation](https://github.com/Secretmapper/react-image-annotation) to "create" the AnnotationComponent

**Comment by lebouquetin** [comment]
The label of this issue should better be *Feat: allo to create annotations on file (previews) (thinking and estimation) * what do you think @gbonaspetti 

@inkhey you did not take pagination into account in your design - this would be mandatory

**Comment by gbonaspetti** [comment]
Yes, you are right, notes is confusing with the note type

**Comment by inkhey** [comment]
> The label of this issue should better be *Feat: allo to create annotations on file (previews) (thinking and estimation) * what do you think @gbonaspetti
> 
> @inkhey you did not take pagination into account in your design - this would be mandatory

Ah if you are referring to the page of the annotation, you're right. I will fix this. In fact the exact detail of the annotation metadata will need some clarification depending on the original data the frontend will have, so it will propably change a bit (not really clear now how we store the "shape").

Also about pagination, i don't add the information here because i don't think it's necessary, but there is another technical debt subject on lack of pagination for many endpoints (/comments list is not paginated now) and we may decide to properly paginate the new/existing endpoints. I don't think it's needed for the POC, but that's something to keep in mind.

**Comment by knodelle** [comment]
done
