### ISSUE TITLE
Bug: Creating a user via tracimcli does not give the right rights on the agenda

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5573]
## Description and expectations

Creating a user via tracimcli does not give the right rights on the agenda.
On oldest version of Tracim, all necessary file/folder are created directly with the good rights.

At present we need to change rights on folder manualy to solve the problem.

### How to reproduce

- create user ith tracimcli
- go to the folder radicale_storage/collection-root/
=> the new folder created for the new user not have the good right.
With docker images, the rights need to be `www-data:www-data` but after using tracimcli command, the rights is only for `root:root`.

### Version information

- Tracim version: All version with the new agenda workflow/feature
- Related to the backend server

### Screenshots

________________________________________________

## Linked PR
#5580

## Implemented solution

Issue ref #5573 
PR ref: #5580 

- fix interactive mode of tracimcli by forcing resetting Depot.
- improve docker doc about how to correctly run tracimcli inside it (with correct rights).

**Comment by inkhey** [comment]
The problem is that tracimcli can be runned with another user than www-data.
I see 2 way to solve this:
- add parameters to tracimcli to chown file after directory creation.
- run tracimcli command as www-data in the docker, if we choose this way we should probably add some kind of helper to be capable to go in the docker directly in the correct directory with the good user.
