### ISSUE TITLE
Bug: stuck when trying to add a user to a space without choosing the role

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5687]
## Description and expectations

When adding a user to a space, from the space dashboard, if a role is not selected, a warning message pops up, but then the screen is stuck on a rotating circle and nothing happens. The page needs to be refreshed in order to get unstuck.
explained with gif on https://algoo.tracim.fr/ui/workspaces/165/contents/thread/68307

there is a discussion about how it needs to work : 
- preselect the space default role and have it checked by default on the adding screen
- make the button disabled until a role is selected
- use the space default role if no role is selected by the user

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: v4.2.2 build_080
- Web browser: 
- Version: 
- Device / System: work laptop

### Screenshots

________________________________________________

## Linked PR
#5714

**Comment by PhilippeAccorsi** [comment]
This is a regression and not a bug (cf discuss in your link.

**Comment by lebouquetin** [comment]
I think we should not set *reader* as default role if there is no defaut role define in the space otherwise, this is not coherent (i decide "no default" on creation screen but the software decide default is "reader".

I see 2 ways to fix this correctly:

- do not set reader if no default (and show an error if nothing selected)
- force a default role in the space creation wizard and space creation admin screen

**Comment by wwalden** [comment]
ok, this is updated now:
- in front, _reader_ is not set if no default
- in db, _default_user_role_ for a space is actually already set as "not null default reader"

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
