### ISSUE TITLE
Feat: Add to dos on advanced search

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5742]
## Feature description and goals

As a user I would like to :
- [x] Indexing children Todo content: Be able to find content depending on one of this direct children todo raw_content.
- [x] Facet: have "Tasks to do" option in "Only search in" filter. That returns the content that has the to do but search only on the author, assigned person and text of the to do.
-  Author indexing: Find content depending on the todo or comment author, this need probably clarification.  see https://github.com/tracim/tracim/issues/5756

note: backend should return the todo count like comment count.
## Prerequisites

None

## Implemented solution

- indexing todo content in advanced search to retrieve parent content.
- adding a filtering option on todo content for advanced search.
- adapt simple search for todo content to retrieve parent content

issue ref : #5742 
pr ref : #5749

**Comment by inkhey** [comment]
About having possibility to search in author of todo or comment of content, it may maybe make much sense to have another field "contributor" instead of "author" which mean everybody that has contributed in some way in the content including commenting and todo. Not sure we should make this work for other subcontent too and recursively, but it's technically possible.

**Comment by gbonaspetti** [comment]
Tested on branch (please make a new issue to the author item)

**Comment by gbonaspetti** [comment]
Done
