### ISSUE TITLE
✨ Feat: authorize the use of "." in a username

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#6171]
### Feature description

The field "username" in tracim should authorise the use of "." 
this is in order to resolve problems met when linking Tracim to an LDAP.

### How it works

Backend issue.
Username has to allow "."

### Related PR

#6177

**Comment by Skylsmoi** [comment]
to fix
- [x] documentation to start ldap server as dev
  - [x] in doc/backedn_specific/settings.md, the § LDAP auth, update ldap url: ...:10389 instead of :389
  - [ ] add internal at "auth_types = ldap,internal"
- [x] update backend regex to validate username in lib/core/user.py::_check_username_correctness
- [x] update frontend regex to validate username in frontend_lib/src/helper.js::checkUsernameValidity

**Comment by Skylsmoi** [comment]
we will close the opened PR and reopen it on develop to push the fixes for the 4.5.0 directly.

Todo:
- [ ] close PR 6174
- [ ] rename ldap param ldap_login_attribute to ldap_username_attribute
- [ ] add ladp param ldap_email_attribute
- [ ] make the 3 ldap param to save a specific ldap attribute 
  - ldap_username_attribute will save the tracim's username
  - ldap_email_attribute will save the tracim's email
  - ldap_name_attribute will save the tracim's publicName 
- [ ] remove the code that check if the old param ldap_login_attribute contains an '@' and handle it as email or username
- [ ] open the new PR for these fixes into develop to be merged for 4.5.x

**Comment by Skylsmoi** [comment]
released in 4.5.1
