### ISSUE TITLE
Better fixtures and test

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#619]
TODO:
- [X] wrapp lib usage in tests to avoid heavy refactoring when changing lib signature ( https://github.com/tracim/tracim/pull/2069)
- [x] convert current fixtures to pytest fixture style. ( https://github.com/tracim/tracim/pull/2089)
- ~~Avoid one fixture for all tests~~ . check #2120 
- ~~Create intelligent fixture, not used in all tests but common to some tests in order to avoid too much code duplication. This need discussion.~~ check #2120 
- ~~Avoid duplication of similar test, check for https://docs.pytest.org/en/latest/parametrize.html usage. this should probably be done after converting to pytest fixture style because parametrize doesn't work with pytest+parametrize by default , see https://stackoverflow.com/questions/18182251/does-pytest-parametrized-test-work-with-unittest-class-based-tests~~ . no  clear case where such modification is needed now.

**Comment by PhilippeAccorsi** [comment]
@inkhey can you explain here what is done, what is not yet developed?
And create separated issue for each functionnality.

Its better to have for exemple five specific issue, because we can work on each when we have time and merge & close issue when work is done. Now we have just one "big" issue and we dont know what is really done, what is not easy to solved.

Thanks.

**Comment by inkhey** [comment]
@PhilippeAccorsi i do think we can close this issue as #2120 new issue is created to fix problem that are not fixed here, other fix of tests (like using parametrisation) are too much unclear to be considered as true bug now. We do need case where current behavior is a problem to fix it.

**Comment by PhilippeAccorsi** [comment]
I close this issue., because no needed test (all test is in CI).
