### ISSUE TITLE
✨ Feat: allow system-wide parametric drowdown menu items (app custom action)

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#6250]
## Update 2023 12 05
A first step will be done here https://github.com/tracim/tracim/issues/6315 as a POC

___

### Feature description

In content listing and content view, there is a `...` menu giving access to actions related to the content. It would be interesting to be able to extend this with system-defined actions.

Example: allow to open a file in a remote application

![exemple menu contextuel](https://github.com/tracim/tracim/assets/907161/93f1ad1c-c040-407d-bea5-64c809aa9d6e)

The idea is to allow administrator to define in the server configuration a list of extra-buttons with associated actions.

This would be nice to have this configured through a JSON list of buttons for given dropdown menus / action lists.

Here is an example of what could be done:

The global structure could be something like this:
```
{
  "user-sidebar-dropdown": [
  ]
  "user-sidebar-shortcuts": [
  ]
  "content-in-list-dropdown": [
  ]
  "content-app-dropdown": [
  ]
  "space-dashboard-action-list": [
  ]
}
```

each item of the lists being something similar to this:

```
{
    "icon-text": "fa fa-edit",
    "icon-image": "https://placehold.co/600x400",
    "bg-hex-color": "#FF00DD",
    "font-hex-color": "#FFFFFF",
    "link": "http://pastebin.org/?label={content.label}&content={content.content}",
    "label": "Share on Pastebin",
    "workspace-filter": "123,456",
    "content-extension-filter": "txt,cpp",
    "content-label-regex": ".*source.*",
    "content-label-match": "jpg",
    "user-role-filter": "administrator,content-manager",
    "user-profile-filter": "trusted-user,"
}
```

**Comment by lebouquetin** [comment]
TODO before implementation:

- [ ] @Skylsmoi make a "large mesh estimate" for both "quick and dirty implementation" and "clean implementation" for the frontend part (assumption: the config comes with `/api/system/config`
- [ ] @lebouquetin make same thing for backend part

**Comment by Skylsmoi** [comment]
A working frontend hardcoded POC is avaible here: feat/6250__add_configurable_dropdown_from_backend

Visible on dropdown header of app file

Estimation:
- Quick & dirty: 2~3 days
  - not much of code
  - most of required time should be on r&d, naming and connection with backend
  - does not include test, doc, deployment
-  Clean implementation
  - hard to tell at this point of specification and definition of perimeter
  - it will also depend on how many places we would allow this configurable dropdown
  - at least 2 weeks

@lebouquetin

**Comment by lebouquetin** [comment]
Thanks for the feedback @Skylsmoi

I can't imagine *at least* 2 weeks of work for inserting a list of links in a component (given by the backend): you did half the job in a few hours.

**Comment by Skylsmoi** [comment]
it's because I hardcoded all of the things in my POC

My clean implementation estimation expects a very reusable mechanism in any components without any overlap with any existing customizable mechanism. And the mechanism will have some specificity depending on the component type (whether it's a dropdown, a button, an input text ...). Also, I'm expecting many surprises depending on the component type.

2 weeks might be exaggerated yes but it also reflects that, currently, I don't really know how much time it'll take. I probably should have given a number though

**Comment by lebouquetin** [comment]
This allows:

- ease of configuration
- powerfullness
- generic and resilient frontend implementation

What do you think?

**Comment by Skylsmoi** [comment]
mmh, would this mean a regex for each property? Eg: content_regex that frontend apply on the content name only

or unnamed regex that frontend apply on each filterable properties? Eg: filter_regex that frontend apply on content name, space id, user profile...

Making the backend do most of the configuration/filtering seems a good idea though.

I'm only a bit concerned by the fact that backend will send, through a JSON property, code from a configuration file to be executed by frontend . That doesn't seem safe, even if it's only regexes

**Comment by lebouquetin** [comment]
> I'm only a bit concerned by the fact that backend will send, through a JSON property, code from a configuration file to be executed by frontend . That doesn't seem safe, even if it's only regexes

Interesting point. Let's take time to think about it.

**Comment by Skylsmoi** [comment]
updated description with new info

**Comment by Skylsmoi** [comment]
Updated description with the update from 2023 12 05 and added:
```json
    "icon-text": "fa fa-edit",
    "icon-image": "https://placehold.co/600x400",
    "bg-hex-color": "#FF00DD",
    "font-hex-color": "#FFFFFF",
```
in example of item list

**Comment by lebouquetin** [comment]
Use cases to be answered:

- link to external application based on mix of workspace_id, content_type, content_label rexeg
- link to prefilled github issue, for example: required fields are at least label + original url (like `https://algoo.tracim.fr/ui/contents/<content_id>`)
- links to fixed aplications associated to a series of pattern / filters (eg: send "open canva" for png/jpeg files found in given workspace)
- links to fixed aplications associated to a series of pattern / filters (eg: send "open canva" for png/jpeg files found in given workspace)
- internal links to
  - fixed content, workspace (eg: link to documentation for "suivi d'activité" files)
  - content author profile (in order to be able to call him/her)
  - last revision content author (in order to be able to call him/her)
  - comment author (in order to be able to call him/her)
- static links to remote apps: dolibarr, webmail, algoo website,

Fields which seem to be required for url fillin:

- content.content_id,
- content.label,
- content.content,
- content.author,
- content.url (generic one: https://<instance>/ui/contents/<id>)
- content.author_id,
- content.last_revision.author_id
- content.last_comment.author_id

@Skylsmoi

**Comment by Skylsmoi** [comment]
My answers at current dev state (20240515):



Use cases to be answered:

- link to external application based on mix of workspace_id, content_type, content_label rexeg
  - ok
- link to prefilled github issue, for example: required fields are at least label + original url (like `https://algoo.tracim.fr/ui/contents/<content_id>`)
  - not sure
- links to fixed aplications associated to a series of pattern / filters (eg: send "open canva" for png/jpeg files found in given workspace)
  - ok
- internal links to
  - fixed content, workspace (eg: link to documentation for "suivi d'activité" files)
    - ok
  - content author profile (in order to be able to call him/her)
    - currently not but will do
  - last revision content author (in order to be able to call him/her)
    - currently not but will do
  - comment author (in order to be able to call him/her)
    - seems equivalent to "content author profile" above
- static links to remote apps: dolibarr, webmail, algoo website,
  - ok

Fields which seem to be required for url fillin:

- content.content_id,
  - ok
- content.label,
  - ok
- content.content,
  - not sure / no
- content.author,
  - will do
- content.url (generic one: https://<instance>/ui/contents/<id>)
  - will do
- content.author_id,
  - will do
- content.last_revision.author_id
  - no
- content.last_comment.author_id
  - no

**Comment by Skylsmoi** [comment]
First implementation released in build_133

For evolution, see https://github.com/tracim/tracim/issues/6494
