### ISSUE TITLE
thread: Blank description is impossible in threads after modification

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#634]
At present:

when you create new thread, you can post first message. 
After that, you can modify description of this thread but its not possible to leave blank description.

Expected:

improve this feature, exemple => when you create thread , you add description and not first message??

**Comment by Quiwy** [comment]
@PhilippeAccorsi : seems we can close this issue, what do you think?

**Comment by PhilippeAccorsi** [comment]
This problem still exist in v2.

- create new thread
- add some text
- save
- edit message and erase all
=> try to save. Error `Attention Error while saving the comment` appear.

So I seen two solution for that:
- not permit to click on save if empty
- show explicit message about why we can't save empty message.

**Comment by Quiwy** [comment]
Ok, I guess the problem is with all comments, whether it's on a thread, a news, or anything else.

The only difference is that on a thread, the first comment is the beginning of the discussion, is that the problem?

Do you have any use case for this? Deleting the thread is not sufficient, instead of having an empty comment?

**Comment by PhilippeAccorsi** [comment]
> Deleting the thread is not sufficient

I don't want to delete thread but just the first message because I have updated the title and this is enought.

But right, now user can delete his own comment so this is ok.

I close this issue.
