### ISSUE TITLE
🐛 Bug: When using ldap,internal auth_type, internal auth doesn't work

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6355]
### Tracim version

4.7.1

### Issue description

When using ldap,internal auth_type, internal auth doesn't work.

Using a local tracim account doesn't work for login.

### How to reproduce

1. Have a LDAP connected tracim with "auth_type: ldap, internal" in development.ini
2. create an account using tracimcli
3. try to connect to that account

**Comment by Millefeuille42** [comment]
Turns out this behaviour only happens for `UNKNOWN` `auth_type` due to how the current flow is implemented:

1. Iterate over the allowed `auth_types`
2. Go to LDAP auth function
3. LDAP auth flow is continued if user has `auth_type` of `LDAP` or `UNKNOWN`
4. LDAP auth flow raises `WrongLDAPCredentials` exception
5. global auth flow catches this exception as a "fatal" exception (by that I mean user can't login)

We should change the exception raised on step 4 if the user's `auth_type` is `UNKNOWN` to `WrongAuthTypeForUser`, then the auth flow will continue with the other allowed `auth_types`

All of the provided code is from `backend/tracim_backend/lib/core/user.py`
Step 1 and 5 (line 756): 
```python
        for auth_type in self._config.AUTH_TYPES:
            if auth_type == AuthType.SAML:
                continue
            try:
                return self._authenticate(
                    login=login,
                    password=password,
                    ldap_connector=ldap_connector,
                    auth_type=auth_type,
                )
            except AuthenticationFailed as exc:
                raise exc
            except WrongAuthTypeForUser:
                pass
```

Step 2 (line ):
```
        try:
            if auth_type == AuthType.LDAP:
                if ldap_connector:
                    return self._ldap_authenticate(user, login, password, ldap_connector)
                raise MissingLDAPConnector()
            elif auth_type == AuthType.INTERNAL:
                return self._internal_db_authenticate(user, login, password)
            else:
                raise UnknownAuthType()
        except (
            EmailRequired,
            WrongUserPassword,
            WrongLDAPCredentials,
            UserDoesNotExist,
            UserAuthenticatedIsDeleted,
            UserAuthenticatedIsNotActive,
            TracimValidationFailed,
        ) as exc:
            raise AuthenticationFailed('User "{}" authentication failed'.format(login)) from exc
```

Step 3 (line ):
```
        if user and user.auth_type not in [auth_type, AuthType.UNKNOWN]:
            raise WrongAuthTypeForUser(
                'User "{}" auth_type is {} not {}'.format(
                    login, user.auth_type.value, auth_type.value
                )
            )
```

Step 4 (line ):
```
        data = ldap_connector.authenticate(login, password)
        if not data:
            raise WrongLDAPCredentials("LDAP credentials are not correct")
```
