### ISSUE TITLE
✨ Feat: Kanban card color should be the background color 

### ISSUE THREAD

**Issue by floreal15** [tracim/tracim#6356]
### Feature description

The color set for the Kanban should be the background of all the Kanban card, not just a border

### How it works

When the front show a Kanban card the background color of the element should be of the color set

### Related PR

https://github.com/tracim/tracim/pull/6415

**Comment by Millefeuille42** [comment]
Note: Considering the current default color of the current kanban card, which is far from optimal we should eventually:

- Provide a script to change the actual cards having the default color to white-ish
- Change the default color to white-ish

**Comment by Skylsmoi** [comment]
The color is saved in the json of the depot file of the kanban, updating the existing ones won't be that easy

**Comment by Millefeuille42** [comment]
Indeed, not easy. Considering that some might have their depot in a s3 storage :/

**Comment by Skylsmoi** [comment]
indeed

**Comment by lebouquetin** [comment]
What we can do is:

- we do nothing except telll the users their kanban will be ugly until they update it manually
- we provide some documentation in order to help users to upgrade manually their kanban by setting a default color to every card of every kanban

Another solution would be to provide a documentation and/or bash script which enligthen all colors found in the kanban (this would be executed manually)

**Comment by floreal15** [comment]
Another solution is to make the text color change from black to white depending on the background color, weather choosing black or white as text color will be calculated according to contrast ratio : https://www.w3.org/TR/2008/REC-WCAG20-20081211/#contrast-ratiodef
