### ISSUE TITLE
🐛 Bug: improve responsiveness for popup new workspace on small screen

### ISSUE THREAD

**Issue by floreal15** [tracim/tracim#6358]
### Tracim version

4.8.0

### Issue description

When using small size screen, the validate button of popup to create a workspace is hard to click because it goes under to bottom of the popup.

Solution is to either make the popin responsive or, probably better and easier, make the popup scrollable.

### How to reproduce

1. be on a small size screen . Eg: 1024x580
2. try create a space
3. The validate button is barely clickable

### Screenshots

![Sélection_021](https://github.com/tracim/tracim/assets/11177014/9b396dce-2abe-4fc5-a2b8-5bfc2b292052)

### What browsers are you seeing the problem on?

any

### What devices are you seeing the problem on?

landscape display with less than 600px height

### Related PR

 #6379

**Comment by Millefeuille42** [comment]
This issue only exists on workspace creation popin, since it is designed differently from other popins.

The fix is designed to be quick but not totally solves the problem. The problem being how the workspace creation popin is designed and it should then be redesigned to be scrollable no matter the changes to the content that will be made
