### ISSUE TITLE
✨ Feat: Update supported version of python

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6360]
### Feature description

Our CI currently test for python 3.7, 3.8 and 3.9.

We need to aim for python 3.9, 3,11 and 3.12.

We need to validate it is working on later version and update CI and documentation.

**Comment by Millefeuille42** [comment]
#6366 needs to be taken into consideration for this issue

**Comment by Skylsmoi** [comment]
Status of dev at 2024 04 05:

- 3.9, 3.10, 3.11 works (tested on debian: bookworm and ubuntu 20.04)
  - from python 3.11, reinstalled tracim
    - then fixed what broke
    - tested with pushpin, postgres, redis and 2 backend plugin : autoinvite and supported mime type
    - need to test (non exhaustive): elastic search, docker image creation and deployment, preview generator, sqlite, email (summary, notif, lost password...), ldap, saml, support minio, webdav
  - in progress: running the CI in a specific setup only for this branch (using specific tag)

**Comment by Millefeuille42** [comment]
Updated all non-breaking dependencies.

Locked version of 
- sqlakeyset, because it's API changed
- sqlalchemy
- alembic
- zope-sqlalchemy
- elasticsearch, because latest versions are not necessarily compatible with the versions of ES we use, and the API changed.

Did the same for dev tools (lint) because rules change when updating and we would have to edit all of our code if we did so.

**Comment by Millefeuille42** [comment]
Issue solved by https://github.com/tracim/tracim/pull/6495 

https://github.com/tracim/tracim/pull/6426 needs to be closed and a new PR and Issue associated to upgrading dependencies must be opened.
