### ISSUE TITLE
🐛 Bug: Mention autocomplete can shows deactivated members of a space

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6398]
**FIRST ACTION IS TO UPDATE DESCRIPTIOn AND TITLE OF THE ISSUE**

### Tracim version

4.8.0

### Issue description

When creating a mention, the autocomplete popin sometimes show deactivated users.

It appears endpoint GET /api/users/234/workspaces/all/settings returns deactivated users, it should do so when passed a path parameter and the default behavior should be to do not.

### How to reproduce

The issue happens intermittently.

1. Open a space
2. Open a content of the space
3. In the comment area, type @
4. The autocomplete popin sometimes shows deactivated users

### Related PR

https://github.com/tracim/tracim/pull/6501

**Comment by floreal15** [comment]
At the current state (tracim 4.8.0) when using a mention, tracim will use either know member list ( for the recent activities and dashboard) or the current workspace member list to find the list of available user for mention,
removing the deactivate user from know members will result in them not being in the list of user we could mention but also their name won't be display on content they have create before because they will be unknown by the front end;
I see few possibilities here:
- do not show the deactivate user, even what they did before being deactivated will appear as create by unknown.
- separate know member list in tow list in front end, one to store user that could be mentioned and  another to store the full list of user to get the full list of user to be able to show who create a content even if deactivate
- know member list return also if each user is deactivated or not and the front filter by depending if deactivate user should be show or not

**Comment by lebouquetin** [comment]
@Millefeuille42 could you comment here what solution you are implementing? In last comment, there are 3 options, the first thing to do is to comment here what you plan to do.

**Comment by lebouquetin** [comment]
I agree this is the best solution :+1:
