### ISSUE TITLE
🐛 Bug: Writing the title of a news is slow

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6408]
### Tracim version

4.8.0+build_125

### Issue description

When setting the title of a news in the popin, characters appears with a delay after being typed on keyboard.

This shows a strong activity in the javascript main thread meaning a lot unnecessary work is done by browser.

This unnecessary work load need to be identified and removed.

### How to reproduce

Type a new news, click "Publish", the popin for the title appears, type quickly in the input for the title

### Related PR

https://github.com/tracim/tracim/pull/6410

**Comment by floreal15** [comment]
The issue is that in the Publications component, the value of the title is stored as a State and so with each modification, the entire component is re-rendered causing lag;
In order to fix that the chosen solution is to create a component PopupSetPublicationTitle used to store the state of the title.
This solution has been chosen because it's the same mechanism that is used in the other app when they used the CardPopupCreateContent component; each app has its own component how store the contentName value of the CardPopupCreateContent component and implement the necessary function to create the content wanted.
In case of the news, the Publications component is the one how created the news because it has the value of the text written and file given, so the popup is only to write a title and send it back to Publication so that it could create the news.
