### ISSUE TITLE
✨ Feat: web notification improvement

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#6428]
### First things to do

1. read the french description
2. propose fake screenshots and a (human-driven) demo with PO
2. propose a checklist of atomic tasks
3. validate the task list with PO
4. implement first version of the feature

### Feature description

**Issue in French - sorry;)**

## Currently - Aujourd'hui le mur des notifications montre tout et agrège tout ce qui me concerne.

l'intégralité des actions faites sur tracim remontent via les TLM

un algorithme frontend filtre et agrège ce qui doit l'être pour présenter un mur de notification

En gros, l'algorithme frontend est le suivant :

1. un TLM remonte via le socket
2. le frontend applique le filtre pour savoir si le TLM doit être pris en compte dans le mur de notification ou ignoré
3.  l'algorithme d'agrégation est ré-exécuté pour savoir comment afficher ce nouveau TLM (nouvel item dans la liste ? ou agrégation dans un bloc existant)

Cela s'applique à l'intégralité des TLM remontant et concernant l'intégralité des espaces dont je suis membre.

Merci de me confirmer que c'est bien ceci qui se déroule côté frontend.
Edit (Skylsmoi at 2024 05 13): I confirm this is what's happening. The point 2 is a bit different though since it is each TLM handler that calls the handleNotification function (from ReduxTlmDispatcher.jsx) to decide whether or not the TLM should be added to the notification wall.

## Expected - Idée d'amélioration pour proposer une stratégie plus granulaire

point préliminaire: la config des notifications frontend serait enregistrée dans la table "user_config" qui stocke des clé/valeur sans que le backend ait connaissance de ce qui y est stocké (le backend sait qu'on stocke un truc mais il ne sait pas quoi et il ne l'exploite pas directement).

La configuration serait la suivante :

- pour chaque espace dont je suis membre, un paramétrage par défaut est déterminé:
  - soit je suis notifié par défaut
  - soit je ne suis pas notifié par défaut.
- Le paramètre pourrait s'appeler `webui_notify` et il vaudrait `true` ou `false` et qui serait donc le comportement par défaut pour l'espace
- pour chaque contenu on aurait un paramètre qui "override" le paramétrage par défaut : `webui_notify` qui vaut `true` ou `false`

Rappel : cette configuration est propre à l'utilisateur.

L'algorithme serait ensuite le suivant :

1. un TLM remonte via le socket
1. le frontend applique le filtre pour savoir si le TLM doit être pris en compte dans le mur de notification ou ignoré (c'est le mécanisme actuel, générique, on ne le change pas)
1.  le frontend applique un second (nouveau) filtre pour savoir si le TLM doit être pris en compte pour l'utilisateur :
  1. si `webui_notify` de l'espace est à `true` :
    1. si `webui_notify` du contenu est à `false` -> on drop le TLM
    1. sinon -> on garde le TLM
  1. si `webui_notify` de l'espace est à `false` :
    1. si `webui_notify` du contenu est à `true` -> on garde le TLM
    1. sinon -> on drop le TLM
1. l'algorithme d'agrégation est ré-exécuté pour savoir comment afficher ce nouveau TLM (nouvel item dans la liste ? ou agrégation dans un bloc existant)

Avantages :

- on conserve le comportement actuel par défaut. Notamment si on n'a rien configuré de spécifique : les notifications continuent comme aujourd'hui ; et **on peut toujours filtrer globalement au niveau de l'instance**
- on permet une granularité fine de notification dans l'interface web.

## Comment configurer l'abonnement aux notifications ?

Déjà c'est que du frontend donc c'est un bon point (on stocke en backend, mais l'intelligence est "pur JS")

La configuration se ferait donc de deux manières :

- pour la configuration de l'espace, on gèrerait ça sur le tableau de bord avec un paramétrage comme ci-dessous

![img1](https://github.com/tracim/tracim/assets/907161/8b74f382-6a9d-4306-bc54-70093362297c)

- pour la configuration liée aux contenus elle serait semi-automatique :
  - dans le menu contextuel d'un contenu on ajouterait deux boutons :
    - un bouton "s'abonner au contenu" qui mettrait à jour la configuration en settant `webui_notify` à `true`. note : ce bouton ne s'afficherait pas si on a déjà `webui_notify` à `true` pour ce contenu
    - un bouton "se désabonne du contenu" qui mettrait à jour la configuration en settant `webui_notify` à `false`. note : ce bouton ne s'afficherait pas si on a déjà `webui_notify` à `false` pour ce contenu
  - dès qu'on interagit (création, réaction, commentaire, modification, tâche, etc)
    - si `webui_notify` existe et est à `false`, on ne fait rien
    - sinon, le frontend set `webui_notify` à `true` (sauf si on a déjà setté `webui_notify` à `false` car dans ce cas c'est qu'on a explicitement demandé à ne pas être notifié)
    - la configuration est enregistrée en backend et un TLM est envoyé pour mettre à jour tous les onglets / tous les clients

![img2](https://github.com/tracim/tracim/assets/907161/3fdf335c-1013-4c77-ae5c-96470eb94a3d)

Un bouton dans l'entête de l'application pourrait  également permettre de s'abonner / se désabonner.

## Questions / réponses

> Pourrait-on avoir avec ce mécanisme de suivi d'un contenu, les réactions dans le murs des notifications pour les contenus que l'on a décidé de suivre ?

Oui, c'est l'idée.

> Les mentions, au moins les personnels, seront-elles prioritaire au réglage de suivi d'un contenu ?

Oui, les mentions devraient toujours passer.

> une partie des config gagnerait a se retrouver dans le profil du compte, comme ce que l'on a pour la gestion des espaces. Cela permettrait d'avoir des pages dédié, potentiellement un peu verbeuse, sans impacter la lisibilité des pages courantes.

C'est bien pour une gestion en masse mais pas au quotidien. Au quotidien il faut que ce soit directement dans les contenus

> Je pense juste que le webui_notify des contenues devrait avoir trois états ( true, false, undefined ? ) 

L'idée est qu'on a un statut `true`, `false` ou rien de défini (qui correspond à `undefined`)

> Je suis d'accord la dessus, les contenus dont l'etat de suivi n'est pas défini devraient hériter du comportement de leur espace parent (ou juste du parent proche donc son contenu parent ?)

Oui c'est ce qui est attendu. 

Pour préciser : 

- on ne configure rien par défaut.
- pas de configuration = comportement défini par la config de l'espace .

Ça rejoint ce qui est dit sauf que ça permet de ne pas décrire explicitement chaque contenu :

- si la clé "contenu xxx" existe, on prend la valeur (`true` ou `false`)
- sinon on prend la valeur de l'espace.

- dès qu'une interaction est faite par l'utilisateur, on définit la config (donc on n'est plus sur une valeur par défaut)

### How it works

La configuration doit être stockée dans "user config" via les routes `/api/users/{user_id:\d+}/config`

### Related PR

https://github.com/tracim/tracim/pull/6518

**Comment by Millefeuille42** [comment]
This is how it should look like for V1:

In space status bar on the right:
![image](https://github.com/tracim/tracim/assets/42064302/52671ddf-11b2-42e9-bdd7-335ff1ef46de)

With popover displayed:
![image](https://github.com/tracim/tracim/assets/42064302/1b086970-adf9-4548-b289-e31f5e33ca03)

In user space settings:
![image](https://github.com/tracim/tracim/assets/42064302/fd0e68e1-e2e9-4f81-85cb-f9aeff4fe378)


For the technical specifications for V1:
- Only do web notification subscription for spaces
- Store configuration in `user_configs`
  - in the field `space.<id>.web_notification`
- Filter everything except individual mentions

**Comment by lebouquetin** [comment]
In the help popin, the following text should be changed:

When disabled, mentions from this workspace will be hidden from your notification wall -> When disabled, **notifications** from this workspace will be hidden from your notification wall -> 

@Millefeuille42

**Comment by Millefeuille42** [comment]
My bad. It is actually fixed but I forgot to take a new screenshot. Will fix

**Comment by Millefeuille42** [comment]
fixed

**Comment by Skylsmoi** [comment]
During development Mathieu and I found out a historical issue.
We investigated it and we plan on fixing.

The issue is manual re-affectations of state or props of components in tracim. Since these values came from redux, it ended up updating redux during the next action called. But the action did update the reducer `user` even though the reducer have no action reducer to handle it.

The reason is that when manually re-affecting redux from, for example, a props, it will be visible in redux dev tools during the next action called in the diff.

To fix:

- App html-document, every affectations related to updating notify_all_members_message
- App file, every affectations related to updating notify_all_members_message

Problem is, theses redux update should have been from a TLM. But, since the issues makes it to work fine, such TLM were not required and, therefore, were not implemented.

So, in this issue, the TLM user_config.modified when the user configuration change must be sent.

The CORE_ENTITY_TYPE `user_config` does not yet exists and must be created in frontend (frontend_lib/src/tracimLiveMessage.js)  and backend



And, the new config space.:id.web_notification should follow the same pattern

**Comment by Millefeuille42** [comment]
Above comment will probably not be adjusted in V1 in order to be able to release in time.

**Comment by Millefeuille42** [comment]
It has been decided to prevent administrators from editing other user's web notification, at least for V1.

- Because `UserSpacesConfig` uses `member` schem which do not contain the user config
- Because it doesn't seem relevant to give these permissions to the administrator

**Comment by Skylsmoi** [comment]
Development status at 2024 06 19

The subscription has been implemented for for spaces.

Some issues has been reported during development. These issues **are not blocking** and web notification feature will be improved on later versions.
Issues:

- 1 - Inconsistency between the number of notification and mention returned by backend and displayed to user
  - info from backend in endpoint `/api/users/:userId/messages/summary?exclude_author_ids=:userId&exclude_event_types=&include_event_types=mention.created`
  - inconsistency because frontend will filter that number depending on subscribed spaces
- 2 - A messages on an unsubscribe space should be considered read?
  - Currently, it is considered unread. 
  - Issue is that, if a user has a space as unsubscribe for a long time and a lot of things happens in that space, if the user re-subscribe to the space, he will receive a lot of messages on next page reload. Also
  - Also, backend keep sending unread notification of unsubscribed spaces which will keep growing and use a lot of resources over time
- 3 - In user recent activities (/ui/recent-activities), should we filter the activites from spaces the user is unsubscribed?

Possible responses:
1: create a query param on endpoint `/api/users/:id/messages/summary`: **workspace_id_excluded_except_mention** that the frontend would send to backend to list each spaces the user is subscribed to
2: create an endpoint to mark a whole space as "read" (similar to "mark all as read") and call this endpoint when we resubscribe to a space. This wont fix the increasing data size of unread mention though
3: will decide later
