### ISSUE TITLE
LDAP: add ldap to tracim

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#657]

**Comment by inkhey** [comment]
uncomplete feature here : https://github.com/tracim/tracim_v2/tree/feature/ldap

**Comment by inkhey** [comment]
https://github.com/tracim/tracim/pull/1139 support new a sort of chained auth system to allow multiple auth method for both login and basic_auth mecanism (email/password typed auth)

As it doesn't make sense to modify password for a ldap auth, it remain unclear how to deal with both chaining mecanism and disable password modification for user.
One way to deal with this is to adapt user model in order to add it auth mecanism type info directly here.

**Comment by PhilippeAccorsi** [comment]
FI:
If you want to use only LDAP you need to used INTERNAL in development.ini for the first connection with an administrator to change profil of one LDAP user. After that you can deactivate INTERNAL authentification.

**Comment by PhilippeAccorsi** [comment]
Test make with local server.
LDAP is working good.

Verified.
