### ISSUE TITLE
Plug the Admin Workspace page

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#779]

**Comment by AlexiCauvin** [comment]
see : https://github.com/tracim/tracim/issues/726

**Comment by Skylsmoi** [comment]
files in /frontend_app_admin_workspace_user/component

@AlexiCauvin To fix:
- html and css of the form add member should be the same as the code from the dashboard add member form. I'll create a specific component and refactor later but if it is already exactly the same code, it will be easier to refactor. Dont forget to add `// @FIXME` comments (with name and date) to delimit code duplication
- fix css differences with admin workspace. switch from one to the other should not allow to use any variation in display. Apart from some margin top/bottom due to specific buttons
- merge css rules that applies to both pages (admin user and admin workspace) using `.adminWorkspacePage, .adminUserPage` stylus declaration. Specific rules should still be declared in a specific class (e.g. by separating the 2 classes)
- apply the new rule about the use of bootstrap alias classes (mt-2, d-flex ...)
- check that btns actually are <button> tag

**Comment by AlexiCauvin** [comment]
@Skylsmoi everything requested above has already been done, is the message still relevant?

**Comment by PhilippeAccorsi** [comment]
Ok.

**Comment by PhilippeAccorsi** [comment]
Verified.
