### ISSUE TITLE
All content: option "Move" for content

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#789]
## new feature

Add possibility to drag-and-drop content/folder in one shared space

## Expected

- [x] drag-and-drop working for content
- [x] drag-and-drop working for folder
- [x] its possible to move folder with content in another place
- [x] Add something to explicit to user that drag-and-drop exist (and is limitation?)

## Impacted components

- backend
- frontend

Edited for 2.3

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi use pop-up to select destination.
move is possible for content manager or more

Don't show option if you don't have right.
You can move everywhere you hare content manager or more.

**Comment by lebouquetin** [comment]
@Skylsmoi @AlexiCauvin do we have the popup integrated?

**Comment by Skylsmoi** [comment]
no, that popup has not been specified

**Comment by PhilippeAccorsi** [comment]
@lebouquetin @Skylsmoi do you want to use this issue to develop move feature for tracim 2.3, or do you prefer I close this issue and create a new one.

If we save this issue, I can change description.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi if that issue is fixed, I think it's better to close it and open another one

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi I guess we can, yes

**Comment by basilelegal** [comment]
Cannot move any type of files, the handle seems broken

**Comment by Skylsmoi** [comment]
Indeed, only in firefox

**Comment by basilelegal** [comment]
The functionnality is tested, I could not find bug.

### Ergonomy feed back
  - On my 15" screen with a 1080p resolution, the drag handle gets really small.
  - When used quickly, I tend to try to drag using the icon and not the handle

_proposition: extend the handle at least to the icon_

  - If you drag a content (doesn't happen on a folder) but you don't click on the handle, the browser will create a draggable image that can be mistaken with our functionnality

_Can that be prevented ? maybe here https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#Handle_the_drop_effect_

 - Because contents are alphabetically sorted when you move a content it doesn't show where you thought it would be.

_proposition: smooth a little the transition, a flash lowering the opacity of the content list to show it was updated, a flash of color in the background of the content to show where it is._

also https://github.com/tracim/tracim/issues/1924

**Comment by lebouquetin** [comment]
@Skylsmoi @basilelegal where is the commit which fixed the issue on firefox? issue must allow to understand what code has been written/modified/deleted for fixing the issue.

Currently, it's impossible to understand what was broken on firefox.

**Comment by basilelegal** [comment]
@lebouquetin it is fixed by #1936

**Comment by lebouquetin** [comment]
thanks @basilelegal

**Comment by Skylsmoi** [comment]
I forgot to mention the issue in the PR description

**Comment by LucBarry** [comment]
Verified
