### ISSUE TITLE
Workspace: bug : sidebar stay open on first workspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#796]
At present

If you create workspace, you see the new dashboard of this workspace but in sidebar, the first workspace stay open and the new one not.

Expected

If you create new workspace, you are redirect to this new workspace in the sidebar.

**Comment by Skylsmoi** [comment]
I have tried a few things, I dont have any simple solution right now.
Problem is: after creating the workspace, the app send 2 custom events:
- refreshWorkspaceList: which is handled by <Sidebar> and will refresh the list of workspaces to get the new one
- redirect: which is handled by <Tracim> that will redirect to the dashboard of the new workspace

Theses 2 events are sent simultaneously, <Sidebar> refresh workspace list process already opens workspace from the id in the url. But, the issue here is that when refreshing workspaces, url might (and actually wont) be already changed by the event 'redirect'. This is due to react redux and router process that handles pack of actions asynchronously to improve performances.

One possible issue is to handle a queue of custom events and to handle them one by one. Refactor required.

**Comment by lebouquetin** [comment]
what is the price of the refactor? (how many hours or days?)

**Comment by Skylsmoi** [comment]
I'd 1 to 2 days

**Comment by Skylsmoi** [comment]
I have found a workaround.
the customEvent 'refreshWorkspaceList' now an optional parameter to tell the id of the workspace to open in sidebar.
It fixes the issue

**Comment by PhilippeAccorsi** [comment]
Verified.
