### ISSUE TITLE
Replace old color variables with new ones 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#797]
Replace the main colors defined in the css files by the classes defined in the index.

**Comment by Skylsmoi** [comment]
There is still one thing to do:
- remove from Variable.styl the variables that aren't used anymore

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi, to test this issue, it is necessary to check if the colors of the theme are given by the classes : 
- primaryColorBg
- primaryColorBorder
- primaryColorFont

Then check if the buttons have the following classes :
- outlineTextBtntn
- highlightBtn

**Comment by Skylsmoi** [comment]
@AlexiCauvin this is a good description of the tests required but, you must assume the tester is not a developer, therefore, you would not ask him/her to check if classes are present because it requires to use browser inspection tools.
A better test description for this issue could be :
Check that btns are only of 2 kind:
- transparent with bordered color, or
- with background color and white font
- also check that there is the color transition on mouseover (color change should not be instant, there is a .5s transition duration)
- etc...

**Comment by PhilippeAccorsi** [comment]
Verified.
