### ISSUE TITLE
Cannot load api backend on windows 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#819]
After a git pull, i couldn't import the API via the backend anymore. 

the back server starts normally:  
![image](https://user-images.githubusercontent.com/16293214/44094932-c45496c6-9fd7-11e8-9742-43b08b096054.png)
 
It displays only one error  : 
![image](https://user-images.githubusercontent.com/16293214/44094959-d7afce98-9fd7-11e8-89ad-80e40c216a35.png)

On the front page we have a blank page and this error message : 
![image](https://user-images.githubusercontent.com/16293214/44094980-ec299368-9fd7-11e8-9794-29d43c506889.png)

**Comment by inkhey** [comment]
Login endpoint error is probably normal login endpoint is available only on POST, not on GET.
To know more about the issue, whoami endpoint should be tested manually to know more about the issue.
All we know actually with this issue is that there is a trouble with database. the most probably is that database is not correctly updated.
To have more result about error, you can enable debug in development.ini : 
`
debug = True
`

**Comment by lebouquetin** [comment]
this issue is fixed.
